Repository mitodl/mit-learn, pull requests merged in 2023-08, with the labels that each got.

#24 Generate OpenAPI spec, Type definitions, and API Client
  .github/workflows/ci.yml
  .prettierrc.json
  README.md
  channels/serializers/channels.py
  channels_fields/serializers.py
  course_catalog/models.py
  course_catalog/serializers.py
  frontends/api/.openapi-generator-ignore
  frontends/api/package.json
  frontends/api/src/generated/.openapi-generator/FILES
  frontends/api/src/generated/.openapi-generator/VERSION
  frontends/api/src/generated/api.ts
  frontends/api/src/generated/base.ts
  frontends/api/src/generated/common.ts
  frontends/api/src/generated/configuration.ts
  frontends/api/src/generated/index.ts
  frontends/api/tsconfig.json
  open_discussions/urls_spectacular.py
  openapi.yaml
  package.json
  scripts/generate_openapi.sh
  scripts/test/openapi_spec_check.sh
  scripts/test/python_tests.sh
  yarn.lock
Labels: Needs Review

#25 New Api V1 for learning resources
  learning_resources/constants.py
  learning_resources/factories.py
  learning_resources/migrations/0002_alter_learningresource_unique_together.py
  learning_resources/migrations/0003_alter_learningresource_resource_type.py
  learning_resources/models.py
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  learning_resources/urls.py
  learning_resources/views.py
  learning_resources/views_test.py
  open_discussions/urls.py
Labels: Needs Review

#29 OpenAPI Generation for Learning Resources + Expose documentation
  course_catalog/urls.py
  frontends/api/src/generated/api.ts
  learning_resources/migrations/0004_alter_learningresourceimage_url.py
  learning_resources/models.py
  learning_resources/serializers.py
  learning_resources/views.py
  open_discussions/settings_spectacular.py
  open_discussions/urls_spectacular.py
  openapi.yaml
Labels: Waiting on author

#30 Make space for new homepage / pages
  frontends/infinite-corridor/src/App.tsx
  frontends/infinite-corridor/src/components/Header.test.tsx
  frontends/infinite-corridor/src/components/LearningResourceCard.test.tsx
  frontends/infinite-corridor/src/components/LearningResourceCard.tsx
  frontends/infinite-corridor/src/infinite-pages/ArticlePage.tsx
  frontends/infinite-corridor/src/infinite-pages/DemoPage.test.tsx
  frontends/infinite-corridor/src/infinite-pages/DemoPage.tsx
  frontends/infinite-corridor/src/infinite-pages/HomePage.test.tsx
  frontends/infinite-corridor/src/infinite-pages/HomePage.tsx
  frontends/infinite-corridor/src/infinite-pages/SearchPage.test.tsx
  frontends/infinite-corridor/src/infinite-pages/SearchPage.tsx
  frontends/infinite-corridor/src/infinite-pages/field-details/EditFieldAppearanceForm.test.tsx
  frontends/infinite-corridor/src/infinite-pages/field-details/EditFieldAppearanceForm.tsx
  frontends/infinite-corridor/src/infinite-pages/field-details/EditFieldBasicForm.test.tsx
  frontends/infinite-corridor/src/infinite-pages/field-details/EditFieldBasicForm.tsx
  frontends/infinite-corridor/src/infinite-pages/field-details/EditFieldPage.test.tsx
  frontends/infinite-corridor/src/infinite-pages/field-details/EditFieldPage.tsx
  frontends/infinite-corridor/src/infinite-pages/field-details/FieldAdminApp.tsx
  frontends/infinite-corridor/src/infinite-pages/field-details/FieldPage.test.tsx
  frontends/infinite-corridor/src/infinite-pages/field-details/FieldPage.tsx
  frontends/infinite-corridor/src/infinite-pages/field-details/FieldPageSkeleton.tsx
  frontends/infinite-corridor/src/infinite-pages/field-details/WidgetsList.test.tsx
  frontends/infinite-corridor/src/infinite-pages/field-details/WidgetsList.tsx
  frontends/infinite-corridor/src/infinite-pages/field-details/components/FieldAvatar.test.tsx
  frontends/infinite-corridor/src/infinite-pages/field-details/components/FieldAvatar.tsx
  frontends/infinite-corridor/src/infinite-pages/field-details/components/FieldMenu.test.tsx
  frontends/infinite-corridor/src/infinite-pages/field-details/components/FieldMenu.tsx
  frontends/infinite-corridor/src/infinite-pages/resource-lists/AddToListDialog.test.tsx
  frontends/infinite-corridor/src/infinite-pages/resource-lists/AddToListDialog.tsx
  frontends/infinite-corridor/src/infinite-pages/resource-lists/EditListMenu.tsx
  frontends/infinite-corridor/src/infinite-pages/resource-lists/FavoritesPage.test.tsx
  frontends/infinite-corridor/src/infinite-pages/resource-lists/FavoritesPage.tsx
  frontends/infinite-corridor/src/infinite-pages/resource-lists/ItemsListing.test.tsx
  frontends/infinite-corridor/src/infinite-pages/resource-lists/ItemsListing.tsx
  frontends/infinite-corridor/src/infinite-pages/resource-lists/ManageListDialogs.test.tsx
  frontends/infinite-corridor/src/infinite-pages/resource-lists/ManageListDialogs.tsx
  frontends/infinite-corridor/src/infinite-pages/resource-lists/ResourceListDetailsPage.test.tsx
  frontends/infinite-corridor/src/infinite-pages/resource-lists/ResourceListDetailsPage.tsx
  frontends/infinite-corridor/src/infinite-pages/resource-lists/ResourceListsListingsPage.test.tsx
  frontends/infinite-corridor/src/infinite-pages/resource-lists/ResourceListsListingsPage.tsx
  frontends/infinite-corridor/src/infinite-pages/routes.ts
  frontends/infinite-corridor/src/infinite-pages/urls.ts
  frontends/infinite-corridor/src/pages/Home.tsx
  frontends/infinite-corridor/src/pages/errors/ErrorPageRedirect.tsx
  frontends/infinite-corridor/src/pages/errors/ForbiddenPage.test.tsx
  frontends/infinite-corridor/src/pages/errors/ForbiddenPage.tsx
  frontends/infinite-corridor/src/pages/errors/NotFoundPage.test.tsx
  frontends/infinite-corridor/src/pages/errors/NotFoundPage.tsx
  frontends/infinite-corridor/src/pages/routes.ts
  frontends/infinite-corridor/src/pages/urls.ts
  frontends/infinite-corridor/src/test-utils/index.tsx
  package.json
  yarn.lock
Labels: Waiting on author

#31 Remove legacy authentication mechanisms
  README.md
  app.json
  authentication/api.py
  authentication/api_test.py
  authentication/backends/base_jwt.py
  authentication/backends/base_jwt_test.py
  authentication/backends/micromasters.py
  authentication/backends/micromasters_test.py
  authentication/exceptions.py
  authentication/middleware_test.py
  authentication/pipeline/invite.py
  authentication/pipeline/invite_test.py
  authentication/pipeline/user.py
  authentication/pipeline/user_test.py
  authentication/serializers.py
  authentication/serializers_test.py
  authentication/strategy.py
  authentication/strategy_test.py
  authentication/templates/confirmation_sent.html
  authentication/templates/login.html
  authentication/templates/profile.html
  authentication/templates/register.html
  authentication/urls.py
  authentication/utils.py
  authentication/utils_test.py
  authentication/views.py
  authentication/views_test.py
  channels/serializers/posts.py
  mail/templates/password_reset/body.html
  mail/templates/password_reset/subject.txt
  mail/templates/verification/body.html
  mail/templates/verification/subject.txt
  mail/verification_api.py
  mail/verification_api_test.py
  mail/views.py
  open_discussions/factories.py
  open_discussions/features.py
  open_discussions/settings.py
  open_discussions/settings_test.py
  open_discussions/urls.py
  open_discussions/views.py
  open_discussions/views_test.py
  poetry.lock
  profiles/filters_test.py
  profiles/serializers.py
  profiles/serializers_test.py
  profiles/views_test.py
  pyproject.toml
  search/serializers.py
  search/serializers_test.py
Labels: Needs Review

#37 Very minimal homepage
  .github/workflows/ci.yml
  frontends/api/jest.config.ts
  frontends/api/package.json
  frontends/api/src/axios.ts
  frontends/api/src/clients.ts
  frontends/api/src/generated/api.ts
  frontends/api/src/hooks/learningResources.test.ts
  frontends/api/src/hooks/learningResources.ts
  frontends/api/src/hooks/test-utils.tsx
  frontends/api/src/test-utils/factories/index.ts
  frontends/api/src/test-utils/factories/learningResources.ts
  frontends/api/src/test-utils/index.ts
  frontends/api/src/test-utils/mockAxios.ts
  frontends/api/src/test-utils/setupJest.ts
  frontends/api/src/test-utils/urls.ts
  frontends/infinite-corridor/src/pages/Home.test.tsx
  frontends/infinite-corridor/src/pages/Home.tsx
  frontends/infinite-corridor/src/test-utils/mockAxios.ts
  frontends/infinite-corridor/src/test-utils/setupJest.ts
  frontends/ol-util/src/factories.ts
  jest-shared-setup.ts
  scripts/generate_openapi.sh
  yarn.lock
Labels: Waiting on author

#35 21: add keycloak authentication
  app.json
  authentication/backends/ol_open_id_connect.py
  open_discussions/settings.py
  poetry.lock
  pyproject.toml
Labels: Waiting on author

#50 fix pylint
  .github/workflows/ci.yml
  authentication/backends/ol_open_id_connect.py
  learning_resources/etl/constants.py
  learning_resources/etl/deduplication.py
  learning_resources/etl/deduplication_test.py
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/etl/pipelines.py
  learning_resources/etl/pipelines_test.py
  learning_resources/etl/utils.py
  learning_resources/etl/xpro.py
  learning_resources/etl/xpro_test.py
  learning_resources/management/commands/backpopulate_xpro_data.py
  notifications/notifiers/email.py
  poetry.lock
  pylintrc
  pyproject.toml
Labels: Waiting on author

#43 Refactor OPEN_DISCUSSIONS_ env vars to MITOPEN_
  .env.example
  .github/workflows/ci.yml
  Dockerfile
  Procfile
  README.md
  app.json
  channels/api.py
  channels/api_test.py
  channels/task_helpers.py
  channels/task_helpers_test.py
  channels/tasks.py
  channels/tasks_test.py
  channels/utils.py
  channels/views/frontpage_test.py
  channels/views/posts_test.py
  docker-compose-notebook.yml
  docker-compose.yml
  docs/architecture/email_notification.md
  docs/configuration.md
  fixtures/reddit.py
  fixtures/users.py
  frontends/infinite-corridor/webpack.config.js
  learning_resources/serializers.py
  learning_resources/views.py
  mail/api.py
  mail/api_test.py
  mail/views.py
  notifications/notifiers/frontpage.py
  open_discussions/auth_utils.py
  open_discussions/features.py
  open_discussions/features_test.py
  open_discussions/settings.py
  open_discussions/settings_test.py
  pytest.ini
  search/api.py
  search/api_test.py
Labels: DevOps, Waiting on author

#53 Faster yarn commands (linting, formatting)
  package.json
  scripts/yarn-run-with-fallback.js
  yarn.lock
Labels: Needs Review

#60 annotate /new, /upcoming as lists
  .gitattributes
  frontends/api/src/generated/api.ts
  learning_resources/views.py
  openapi.yaml
Labels: Waiting on author

#34 Add LearningPath (StaffList) model and API, refactor relationships between resources-
  .secrets.baseline
  README.md
  frontends/api/src/generated/api.ts
  frontends/api/src/test-utils/factories/learningResources.ts
  learning_resources/admin.py
  learning_resources/constants.py
  learning_resources/etl/constants.py
  learning_resources/etl/deduplication_test.py
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/etl/pipelines.py
  learning_resources/etl/utils.py
  learning_resources/etl/xpro.py
  learning_resources/etl/xpro_test.py
  learning_resources/factories.py
  learning_resources/migrations/0001_initial.py
  learning_resources/migrations/0006_relations_and_learning_paths.py
  learning_resources/migrations/0007_add_editors_group.py
  learning_resources/migrations/0008_alter_relationship_relation_type.py
  learning_resources/models.py
  learning_resources/permissions.py
  learning_resources/permissions_test.py
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  learning_resources/tasks.py
  learning_resources/urls.py
  learning_resources/utils.py
  learning_resources/views.py
  learning_resources/views_learningpath_test.py
  learning_resources/views_test.py
  openapi.yaml
Labels: Needs Review
