Repository mitodl/mit-learn, pull requests merged in 2023-11, with the labels that each got.

#176 fix watch container default NODE_ENV
  docker-compose.yml
Labels: Needs Review

#173 Refactor course numbers
  frontends/api/src/generated/api.ts
  frontends/api/src/test-utils/factories/learningResources.ts
  learning_resources/etl/constants.py
  learning_resources/etl/loaders_test.py
  learning_resources/etl/mitxonline.py
  learning_resources/etl/mitxonline_test.py
  learning_resources/etl/ocw.py
  learning_resources/etl/ocw_test.py
  learning_resources/etl/openedx.py
  learning_resources/etl/openedx_test.py
  learning_resources/etl/pipelines_test.py
  learning_resources/etl/prolearn.py
  learning_resources/etl/prolearn_test.py
  learning_resources/etl/utils.py
  learning_resources/etl/xpro.py
  learning_resources/etl/xpro_test.py
  learning_resources/factories.py
  learning_resources/migrations/0023_course_course_numbers.py
  learning_resources/migrations/0024_remove_course_extra_course_numbers.py
  learning_resources/models.py
  learning_resources/models_test.py
  learning_resources/serializers_test.py
  learning_resources_search/api.py
  learning_resources_search/api_test.py
  learning_resources_search/constants.py
  learning_resources_search/management/commands/update_index.py
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
  learning_resources_search/tasks.py
  learning_resources_search/tasks_test.py
  openapi.yaml
Labels: Needs Review

#190 Removed call to manage.py createcachetables in the release process.
  scripts/heroku-release-phase.sh
  scripts/run-django-dev.sh
Labels: DevOps, bug

#182 Env var warnings and readme for ETL tasks/commands
  README.md
  learning_resources/etl/micromasters.py
  learning_resources/etl/mit_edx.py
  learning_resources/etl/mitxonline.py
  learning_resources/etl/oll.py
  learning_resources/etl/prolearn.py
  learning_resources/etl/xpro.py
  learning_resources/management/commands/backpopulate_micromasters_data.py
  learning_resources/management/commands/backpopulate_mit_edx_data.py
  learning_resources/management/commands/backpopulate_mitxonline_data.py
  learning_resources/management/commands/backpopulate_ocw_data.py
  learning_resources/management/commands/backpopulate_oll_data.py
  learning_resources/management/commands/backpopulate_prolearn_data.py
  learning_resources/management/commands/backpopulate_xpro_data.py
  learning_resources/tasks.py
Labels: Waiting on author

#174 content file search
  frontends/api/src/generated/api.ts
  learning_resources/constants.py
  learning_resources/etl/constants.py
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  learning_resources_search/api.py
  learning_resources_search/api_test.py
  learning_resources_search/connection.py
  learning_resources_search/constants.py
  learning_resources_search/indexing_api.py
  learning_resources_search/indexing_api_test.py
  learning_resources_search/management/commands/recreate_index.py
  learning_resources_search/management/commands/update_index.py
  learning_resources_search/search_index_helpers.py
  learning_resources_search/search_index_helpers_test.py
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
  learning_resources_search/tasks.py
  learning_resources_search/tasks_test.py
  learning_resources_search/urls.py
  learning_resources_search/views.py
  learning_resources_search/views_test.py
  openapi.yaml
Labels: Waiting on author

#194 130: Add custom logout and redirect to keycloak
  .env.example
  README.md
  app.json
  authentication/urls.py
  authentication/views.py
  open_discussions/settings.py
Labels: Waiting on author

#211 Remove double formatting checks, switch to Ruff for python formatting
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  authentication/middleware.py
  authentication/pipeline/user.py
  authentication/views.py
  channels_fields/factories.py
  channels_fields/serializers_test.py
  channels_fields/signals.py
  channels_fields/views_test.py
  course_catalog/migrations/0084_department_array.py
  course_catalog/serializers.py
  discussions/constants.py
  discussions/factories.py
  fixtures/aws.py
  frontends/mit-open/src/scss/header.scss
  jest-shared-setup.ts
  learning_resources/etl/conftest.py
  learning_resources/etl/exceptions.py
  learning_resources/etl/mitxonline.py
  learning_resources/etl/openedx.py
  learning_resources/etl/pipelines.py
  learning_resources/etl/utils.py
  learning_resources/etl/utils_test.py
  learning_resources/exceptions.py
  learning_resources/factories.py
  learning_resources/views_learningpath_test.py
  learning_resources/views_userlist_test.py
  learning_resources_search/exceptions.py
  learning_resources_search/views.py
  livestream/views.py
  mail/api_test.py
  mail/templates/email_base.html
  open_discussions/settings.py
  open_discussions/settings_celery.py
  open_discussions/templates/index.html
  open_discussions/views.py
  package.json
  poetry.lock
  profiles/models.py
  profiles/permissions.py
  profiles/serializers.py
  profiles/utils_test.py
  profiles/views.py
  profiles/views_test.py
  pyproject.toml
  search/api_test.py
  search/exceptions.py
  search/indexing_api.py
  search/indexing_api_test.py
  search/serializers.py
  search/serializers_test.py
  search/tasks_test.py
  test_html/test_csail_listings.html
  test_html/test_see_listings.html
  widgets/serializers/utils.py
  widgets/serializers/widget_instance.py
  widgets/serializers/widget_list.py
  yarn.lock
Labels: Needs Review

#159 Create favorites list for new users
  app.json
  authentication/apps.py
  authentication/hooks.py
  authentication/pipeline/user.py
  authentication/pipeline/user_test.py
  fixtures/common.py
  learning_resources/admin.py
  learning_resources/constants.py
  learning_resources/management/commands/backpopulate_favorites_lists.py
  learning_resources/plugins.py
  learning_resources/plugins_test.py
  learning_resources/utils.py
  open_discussions/settings.py
  open_discussions/settings_pluggy.py
  poetry.lock
  pyproject.toml
Labels: Waiting on author

#196 Use new LearningPath model for Fields
  .devcontainer/web/devcontainer.json
  channels_fields/factories.py
  channels_fields/migrations/0009_alter_fieldchannel_featured_list_and_more.py
  channels_fields/models.py
  channels_fields/serializers.py
  channels_fields/serializers_test.py
  channels_fields/urls.py
  channels_fields/views.py
  channels_fields/views_test.py
  frontends/README.md
  frontends/api/src/generated/api.ts
  frontends/api/src/generated/base.ts
  frontends/api/src/generated/common.ts
  frontends/api/src/generated/configuration.ts
  frontends/api/src/generated/index.ts
  learning_resources/views.py
  learning_resources/views_test.py
  open_discussions/features.py
  open_discussions/settings.py
  open_discussions/settings_spectacular.py
  open_discussions/urls_spectacular.py
  openapi.yaml
Labels: Waiting on author

#216 remove sql file logging
  open_discussions/settings.py
Labels: Waiting on author

#214 Fix bad course department numbers
  learning_resources/etl/utils.py
  learning_resources/etl/utils_test.py
  learning_resources/management/commands/update_course_number_departments.py
  learning_resources/migrations/0025_update_course_number_depts.py
Labels: Needs Review

#197 Sort by coursenums, filtering by department if applicable
  frontends/api/src/generated/api.ts
  learning_resources_search/api.py
  learning_resources_search/api_test.py
  learning_resources_search/constants.py
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
  openapi.yaml
Labels: Waiting on author

#201 new content file search filters
  frontends/api/src/generated/api.ts
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  learning_resources_search/api.py
  learning_resources_search/constants.py
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
  learning_resources_search/views.py
  learning_resources_search/views_test.py
  openapi.yaml
Labels: Waiting on author

#172 Use pluggy to trigger search index updates
  app.json
  learning_resources/apps.py
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/etl/pipelines_test.py
  learning_resources/hooks.py
  learning_resources/management/commands/backpopulate_micromasters_data.py
  learning_resources/management/commands/backpopulate_mit_edx_data.py
  learning_resources/management/commands/backpopulate_mitxonline_data.py
  learning_resources/management/commands/backpopulate_ocw_data.py
  learning_resources/management/commands/backpopulate_oll_data.py
  learning_resources/management/commands/backpopulate_podcast_data.py
  learning_resources/management/commands/backpopulate_prolearn_data.py
  learning_resources/management/commands/backpopulate_xpro_data.py
  learning_resources/tasks_test.py
  learning_resources/utils.py
  learning_resources/views.py
  learning_resources/views_test.py
  learning_resources_search/plugins.py
  learning_resources_search/plugins_test.py
  learning_resources_search/search_index_helpers.py
  learning_resources_search/tasks.py
  open_discussions/settings_pluggy.py
Labels: Needs Review

#224 do not index any pages, for now
  open_discussions/templatetags/noindex_meta.py
Labels: Waiting on author

#221 Change default ordering parameter to "sortby", add options documentation to learning_resources endpoint
  frontends/api/src/generated/api.ts
  frontends/api/src/test-utils/factories/learningResources.ts
  learning_resources/constants.py
  learning_resources/etl/mitxonline_test.py
  learning_resources/etl/ocw_test.py
  learning_resources/etl/openedx_test.py
  learning_resources/etl/utils.py
  learning_resources/etl/xpro_test.py
  learning_resources/factories.py
  learning_resources/filters.py
  learning_resources/filters_test.py
  learning_resources/models.py
  learning_resources/serializers.py
  learning_resources/views.py
  learning_resources/views_test.py
  learning_resources_search/api.py
  learning_resources_search/constants.py
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
  open_discussions/settings.py
  openapi.yaml
Labels: Needs Review

#218 podcast search
  frontends/api/src/generated/api.ts
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources_search/api_test.py
  learning_resources_search/connection_test.py
  learning_resources_search/constants.py
  learning_resources_search/indexing_api.py
  learning_resources_search/indexing_api_test.py
  learning_resources_search/plugins.py
  learning_resources_search/plugins_test.py
  learning_resources_search/search_index_helpers.py
  learning_resources_search/search_index_helpers_test.py
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
  learning_resources_search/tasks.py
  learning_resources_search/tasks_test.py
  openapi.yaml
Labels: Waiting on author

#240 Refactor platform/offered_by filtering and serialization for search
  frontends/api/src/generated/api.ts
  frontends/api/src/test-utils/factories/learningResources.ts
  frontends/ol-learning-resources/src/components/LearningResourceCardTemplate.tsx
  learning_resources/conftest.py
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/etl/pipelines_test.py
  learning_resources/etl/prolearn.py
  learning_resources/etl/prolearn_test.py
  learning_resources/factories.py
  learning_resources/filters.py
  learning_resources/fixtures/platforms.json
  learning_resources/migrations/0026_rename_platform_code.py
  learning_resources/migrations/0027_unique_offeror_code.py
  learning_resources/models.py
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  learning_resources/tasks_test.py
  learning_resources/views.py
  learning_resources_search/api_test.py
  learning_resources_search/constants.py
  learning_resources_search/serializers.py
  openapi.yaml
Labels: Waiting on author

#244 Normalize learning resource serializers
  .github/workflows/ci.yml
  Dockerfile-node
  channels/factories.py
  course_catalog/factories.py
  docker-compose.yml
  frontends/api/src/generated/api.ts
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/test-utils/factories/learningResources.ts
  frontends/mit-open/src/pages/learningpaths/AddToListDialog.test.tsx
  frontends/mit-open/src/pages/learningpaths/LearningPathDetails.test.ts
  frontends/ol-learning-resources/src/components/LearningResourceCardTemplate.test.tsx
  frontends/ol-learning-resources/src/components/LearningResourceCardTemplate.tsx
  frontends/ol-util/src/factories.ts
  learning_resources/apps.py
  learning_resources/constants.py
  learning_resources/etl/loaders_test.py
  learning_resources/factories.py
  learning_resources/models_test.py
  learning_resources/schema.py
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  learning_resources/views.py
  learning_resources/views_learningpath_test.py
  learning_resources/views_test.py
  learning_resources_search/plugins_test.py
  manage.py
  open_discussions/factories.py
  open_discussions/test_utils.py
  openapi.yaml
  package.json
  poetry.lock
  pyproject.toml
  scripts/generate_openapi.sh
  scripts/openapi-configs/typescript-axios.yaml
  yarn.lock
Labels: Waiting on author

#254 Fixed a test that serializer rework made flaky
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
Labels: Waiting on author

#222 Add an article creation page
  frontends/api/src/hooks/articles/index.ts
  frontends/api/src/hooks/articles/keyFactory.ts
  frontends/mit-open/src/pages/articles/ArticleEditPage.test.tsx
  frontends/mit-open/src/pages/articles/ArticleUpsertPages.test.tsx
  frontends/mit-open/src/pages/articles/ArticleUpsertPages.tsx
  frontends/mit-open/src/pages/routes.ts
  frontends/mit-open/src/pages/urls.ts
  frontends/ol-ckeditor/src/test_utils.tsx
Labels: Waiting on author
