Repository mitodl/mit-learn, pull requests merged in 2024-11, with the labels that each got.

#1788 Fix DST issue
  news_events/etl/mitpe_events.py
  news_events/etl/mitpe_events_test.py
  test_json/mitpe_events.json
Labels: Needs Review

#1783 Maintain API instructor order
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/migrations/0072_alter_learningresourceinstructor_relationship.py
  learning_resources/migrations/0073_learningresourceinstructor_through.py
  learning_resources/migrations/0074_remove_learningresourcerun_instructors.py
  learning_resources/migrations/0075_learningresourcerun_instructors.py
  learning_resources/models.py
Labels: Needs Review

#1792 upgrade stories & events grid to grid2
  frontends/main/src/app-pages/HomePage/NewsEventsSection.tsx
  frontends/ol-components/src/index.ts
Labels: Needs Review

#1793 Card bug fixes
  frontends/main/src/app-pages/HomePage/NewsEventsSection.tsx
  frontends/main/src/app-pages/UnitsListingPage/UnitCard.tsx
  frontends/main/src/app-pages/UnitsListingPage/UnitsListingPage.test.tsx
  frontends/main/src/app-pages/UnitsListingPage/UnitsListingPage.tsx
  frontends/main/src/page-components/UserListCard/UserListCardCondensed.test.tsx
  frontends/main/src/page-components/UserListCard/UserListCardCondensed.tsx
  frontends/ol-components/src/components/Card/Card.stories.tsx
  frontends/ol-components/src/components/Card/Card.test.tsx
  frontends/ol-components/src/components/Card/Card.tsx
  frontends/ol-components/src/components/Card/ListCard.test.tsx
  frontends/ol-components/src/components/Card/ListCard.tsx
  frontends/ol-components/src/components/Card/ListCardCondensed.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCardCondensed.tsx
Labels: Needs Review

#1797 calculate min_score before score adjustments
  learning_resources_search/api.py
  learning_resources_search/api_test.py
Labels: Waiting on author

#1801 Remove unnecessary percolate calls
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
Labels: Needs Review

#1802 Add playlist id to video results
  frontends/api/src/generated/v1/api.ts
  learning_resources/serializers.py
  learning_resources/views_test.py
  openapi/specs/v1.yaml
Labels: Needs Review

#1806 remove sentence transformers dependency
  poetry.lock
  pyproject.toml
Labels: Needs Review

#1782 learning resource drawer v2 run comparison table
  frontends/ol-components/src/components/LearningResourceCard/testUtils.ts
  frontends/ol-components/src/components/LearningResourceExpanded/DifferingRunsTable.test.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/DifferingRunsTable.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSectionV2.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpandedV2.tsx
  frontends/ol-utilities/src/learning-resources/pricing.ts
Labels: Needs Review

#1780 Clear resource_type filter when leaving Learning Materials search tab
  frontends/main/src/app-pages/SearchPage/SearchPage.test.tsx
  frontends/main/src/page-components/SearchDisplay/ResourceCategoryTabs.tsx
Labels: Needs Review

#1808 Endpoints for userlist/learningpath memberships
  frontends/api/src/generated/v1/api.ts
  learning_resources/permissions.py
  learning_resources/urls.py
  learning_resources/views.py
  learning_resources/views_learningpath_test.py
  learning_resources/views_userlist_test.py
  openapi/specs/v1.yaml
Labels: Needs Review

#1821 Add data-ph- elements to CTA buttons
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpandedV1.test.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpandedV1.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpandedV2.test.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpandedV2.tsx
Labels: product:mit-open, Waiting on author

#1809 show more button for v2 drawer dates
  frontends/ol-components/src/components/LearningResourceCard/testUtils.ts
  frontends/ol-components/src/components/LearningResourceExpanded/DifferingRunsTable.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSectionV2.test.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSectionV2.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpandedV2.tsx
  frontends/ol-utilities/src/learning-resources/learning-resources.test.ts
  frontends/ol-utilities/src/learning-resources/learning-resources.ts
Labels: Needs Review

#1798 Mechanism to sync server prefetch with client API calls
  frontends/api/package.json
  frontends/api/src/hooks/channels/index.ts
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/hooks/newsEvents/index.ts
  frontends/api/src/hooks/testimonials/index.ts
  frontends/api/src/hooks/widget_lists/index.ts
  frontends/api/src/ssr/prefetch.ts
  frontends/api/src/ssr/usePrefetchWarnings.test.ts
  frontends/api/src/ssr/usePrefetchWarnings.ts
  frontends/main/src/app-pages/HomePage/HomePage.tsx
  frontends/main/src/app/departments/page.tsx
  frontends/main/src/app/page.tsx
  frontends/main/src/app/providers.tsx
Labels: Needs Review

#1823 v2 drawer certification updates
  frontends/api/src/generated/v1/api.ts
  frontends/ol-components/src/components/LearningResourceCard/testUtils.ts
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSectionV2.test.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSectionV2.tsx
  learning_resources/constants.py
  learning_resources/migrations/0076_alter_learningresource_certification_type.py
  openapi/specs/v1.yaml
Labels: Needs Review

#1826 v2 learning resource drawer formats and location
  frontends/ol-components/src/components/LearningResourceCard/testUtils.ts
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSectionV2.test.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSectionV2.tsx
Labels: Needs Review

#1831 LocalDate and NoSSR components to render localized dates only on client
  frontends/main/package.json
  frontends/main/src/app-pages/HomePage/NewsEventsSection.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/DifferingRunsTable.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSectionV2.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpandedV1.tsx
  frontends/ol-utilities/src/date/LocalDate.tsx
  frontends/ol-utilities/src/date/format.ts
  frontends/ol-utilities/src/index.ts
  frontends/ol-utilities/src/ssr/NoSSR.tsx
Labels: Needs Review

#1827 vector search endpoint
  frontends/api/src/generated/v0/api.ts
  learning_resources_search/api.py
  learning_resources_search/serializers.py
  learning_resources_search/urls.py
  learning_resources_search/views.py
  learning_resources_search/views_test.py
  openapi/specs/v0.yaml
Labels: Needs Review

#1822 Server rendering for homepage, units and topics listing pages
  frontends/api/src/hooks/channels/index.ts
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/hooks/learningResources/keyFactory.ts
  frontends/api/src/hooks/newsEvents/index.ts
  frontends/api/src/hooks/testimonials/index.ts
  frontends/api/src/ssr/prefetch.ts
  frontends/api/src/ssr/usePrefetchWarnings.test.ts
  frontends/api/src/ssr/usePrefetchWarnings.ts
  frontends/api/src/test-utils/factories/channels.ts
  frontends/api/src/test-utils/urls.ts
  frontends/main/src/app-pages/UnitsListingPage/UnitCard.tsx
  frontends/main/src/app-pages/UnitsListingPage/UnitsListingPage.test.tsx
  frontends/main/src/app-pages/UnitsListingPage/UnitsListingPage.tsx
  frontends/main/src/app/about/page.tsx
  frontends/main/src/app/c/[channelType]/[name]/page.tsx
  frontends/main/src/app/dashboard/[tab]/[id]/page.tsx
  frontends/main/src/app/departments/page.tsx
  frontends/main/src/app/learningpaths/[id]/page.tsx
  frontends/main/src/app/learningpaths/page.tsx
  frontends/main/src/app/onboarding/page.tsx
  frontends/main/src/app/page.tsx
  frontends/main/src/app/privacy/page.tsx
  frontends/main/src/app/search/page.tsx
  frontends/main/src/app/terms/page.tsx
  frontends/main/src/app/topics/page.tsx
  frontends/main/src/app/types.d.ts
  frontends/main/src/app/units/page.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawer.tsx
  frontends/main/src/page-components/ResourceCarousel/ResourceCarousel.tsx
Labels: Needs Review

#1842 Refactor user lists and learning paths hooks out of learning resources
  frontends/api/src/clients.ts
  frontends/api/src/hooks/learningPaths/index.test.ts
  frontends/api/src/hooks/learningPaths/index.ts
  frontends/api/src/hooks/learningPaths/keyFactory.ts
  frontends/api/src/hooks/learningResources/index.test.ts
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/hooks/learningResources/invalidation.ts
  frontends/api/src/hooks/learningResources/keyFactory.ts
  frontends/api/src/hooks/programLetters/index.ts
  frontends/api/src/hooks/searchSubscription/keyFactory.ts
  frontends/api/src/hooks/userLists/index.ts
  frontends/api/src/hooks/userLists/invalidation.ts
  frontends/api/src/hooks/userLists/keyFactory.ts
  frontends/main/src/app-pages/DashboardPage/UserListDetailsTab.tsx
  frontends/main/src/app-pages/LearningPathDetailsPage/LearningPathDetailsPage.tsx
  frontends/main/src/app-pages/LearningPathListingPage/LearningPathListingPage.tsx
  frontends/main/src/page-components/Dialogs/AddToListDialog.tsx
  frontends/main/src/page-components/ItemsListing/ItemsListing.tsx
  frontends/main/src/page-components/ManageListDialogs/ManageListDialogs.tsx
  frontends/main/src/page-components/UserListListing/UserListListing.tsx
Labels: Needs Review

#1835 similar resources carousel
  frontends/api/src/generated/v1/api.ts
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/hooks/learningResources/keyFactory.ts
  frontends/api/src/test-utils/urls.ts
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV2.test.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV2.tsx
  frontends/main/src/page-components/ResourceCarousel/ResourceCarousel.tsx
  frontends/main/src/page-components/ResourceCarousel/types.ts
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpandedV2.tsx
  learning_resources/views.py
  openapi/specs/v1.yaml
Labels: Needs Review

#1845 set min cpu and memory. also add qdrant container
  .devcontainer/devcontainer.json
Labels: Waiting on author

#1839 Consistent qdrant point ids
  learning_resources_search/api.py
  learning_resources_search/indexing_api.py
  learning_resources_search/indexing_api_test.py
  main/settings.py
Labels: Needs Review

#1846 Query membership endpoints for resources belonging to user lists and learning paths
  frontends/api/src/hooks/learningPaths/index.test.ts
  frontends/api/src/hooks/learningPaths/index.ts
  frontends/api/src/hooks/learningPaths/keyFactory.ts
  frontends/api/src/hooks/learningResources/index.test.ts
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/hooks/learningResources/invalidation.ts
  frontends/api/src/hooks/learningResources/keyFactory.ts
  frontends/api/src/hooks/user/index.ts
  frontends/api/src/hooks/userLists/index.ts
  frontends/api/src/hooks/userLists/invalidation.ts
  frontends/api/src/hooks/userLists/keyFactory.ts
  frontends/api/src/test-utils/factories/learningResources.ts
  frontends/api/src/test-utils/factories/userLists.ts
  frontends/api/src/test-utils/urls.ts
  frontends/main/src/app-pages/ChannelPage/ChannelSearch.test.tsx
  frontends/main/src/app-pages/DashboardPage/Dashboard.test.tsx
  frontends/main/src/app-pages/HomePage/HomePage.test.tsx
  frontends/main/src/app-pages/LearningPathDetailsPage/ListDetailsPage.tsx
  frontends/main/src/app-pages/SearchPage/SearchPage.test.tsx
  frontends/main/src/page-components/Dialogs/AddToListDialog.test.tsx
  frontends/main/src/page-components/Dialogs/AddToListDialog.tsx
  frontends/main/src/page-components/ItemsListing/ItemsListing.test.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV1.test.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV1.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV2.test.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV2.tsx
  frontends/main/src/page-components/ResourceCard/ResourceCard.test.tsx
  frontends/main/src/page-components/ResourceCard/ResourceCard.tsx
  frontends/main/src/page-components/ResourceCarousel/ResourceCarousel.test.tsx
  frontends/ol-components/src/components/Checkbox/Checkbox.stories.tsx
  frontends/ol-components/src/components/Checkbox/Checkbox.tsx
  frontends/ol-components/src/components/Checkbox/CheckboxChoiceField.stories.tsx
  frontends/ol-components/src/components/Checkbox/CheckboxChoiceField.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSectionV1.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpandedV1.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpandedV2.tsx
Labels: Needs Review

#1847 Server rendering for homepage, units and topics listing pages
  frontends/api/src/hooks/channels/index.ts
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/hooks/newsEvents/index.ts
  frontends/api/src/hooks/testimonials/index.ts
  frontends/api/src/ssr/prefetch.ts
  frontends/api/src/ssr/usePrefetchWarnings.test.ts
  frontends/api/src/test-utils/factories/channels.ts
  frontends/api/src/test-utils/urls.ts
  frontends/main/src/app-pages/UnitsListingPage/UnitCard.tsx
  frontends/main/src/app-pages/UnitsListingPage/UnitsListingPage.test.tsx
  frontends/main/src/app-pages/UnitsListingPage/UnitsListingPage.tsx
  frontends/main/src/app/about/page.tsx
  frontends/main/src/app/c/[channelType]/[name]/page.tsx
  frontends/main/src/app/dashboard/[tab]/[id]/page.tsx
  frontends/main/src/app/departments/page.tsx
  frontends/main/src/app/learningpaths/[id]/page.tsx
  frontends/main/src/app/learningpaths/page.tsx
  frontends/main/src/app/onboarding/page.tsx
  frontends/main/src/app/page.tsx
  frontends/main/src/app/privacy/page.tsx
  frontends/main/src/app/search/page.tsx
  frontends/main/src/app/terms/page.tsx
  frontends/main/src/app/topics/page.tsx
  frontends/main/src/app/types.d.ts
  frontends/main/src/app/units/page.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawer.tsx
  frontends/main/src/page-components/ResourceCarousel/ResourceCarousel.tsx
Labels: Needs Review

#1840 Refactor date/time parsing for mitpe events
  news_events/etl/mitpe_events.py
  news_events/etl/mitpe_events_test.py
  news_events/etl/utils.py
  news_events/etl/utils_test.py
Labels: Needs Review

#1849 returning all resource types for similar resources endpoint
  learning_resources_search/api.py
Labels: Waiting on author

#1863 Filter out content type on similar resources endpoint
  learning_resources/views_test.py
  learning_resources_search/api.py
Labels: Waiting on author
