Repository mitodl/mit-learn, pull requests merged in 2024-08, with the labels that each got.

#1347 Use resource_delete_actions instead of resource.delete directly
  learning_resources/etl/loaders.py
Labels: Needs Review

#1344 Update the mappings for PWT topic "Programming & Coding"
  data_fixtures/migrations/0006_topic_mappings_edx_add_programming_coding_to_computer_science.py
Labels: product:mit-open, Waiting on author

#1353 Renaming my topic update migration from 0006 to 0007
  data_fixtures/migrations/0007_topic_mappings_edx_add_programming_coding_to_computer_science.py
Labels: Needs Review, product:mit-open

#1307 Add certificate badge to drawer
  frontends/ol-components/src/components/Card/ListCardCondensed.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.stories.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.stories.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCardCondensed.stories.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCardCondensed.tsx
  frontends/ol-components/src/components/LearningResourceCard/testUtils.ts
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSection.test.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSection.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.stories.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.tsx
  frontends/ol-utilities/jest.config.ts
  frontends/ol-utilities/src/index.ts
  frontends/ol-utilities/src/learning-resources/pricing.test.ts
  frontends/ol-utilities/src/learning-resources/pricing.ts
Labels: Waiting on author

#1331 Subscription management page
  frontends/api/src/generated/v1/api.ts
  frontends/api/src/test-utils/factories/percolateQueries.ts
  frontends/mit-open/src/common/utils.test.ts
  frontends/mit-open/src/common/utils.ts
  frontends/mit-open/src/pages/DashboardPage/Dashboard.test.tsx
  frontends/mit-open/src/pages/DashboardPage/DashboardPage.tsx
  frontends/mit-open/src/pages/DashboardPage/SettingsPage.test.tsx
  frontends/mit-open/src/pages/DashboardPage/SettingsPage.tsx
  learning_resources_search/models.py
  learning_resources_search/models_test.py
  learning_resources_search/serializers.py
  openapi/specs/v1.yaml
Labels: Needs Review

#1303 Address performance of learning resource APIs
  channels/migrations/0014_dept_detail_related_name.py
  channels/models.py
  frontends/api/src/generated/v1/api.ts
  learning_resources/models.py
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  learning_resources/views.py
  learning_resources/views_test.py
  learning_resources_search/indexing_api.py
  learning_resources_search/indexing_api_test.py
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
  openapi/specs/v1.yaml
  poetry.lock
  pyproject.toml
Labels: Waiting on author

#1311 Subscription email template updates
  frontends/mit-open/public/images/mit-logo-transparent5.jpg
  frontends/mit-open/public/images/mit-logo-transparent5.png
  learning_resources_search/models.py
  learning_resources_search/tasks.py
  learning_resources_search/tasks_test.py
  main/templates/email/email_base.html
  main/templates/email/subscribed_channel_digest.html
  profiles/utils.py
Labels: Needs Review

#1348 user list UI updates
  frontends/mit-open/src/common/urls.ts
  frontends/mit-open/src/page-components/Header/UserMenu.tsx
  frontends/mit-open/src/page-components/ItemsListing/ItemsListingComponent.tsx
  frontends/mit-open/src/page-components/UserListCard/UserListCardCondensed.test.tsx
  frontends/mit-open/src/page-components/UserListCard/UserListCardCondensed.tsx
  frontends/mit-open/src/page-components/UserListCardTemplate/UserListCardTemplate.tsx
  frontends/mit-open/src/pages/DashboardPage/Dashboard.test.tsx
  frontends/mit-open/src/pages/DashboardPage/DashboardPage.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.test.tsx
  frontends/mit-open/src/pages/HomePage/PersonalizeSection.tsx
  frontends/mit-open/src/pages/ListDetailsPage/ListDetailsPage.test.ts
  frontends/mit-open/src/pages/ListDetailsPage/ListDetailsPage.tsx
  frontends/mit-open/src/pages/OnboardingPage/OnboardingPage.tsx
  frontends/mit-open/src/pages/UserListListingComponent/UserListListingComponent.test.tsx
  frontends/mit-open/src/pages/UserListListingComponent/UserListListingComponent.tsx
  frontends/mit-open/src/pages/UserListListingPage/UserListListingPage.test.tsx
  frontends/mit-open/src/pages/UserListListingPage/UserListListingPage.tsx
  frontends/mit-open/src/routes.tsx
  frontends/ol-components/src/index.ts
Labels: Waiting on author

#1355 add a bullet about collecting demographics to PrivacyPage.tsx
  frontends/mit-open/src/pages/PrivacyPage/PrivacyPage.tsx
Labels: Needs Review

#1362 Fix frontend sentry configuration
  .github/workflows/production.yml
  .github/workflows/release-candidate.yml
  frontends/mit-open/package.json
  frontends/mit-open/src/App.tsx
  frontends/mit-open/src/types/settings.d.ts
  frontends/mit-open/webpack.config.js
  frontends/ol-utilities/src/types/settings.d.ts
  scripts/get_version.sh
Labels: Needs Review

#1368 Update CI to check data migrations for conflicts
  scripts/test/detect_missing_migrations.sh
Labels: product:mit-open, Waiting on author

#1361 Fix issue with User List cards not updating on edit
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/hooks/learningResources/keyFactory.ts
Labels: Waiting on author

#1349 Publish topic channels based on resource count
  channels/factories.py
  channels/migrations/0015_channel_published.py
  channels/models.py
  channels/models_test.py
  channels/plugins.py
  channels/plugins_test.py
  channels/serializers.py
  channels/views.py
  channels/views_test.py
  data_fixtures/migrations/0008_unpublish_empty_topic_channels.py
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/generated/v1/api.ts
  frontends/mit-open/src/pages/TopicListingPage/TopicsListingPage.tsx
  learning_resources/hooks.py
  learning_resources/serializers.py
  learning_resources/utils.py
  learning_resources/utils_test.py
  learning_resources/views_test.py
  learning_resources_search/plugins.py
  learning_resources_search/plugins_test.py
  openapi/specs/v0.yaml
  openapi/specs/v1.yaml
Labels: Waiting on author

#1364 Add Manufacturing topic; update upserter to make adding child topics easier
  data_fixtures/migrations/0008_topics_update_engineering_add_manufacturing.py
  learning_resources/data/README-topics.md
  learning_resources/utils.py
  learning_resources/utils_test.py
Labels: product:mit-open, Waiting on author

#1374 Rename my 0008 to 0009 to prevent conflict
  data_fixtures/migrations/0009_topics_update_engineering_add_manufacturing.py
Labels: product:mit-open, Waiting on author

#1372 Fix flaky test_serialize_bulk_learning_resources
  learning_resources_search/serializers_test.py
Labels: Waiting on author

#1378 prevent renovate django 5 updates
  renovate.json
Labels: Needs Review

#1380 Update topic boxes to support multiple lines
  data_fixtures/migrations/0010_topics_update_icons_for_innovation_data_science.py
  frontends/mit-open/src/components/RootTopicIcon/RootTopicIcon.test.tsx
  frontends/mit-open/src/components/RootTopicIcon/RootTopicIcon.tsx
  frontends/mit-open/src/pages/HomePage/BrowseTopicsSection.tsx
  frontends/mit-open/src/pages/TopicListingPage/TopicsListingPage.tsx
  learning_resources/admin.py
Labels: Needs Review, product:mit-open

#1370 enable mailgun and analytics
  main/settings.py
  profiles/utils.py
Labels: Needs Review

#1390 Rename MIT Open to MIT Learn for subscription emails
  frontends/mit-open/public/images/mit-logo-learn.jpg
  frontends/mit-open/public/images/mit-logo-transparent5.jpg
  main/templates/email/email_base.html
  main/templates/email/subscribed_channel_digest.html
Labels: Waiting on author

#1391 fix prettier and eslint in pre-commit
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  .prettierignore
  frontends/.eslintrc.js
  frontends/api/src/generated/v0/common.ts
  frontends/api/src/generated/v1/common.ts
  frontends/mit-open/src/page-components/SearchDisplay/ResourceCategoryTabs.tsx
  frontends/ol-components/src/components/Button/Button.mdx
  frontends/ol-components/src/components/Checkbox/CheckboxChoiceField.tsx
  frontends/ol-components/src/components/Chips/Chip.mdx
  frontends/ol-components/src/components/Input/Input.mdx
  frontends/ol-components/src/components/SelectField/SelectField.mdx
  frontends/ol-components/src/components/TabButtons/TabButtonList.mdx
  frontends/ol-components/src/components/TextField/TextField.mdx
  frontends/ol-components/src/components/ThemeProvider/Typography.mdx
  frontends/ol-components/src/components/TruncateText/TruncateText.mdx
  frontends/package.json
  package.json
  yarn.lock
Labels: Needs Review

#1387 Update search term event handler to clear page if the term changes
  frontends/mit-open/src/pages/SearchPage/SearchPage.test.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.tsx
Labels: Needs Review, product:mit-open

#1371 Fix homepage contrast issues
  frontends/mit-open/src/page-components/TestimonialDisplay/AttestantBlock.tsx
  frontends/ol-components/src/components/Input/Input.tsx
Labels: Waiting on author

#1381 show featured resources first minus breaking changes
  channels/migrations/0016_alter_channel_featured_list.py
  channels/models.py
  fixtures/common.py
  frontends/api/src/generated/v1/api.ts
  learning_resources/models.py
  learning_resources/views.py
  learning_resources/views_test.py
  learning_resources_search/api_test.py
  learning_resources_search/constants.py
  learning_resources_search/indexing_api.py
  learning_resources_search/indexing_api_test.py
  learning_resources_search/management/commands/update_featured_rank.py
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
  learning_resources_search/tasks.py
  learning_resources_search/tasks_test.py
  main/settings_celery.py
  openapi/specs/v1.yaml
Labels: Waiting on author

#1401 Update values of hostnames to use learn.mit.edu
  .github/workflows/production.yml
  .github/workflows/release-candidate.yml
  README.md
  e2e_testing/.env
  e2e_testing/README.md
  e2e_testing/package.json
  frontends/api/jest.config.ts
  frontends/mit-open/jest.config.ts
  frontends/ol-ckeditor/jest.config.ts
  frontends/ol-components/src/components/Banner/Banner.stories.tsx
  frontends/ol-utilities/jest.config.ts
  package.json
Labels: Needs Review

#1377 show featured resources first
  learning_resources_search/api.py
  learning_resources_search/api_test.py
Labels: Waiting on author, Blocked

#1404 adding fix for logo in email
  main/templates/email/email_base.html
  profiles/utils.py
Labels: Waiting on author

#1388 Rename env var prefix MITOPEN_ to MITOL_
  .github/workflows/ci.yml
  Procfile
  README.md
  RELEASE.rst
  app.json
  authentication/hooks.py
  docker-compose-notebook.yml
  docker-compose.yml
  env/backend.env
  env/backend.local.example.env
  env/ci.env
  env/frontend.env
  env/shared.env
  env/shared.local.example.env
  fixtures/users.py
  frontends/api/jest.config.ts
  frontends/api/src/axios.ts
  frontends/api/src/clients.ts
  frontends/api/src/test-utils/urls.ts
  frontends/api/src/types/settings.d.ts
  frontends/mit-open/jest.config.ts
  frontends/mit-open/src/common/urls.test.ts
  frontends/mit-open/src/common/urls.ts
  frontends/mit-open/src/pages/PrivacyPage/PrivacyPage.tsx
  frontends/mit-open/webpack.config.js
  frontends/ol-ckeditor/jest.config.ts
  frontends/ol-ckeditor/src/types/settings.d.ts
  frontends/ol-utilities/jest.config.ts
  frontends/ol-utilities/src/types/settings.d.ts
  learning_resources/hooks.py
  main/auth_utils.py
  main/features.py
  main/features_test.py
  main/settings.py
  main/settings_pluggy.py
  main/settings_test.py
  manage.py
  package.json
  pytest.ini
Labels: Needs Review

#1392 cache learning resources search api view
  learning_resources/tasks.py
  learning_resources/tasks_test.py
  learning_resources_search/management/commands/update_index.py
  learning_resources_search/tasks.py
  learning_resources_search/tasks_test.py
  learning_resources_search/views.py
  main/settings.py
  main/utils.py
Labels: Needs Review

#1406 Fix typo in env variable prefix
  manage.py
Labels: Waiting on author

#1409 Rename the variables on release workflows
  .github/workflows/production.yml
  .github/workflows/release-candidate.yml
Labels: Waiting on author

#1412 Make MITOL_ settings optional in app.json
  app.json
Labels: Needs Review

#1395 Add accessibility linting
  frontends/.eslintrc.js
  frontends/mit-learn/src/components/ChannelAvatar/ChannelAvatar.test.tsx
  frontends/mit-learn/src/components/ChannelAvatar/ChannelAvatar.tsx
  frontends/mit-learn/src/page-components/Header/Header.tsx
  frontends/mit-learn/src/page-components/Header/UserMenu.tsx
  frontends/mit-learn/src/page-components/SearchDisplay/SearchInput.tsx
  frontends/mit-learn/src/page-components/TestimonialDisplay/AttestantBlock.tsx
  frontends/mit-learn/src/page-components/TestimonialDisplay/TestimonialDisplay.tsx
  frontends/mit-learn/src/pages/HomePage/PersonalizeSection.tsx
  frontends/mit-learn/src/pages/HomePage/SearchInput.tsx
  frontends/mit-learn/src/pages/HomePage/TestimonialsSection.tsx
  frontends/mit-learn/src/pages/ProgramLetterPage/ProgramLetterPage.tsx
  frontends/ol-components/package.json
  frontends/ol-components/src/components/Alert/Alert.tsx
  frontends/ol-components/src/components/Button/Button.stories.tsx
  frontends/ol-components/src/components/Card/Card.stories.tsx
  frontends/ol-components/src/components/Card/Card.tsx
  frontends/ol-components/src/components/Card/ListCard.tsx
  frontends/ol-components/src/components/Input/Input.stories.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.tsx
  frontends/ol-components/src/components/ShareTooltip/ShareTooltip.stories.tsx
  frontends/ol-components/src/components/ShareTooltip/ShareTooltip.tsx
  frontends/ol-components/src/components/SimpleMenu/SimpleMenu.test.tsx
  frontends/ol-components/src/index.ts
  frontends/ol-widgets/src/components/editing/ManageWidgetDialog.tsx
  frontends/package.json
  yarn.lock
Labels: Needs Review

#1416 Update the ETL pipelines times
  main/settings_celery.py
Labels: Needs Review, product:mit-open

#1418 Expose the SESSION_COOKIE_NAME setting
  main/settings.py
Labels: Needs Review

#1420 set csrf cookie name from env var
  .github/workflows/production.yml
  .github/workflows/release-candidate.yml
  env/shared.env
  frontends/api/jest.config.ts
  frontends/api/src/axios.ts
  frontends/api/src/types/settings.d.ts
  frontends/mit-learn/src/services/axios.ts
  frontends/mit-learn/webpack.config.js
  frontends/ol-utilities/src/types/settings.d.ts
  main/settings.py
Labels: Needs Review

#1411 Per Page metadata tags
  frontends/mit-learn/src/page-components/LearningResourceDrawer/LearningResourceDrawer.tsx
  frontends/mit-learn/src/page-components/MetaTags/MetaTags.test.tsx
  frontends/mit-learn/src/page-components/MetaTags/MetaTags.tsx
  frontends/mit-learn/src/pages/AboutPage/AboutPage.tsx
  frontends/mit-learn/src/pages/ArticleDetailsPage/ArticleDetailsPage.tsx
  frontends/mit-learn/src/pages/ArticleUpsertPages/ArticleUpsertPage.tsx
  frontends/mit-learn/src/pages/ChannelPage/ChannelPage.test.tsx
  frontends/mit-learn/src/pages/ChannelPage/DefaultChannelTemplate.tsx
  frontends/mit-learn/src/pages/ChannelPage/EditChannelPage.tsx
  frontends/mit-learn/src/pages/ChannelPage/UnitChannelTemplate.tsx
  frontends/mit-learn/src/pages/DashboardPage/DashboardPage.tsx
  frontends/mit-learn/src/pages/DepartmentListingPage/DepartmentListingPage.tsx
  frontends/mit-learn/src/pages/ErrorPage/ErrorPage.test.tsx
  frontends/mit-learn/src/pages/ErrorPage/ErrorPageTemplate.tsx
  frontends/mit-learn/src/pages/HomePage/HomePage.tsx
  frontends/mit-learn/src/pages/LearningPathListingPage/LearningPathListingPage.tsx
  frontends/mit-learn/src/pages/ListDetailsPage/ListDetailsPage.tsx
  frontends/mit-learn/src/pages/OnboardingPage/OnboardingPage.tsx
  frontends/mit-learn/src/pages/PrivacyPage/PrivacyPage.tsx
  frontends/mit-learn/src/pages/SearchPage/SearchPage.tsx
  frontends/mit-learn/src/pages/TermsPage/TermsPage.tsx
  frontends/mit-learn/src/pages/TopicListingPage/TopicsListingPage.tsx
  frontends/mit-learn/src/pages/UnitsListingPage/UnitsListingPage.tsx
  frontends/mit-learn/src/test-utils/index.tsx
  frontends/mit-learn/src/test-utils/setupJest.ts
  frontends/ol-utilities/src/components/MetaTags.tsx
  frontends/ol-utilities/src/components/index.ts
Labels: Needs Review

#1415 remove elementary / primary school as an education option
  frontends/api/src/generated/v0/api.ts
  openapi/specs/v0.yaml
  profiles/migrations/0032_alter_profile_current_education.py
  profiles/models.py
Labels: Waiting on author

#1393 search test query fields cleanup
  learning_resources_search/api.py
  learning_resources_search/api_test.py
  learning_resources_search/constants.py
Labels: product:mit-open, Waiting on author

#1428 Fix home page header capitalization
  frontends/mit-learn/src/pages/HomePage/HeroSearch.tsx
Labels: Needs Review

#1408 Add migration to adjust mappings, make some minor changes to the dump to yaml util function
  data_fixtures/migrations/0012_topic_mappings_adjust_sustainable_business_finance_accounting.py
  learning_resources/utils.py
Labels: product:mit-open, Waiting on author

#1379 Replace resource drawer topic chips with info section text
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSection.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.test.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.tsx
Labels: Needs Review

#1422 Add load testing suite
  docker-compose.yml
  env/backend.env
  load_testing/README.md
  load_testing/__init__.py
  load_testing/locustfile.py
  main/settings.py
  poetry.lock
  pyproject.toml
  uwsgi.ini
Labels: Needs Review

#1383 Only process best/next run contentfiles, and make sure other run contentfiles are deindexed
  learning_resources/etl/edx_shared.py
  learning_resources/etl/edx_shared_test.py
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/etl/pipelines_test.py
  learning_resources/etl/utils.py
  learning_resources/hooks.py
  learning_resources/utils.py
  learning_resources/utils_test.py
  learning_resources_search/plugins.py
  learning_resources_search/plugins_test.py
  main/settings_course_etl.py
Labels: Needs Review

#1424 Remove remaining frontend routes
  main/urls.py
  main/urls_test.py
  main/views.py
  main/views_test.py
Labels: product:mit-open, Waiting on author

#1386 Fix frontend sentry_env and release version
  .github/workflows/production.yml
  .github/workflows/release-candidate.yml
  frontends/mit-learn/webpack.config.js
  scripts/get_version.sh
Labels: Needs Review

#1435 add appzi for feedback
  .github/workflows/production.yml
  .github/workflows/release-candidate.yml
  frontends/mit-learn/public/index.html
  frontends/mit-learn/webpack.config.js
Labels: Waiting on author

#1432 Get availability value from xpro api
  learning_resources/etl/xpro.py
  test_json/xpro_courses.json
  test_json/xpro_programs.json
Labels: Waiting on author

#1441 allow empty APPZI_URL
  frontends/mit-learn/webpack.config.js
Labels: Waiting on author

#1440 remove privacy chip from add to user list dialog
  frontends/mit-learn/src/page-components/Dialogs/AddToListDialog.tsx
Labels: Waiting on author

#1442 restrict learning path pages to learning path editors
  frontends/mit-learn/src/pages/ListDetailsPage/ListDetailsPage.test.ts
  frontends/mit-learn/src/routes.tsx
Labels: Waiting on author

#1437 department is optional
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
Labels: Waiting on author

#1439 Remove RES from departments
  data_fixtures/migrations/0013_remove_department_RES.py
  frontends/api/src/generated/v1/api.ts
  learning_resources/constants.py
  learning_resources/fixtures/departments.json
  openapi/specs/v1.yaml
Labels: Waiting on author

#1446 restoring redirect route
  main/urls.py
Labels: Needs Review

#1449 change default og:image
  frontends/mit-learn/public/images/mit-and-logo.jpg
  frontends/mit-learn/src/page-components/MetaTags/MetaTags.tsx
Labels: Needs Review

#1365 News and events for MIT Professional Education
  frontends/api/src/generated/v0/api.ts
  main/settings_celery.py
  main/settings_course_etl.py
  news_events/constants.py
  news_events/etl/loaders.py
  news_events/etl/mitpe_events.py
  news_events/etl/mitpe_events_test.py
  news_events/etl/mitpe_news.py
  news_events/etl/mitpe_news_test.py
  news_events/etl/pipelines.py
  news_events/etl/pipelines_test.py
  news_events/etl/sloan_webinars.py
  news_events/etl/utils.py
  news_events/migrations/0004_feedeventdetail_event_end_datetime.py
  news_events/models.py
  news_events/tasks.py
  news_events/tasks_test.py
  openapi/specs/v0.yaml
  test_json/mitpe_events.json
  test_json/mitpe_news.json
Labels: Needs Review

#1448 adding test for redirect view
  main/views_test.py
Labels: Waiting on author

#1451 Add SP as a department
  data_fixtures/migrations/0014_add_department_SP.py
  frontends/mit-learn/package.json
  learning_resources/fixtures/departments.json
  yarn.lock
Labels: Waiting on author

#1455 S3 bucket renaming
  .github/workflows/production.yml
  .github/workflows/release-candidate.yml
Labels: DevOps, Needs Review, Tech Debt

#1454 homepage hero search updates
  frontends/mit-learn/src/pages/HomePage/HeroSearch.tsx
  frontends/mit-learn/src/pages/HomePage/HomePage.test.tsx
  frontends/mit-learn/src/pages/HomePage/SearchInput.tsx
  frontends/ol-components/src/components/Input/Input.tsx
Labels: Needs Review

#1457 1454 follow-up: fix mobile adornment button width
  frontends/mit-learn/src/pages/HomePage/SearchInput.tsx
Labels: Waiting on author

#1459 randomize the hero image
  frontends/mit-learn/public/images/hero/hero-1.png
  frontends/mit-learn/public/images/hero/hero-2.png
  frontends/mit-learn/public/images/hero/hero-3.png
  frontends/mit-learn/public/images/hero/hero-4.png
  frontends/mit-learn/public/images/hero/hero-5.png
  frontends/mit-learn/public/images/person_with_headphones.png
  frontends/mit-learn/src/pages/HomePage/HeroSearch.tsx
Labels: Waiting on author

#1460 fix certification search url
  frontends/mit-learn/src/common/urls.ts
  frontends/mit-learn/src/page-components/Header/Header.tsx
  frontends/mit-learn/src/pages/HomePage/HeroSearch.tsx
  frontends/mit-learn/src/pages/HomePage/HomePage.test.tsx
Labels: Needs Review

#1444 Setup codespaces
  .devcontainer/devcontainer.json
  README.md
  docker-compose.codespaces.yml
  env/codespaces.env
Labels: Needs Review

#1394 Preliminary ETL pipeline for Sloan
  app.json
  learning_resources/etl/constants.py
  learning_resources/etl/pipelines.py
  learning_resources/etl/pipelines_test.py
  learning_resources/etl/prolearn.py
  learning_resources/etl/prolearn_test.py
  learning_resources/etl/sloan.py
  learning_resources/etl/sloan_test.py
  learning_resources/management/commands/backpopulate_sloan_data.py
  learning_resources/tasks.py
  main/settings_celery.py
  main/settings_course_etl.py
  test_json/test_sloan_courses.json
  test_json/test_sloan_runs.json
Labels: Needs Review

#1456 ability to set search mode
  data_fixtures/migrations/0014_add_department_SP.py
  frontends/api/src/generated/v1/api.ts
  frontends/mit-learn/src/page-components/SearchDisplay/SearchDisplay.tsx
  frontends/mit-learn/src/page-components/SearchDisplay/SliderInput.tsx
  frontends/mit-learn/src/page-components/SearchDisplay/StalenessPenaltySlider.tsx
  frontends/mit-learn/src/pages/SearchPage/SearchPage.test.tsx
  learning_resources_search/api.py
  learning_resources_search/api_test.py
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
  openapi/specs/v1.yaml
Labels: Waiting on author

#1462 Carousel accessibility improvements
  frontends/mit-learn/src/page-components/ResourceCarousel/ResourceCarousel.tsx
  frontends/mit-learn/src/page-components/TestimonialDisplay/AttestantBlock.tsx
  frontends/mit-learn/src/page-components/TestimonialDisplay/TestimonialDisplay.tsx
  frontends/mit-learn/src/pages/HomePage/TestimonialsSection.tsx
  frontends/ol-components/src/components/Carousel/Carousel.test.tsx
  frontends/ol-components/src/components/Carousel/Carousel.tsx
  frontends/ol-components/src/components/Carousel/util.ts
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCardCondensed.tsx
  frontends/ol-components/src/index.ts
Labels: Needs Review

#1464 Update newrelic to latest
  poetry.lock
  pyproject.toml
Labels: Waiting on author

#1472 Add caching for imagekit
  main/cache/__init__.py
  main/cache/backends.py
  main/cache/backends_test.py
  main/settings.py
  scripts/run-django-dev.sh
Labels: Waiting on author

#1467 update the footer logo
  frontends/mit-learn/public/images/mit_logo_std_cmyk_black.svg
  frontends/mit-learn/src/page-components/Footer/Footer.tsx
Labels: Needs Review

#1471 change drawer CTA label
  frontends/ol-components/src/components/Button/Button.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.test.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.tsx
Labels: Waiting on author

#1477 Remove the in-memory cache for imagekit
  main/settings.py
Labels: Waiting on author

#1469 Shanbady/fix multiple instances of subscriptions
  learning_resources_search/management/commands/prune_subscription_queries.py
  learning_resources_search/utils.py
  learning_resources_search/utils_test.py
  scripts/heroku-release-phase.sh
  scripts/run-django-dev.sh
Labels: Waiting on author

#1461 OCW course completeness score
  frontends/api/src/generated/v1/api.ts
  learning_resources/etl/constants.py
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/etl/pipelines.py
  learning_resources/etl/pipelines_test.py
  learning_resources/management/commands/backpopulate_ocw_scores.py
  learning_resources/migrations/0061_learningresource_completeness.py
  learning_resources/models.py
  learning_resources/serializers_test.py
  openapi/specs/v1.yaml
Labels: Needs Review

#1475 Switched imagekit caching from in-memory to redis
  main/cache/backends.py
  main/cache/backends_test.py
  main/settings.py
Labels: Waiting on author

#1480 Fix syntax that a pre-commit check was failing
  data_fixtures/migrations/0001_add_testimonial_data.py
Labels: Needs Review

#1463 add to list dialog updates
  frontends/api/src/generated/v1/api.ts
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/test-utils/urls.ts
  frontends/mit-learn/src/page-components/Dialogs/AddToListDialog.test.tsx
  frontends/mit-learn/src/page-components/Dialogs/AddToListDialog.tsx
  frontends/ol-components/src/components/Checkbox/CheckboxChoiceField.tsx
  learning_resources/urls.py
  learning_resources/views.py
  learning_resources/views_learningpath_test.py
  learning_resources/views_userlist_test.py
  openapi/specs/v1.yaml
Labels: Needs Review

#1482 Remove Pathways (Coming Soon)
  frontends/mit-learn/src/page-components/Header/Header.tsx
  frontends/ol-components/src/components/NavDrawer/NavDrawer.stories.tsx
  frontends/ol-components/src/components/NavDrawer/NavDrawer.test.tsx
  frontends/ol-components/src/components/NavDrawer/NavDrawer.tsx
Labels: Needs Review

#1484 Fix dialog spacing + reset AddToListDialog
  .gitignore
  frontends/mit-learn/package.json
  frontends/mit-learn/src/page-components/Dialogs/AddToListDialog.tsx
  frontends/mit-learn/src/page-components/ManageListDialogs/ManageListDialogs.tsx
  frontends/mit-learn/webpack.config.js
  frontends/ol-components/src/components/Dialog/Dialog.tsx
  frontends/ol-components/src/components/FormDialog/FormDialog.stories.tsx
  frontends/ol-components/src/components/FormDialog/FormDialog.tsx
  frontends/ol-components/src/components/FormHelpers/FormHelpers.tsx
  frontends/ol-components/src/index.ts
  frontends/ol-widgets/src/components/editing/ManageWidgetDialog.tsx
  yarn.lock
Labels: Needs Review

#1473 Better Headings Structure
  frontends/mit-learn/src/page-components/CardTemplate/CardTemplate.test.tsx
  frontends/mit-learn/src/page-components/CardTemplate/CardTemplate.tsx
  frontends/mit-learn/src/page-components/ItemsListing/ItemsListing.test.tsx
  frontends/mit-learn/src/page-components/ItemsListing/ItemsListingComponent.tsx
  frontends/mit-learn/src/page-components/ResourceCard/ResourceCard.test.tsx
  frontends/mit-learn/src/page-components/ResourceCarousel/ResourceCarousel.test.tsx
  frontends/mit-learn/src/page-components/ResourceCarousel/ResourceCarousel.tsx
  frontends/mit-learn/src/page-components/SearchDisplay/SearchDisplay.tsx
  frontends/mit-learn/src/page-components/TestimonialDisplay/TestimonialDisplay.tsx
  frontends/mit-learn/src/page-components/UserListCard/UserListCardCondensed.test.tsx
  frontends/mit-learn/src/page-components/UserListCard/UserListCardCondensed.tsx
  frontends/mit-learn/src/pages/ChannelPage/ChannelPage.test.tsx
  frontends/mit-learn/src/pages/ChannelPage/ChannelPage.tsx
  frontends/mit-learn/src/pages/ChannelPage/ChannelSearch.tsx
  frontends/mit-learn/src/pages/ChannelPage/UnitChannelTemplate.tsx
  frontends/mit-learn/src/pages/DashboardPage/DashboardPage.tsx
  frontends/mit-learn/src/pages/DepartmentListingPage/DepartmentListingPage.test.tsx
  frontends/mit-learn/src/pages/DepartmentListingPage/DepartmentListingPage.tsx
  frontends/mit-learn/src/pages/HomePage/BrowseTopicsSection.tsx
  frontends/mit-learn/src/pages/HomePage/HeroSearch.tsx
  frontends/mit-learn/src/pages/HomePage/HomePage.test.tsx
  frontends/mit-learn/src/pages/HomePage/HomePage.tsx
  frontends/mit-learn/src/pages/HomePage/NewsEventsSection.tsx
  frontends/mit-learn/src/pages/HomePage/TestimonialsSection.tsx
  frontends/mit-learn/src/pages/HomePage/UpcomingCoursesSection.tsx
  frontends/mit-learn/src/pages/LearningPathListingPage/LearningPathListingPage.test.tsx
  frontends/mit-learn/src/pages/PrivacyPage/PrivacyPage.tsx
  frontends/mit-learn/src/pages/SearchPage/SearchPage.test.tsx
  frontends/mit-learn/src/pages/SearchPage/SearchPage.tsx
  frontends/mit-learn/src/pages/TermsPage/TermsPage.tsx
  frontends/mit-learn/src/pages/TopicListingPage/TopicsListingPage.test.tsx
  frontends/mit-learn/src/pages/TopicListingPage/TopicsListingPage.tsx
  frontends/mit-learn/src/pages/UnitsListingPage/UnitsListingPage.test.tsx
  frontends/mit-learn/src/pages/UnitsListingPage/UnitsListingPage.tsx
  frontends/mit-learn/src/pages/UserListListingComponent/UserListListingComponent.test.tsx
  frontends/mit-learn/src/pages/UserListListingComponent/UserListListingComponent.tsx
  frontends/mit-learn/src/routes.tsx
  frontends/ol-components/src/components/Banner/Banner.tsx
  frontends/ol-components/src/components/Card/Card.tsx
  frontends/ol-components/src/components/Card/ListCard.tsx
  frontends/ol-components/src/components/Dialog/Dialog.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.test.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.test.tsx
  frontends/ol-components/src/components/ThemeProvider/typography.ts
  frontends/ol-components/src/components/VisuallyHidden/VisuallyHidden.tsx
  frontends/ol-components/src/index.ts
  frontends/ol-test-utilities/package.json
  frontends/ol-test-utilities/src/assertions.ts
  frontends/ol-test-utilities/src/index.ts
  yarn.lock
Labels: Needs Review

#1485 homepage search revisions
  frontends/mit-learn/src/pages/HomePage/HeroSearch.tsx
  frontends/mit-learn/src/pages/HomePage/SearchInput.tsx
Labels: Needs Review

#1487 Fix a flaky test
  frontends/mit-learn/src/pages/ChannelPage/ChannelPage.test.tsx
Labels: Needs Review

#1466 score cutoff
  frontends/api/src/generated/v1/api.ts
  frontends/mit-learn/src/page-components/SearchDisplay/SearchDisplay.tsx
  frontends/mit-learn/src/page-components/SearchDisplay/SliderInput.tsx
  frontends/mit-learn/src/pages/SearchPage/SearchPage.test.tsx
  learning_resources_search/api.py
  learning_resources_search/api_test.py
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
  openapi/specs/v1.yaml
Labels: Waiting on author

#1488 fix codespace backend
  docker-compose.codespaces.yml
Labels: Needs Review

#1490 fix random hero image
  frontends/mit-learn/src/pages/HomePage/HeroSearch.tsx
Labels: Needs Review
