Repository mitodl/mit-learn, pull requests merged in 2024-12, with the labels that each got.

#1860 Consolidate qdrant functionality into its own app
  frontends/api/src/generated/v0/api.ts
  learning_resources/views_test.py
  learning_resources_search/api.py
  learning_resources_search/indexing_api.py
  learning_resources_search/indexing_api_test.py
  learning_resources_search/serializers.py
  learning_resources_search/tasks.py
  learning_resources_search/tasks_test.py
  learning_resources_search/urls.py
  learning_resources_search/views.py
  learning_resources_search/views_test.py
  main/settings.py
  main/urls.py
  openapi/specs/v0.yaml
  vector_search/__init__.py
  vector_search/admin.py
  vector_search/apps.py
  vector_search/management/__init__.py
  vector_search/management/commands/__init__.py
  vector_search/management/commands/generate_embeddings.py
  vector_search/migrations/__init__.py
  vector_search/models.py
  vector_search/serializers.py
  vector_search/tasks.py
  vector_search/tasks_test.py
  vector_search/urls.py
  vector_search/utils.py
  vector_search/utils_test.py
  vector_search/views.py
  vector_search/views_test.py
Labels: Waiting on author

#1850 v2 drawer qa adjustments
  frontends/main/src/app-pages/HomePage/NewsEventsSection.tsx
  frontends/ol-components/src/components/Card/Card.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/DifferingRunsTable.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpandedV2.tsx
Labels: Needs Review

#1871 fix card line clamping
  frontends/main/src/app-pages/HomePage/NewsEventsSection.tsx
  frontends/ol-components/src/components/Card/Card.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.tsx
Labels: Needs Review

#1873 fix certification type none display
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSectionV2.tsx
Labels: Needs Review

#1867 fix edx file imports
  frontends/api/src/generated/v1/api.ts
  learning_resources/constants.py
  learning_resources/etl/edx_shared.py
  learning_resources/etl/edx_shared_test.py
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/etl/ocw.py
  learning_resources/etl/utils.py
  learning_resources/etl/utils_test.py
  learning_resources/management/commands/backpopulate_mit_edx_files.py
  learning_resources/management/commands/backpopulate_mitxonline_files.py
  learning_resources/management/commands/backpopulate_oll_files.py
  learning_resources/management/commands/backpopulate_xpro_files.py
  learning_resources/migrations/0077_contentfile_file_extension_contentfile_source_path.py
  learning_resources/migrations/0078_alter_contentfile_content_type.py
  learning_resources/models.py
  learning_resources/tasks.py
  learning_resources/tasks_test.py
  openapi/specs/v1.yaml
  poetry.lock
  pyproject.toml
Labels: Waiting on author

#1870 Simplify Theme
  frontends/ol-components/src/components/Carousel/Carousel.stories.tsx
  frontends/ol-components/src/components/FormDialog/FormDialog.tsx
  frontends/ol-components/src/components/RoutedDrawer/RoutedDrawer.stories.tsx
  frontends/ol-components/src/components/ThemeProvider/MITLearnGlobalStyles.tsx
  frontends/ol-components/src/components/ThemeProvider/ThemeProvider.tsx
  frontends/ol-components/src/types/theme.d.ts
Labels: Waiting on author

#1869 OpenAI embeddings for vector search
  learning_resources_search/api.py
  main/settings.py
  main/settings_celery.py
  poetry.lock
  pyproject.toml
  vector_search/conftest.py
  vector_search/encoders/__init__.py
  vector_search/encoders/base.py
  vector_search/encoders/fastembed.py
  vector_search/encoders/litellm.py
  vector_search/encoders/utils.py
  vector_search/management/commands/generate_embeddings.py
  vector_search/tasks.py
  vector_search/tasks_test.py
  vector_search/utils.py
  vector_search/utils_test.py
  vector_search/views_test.py
Labels: Waiting on author

#1876 fix price comparison in differing runs table
  frontends/ol-components/src/components/LearningResourceCard/testUtils.ts
  frontends/ol-utilities/src/learning-resources/learning-resources.test.ts
  frontends/ol-utilities/src/learning-resources/learning-resources.ts
Labels: Waiting on author

#1872 Server render homepage and listing pages. Client-only drawer navigation.
  frontends/api/src/hooks/channels/index.ts
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/hooks/newsEvents/index.ts
  frontends/api/src/hooks/testimonials/index.ts
  frontends/api/src/ssr/prefetch.ts
  frontends/api/src/ssr/usePrefetchWarnings.test.ts
  frontends/api/src/test-utils/factories/channels.ts
  frontends/api/src/test-utils/urls.ts
  frontends/main/src/app-pages/UnitsListingPage/UnitCard.tsx
  frontends/main/src/app-pages/UnitsListingPage/UnitsListingPage.test.tsx
  frontends/main/src/app-pages/UnitsListingPage/UnitsListingPage.tsx
  frontends/main/src/app/about/page.tsx
  frontends/main/src/app/c/[channelType]/[name]/page.tsx
  frontends/main/src/app/dashboard/[tab]/[id]/page.tsx
  frontends/main/src/app/departments/page.tsx
  frontends/main/src/app/learningpaths/page.tsx
  frontends/main/src/app/onboarding/page.tsx
  frontends/main/src/app/page.tsx
  frontends/main/src/app/privacy/page.tsx
  frontends/main/src/app/search/page.tsx
  frontends/main/src/app/terms/page.tsx
  frontends/main/src/app/topics/page.tsx
  frontends/main/src/app/types.d.ts
  frontends/main/src/app/units/page.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawer.tsx
  frontends/main/src/page-components/ResourceCarousel/ResourceCarousel.tsx
  frontends/ol-components/src/components/Card/Card.tsx
  frontends/ol-components/src/components/Link/Link.tsx
  frontends/ol-components/src/components/RoutedDrawer/RoutedDrawer.tsx
Labels: Waiting on author

#1877 add a trailing slash to non contentfile OCW resources
  learning_resources/etl/ocw.py
  learning_resources/migrations/0079_ocw_pages_trailing_slash.py
Labels: Waiting on author

#1892 subscription email language update
  learning_resources_search/tasks.py
  learning_resources_search/tasks_test.py
Labels: Needs Review

#1895 Load font with simple link tag
  frontends/main/src/app/layout.tsx
  frontends/ol-components/src/components/ThemeProvider/MITLearnGlobalStyles.tsx
Labels: Needs Review

#1891 Populate OCW file extensions
  learning_resources/etl/ocw.py
  learning_resources/etl/ocw_test.py
Labels: Waiting on author

#1897 add nprogress loading bar
  frontends/.eslintrc.js
  frontends/main/package.json
  frontends/main/src/app-pages/DashboardPage/UserListDetailsTab.tsx
  frontends/main/src/app-pages/OnboardingPage/OnboardingPage.tsx
  frontends/main/src/app/providers.tsx
  frontends/main/src/page-components/HeroSearch/HeroSearch.tsx
  yarn.lock
Labels: Needs Review

#1889 Filter params for vector search
  frontends/api/src/generated/v0/api.ts
  learning_resources_search/api.py
  openapi/specs/v0.yaml
  vector_search/conftest.py
  vector_search/management/commands/generate_embeddings.py
  vector_search/serializers.py
  vector_search/utils.py
  vector_search/utils_test.py
  vector_search/views.py
  vector_search/views_test.py
Labels: Waiting on author

#1899 fix storybook
  .github/workflows/ci.yml
  frontends/ol-components/.storybook/main.ts
Labels: Waiting on author

#1900 add bordered button variant
  frontends/ol-components/src/components/Button/Button.mdx
  frontends/ol-components/src/components/Button/Button.stories.tsx
  frontends/ol-components/src/components/Button/Button.tsx
Labels: Needs Review

#1868 App env vars for use with local vault agent
  env/app_vars.sh
Labels: Needs Review, enhancement

#1893 drawer v2 - share resource
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV2.test.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV2.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpandedV2.test.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpandedV2.tsx
Labels: Needs Review

#1902 drawer v2 - use only vector based recommendation carousel
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV2.test.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV2.tsx
Labels: Waiting on author

#1905 Contentfile chunk embeddings
  poetry.lock
  pyproject.toml
  vector_search/conftest.py
  vector_search/encoders/litellm.py
  vector_search/management/commands/generate_embeddings.py
  vector_search/tasks.py
  vector_search/tasks_test.py
  vector_search/utils.py
  vector_search/utils_test.py
Labels: Needs Review

#1909 restore main tag in root layout
  frontends/main/src/app/styled.tsx
Labels: Waiting on author

#1908 fix v2 drawer scrolling issues
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV2.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSectionV2.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpandedV2.test.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpandedV2.tsx
  frontends/ol-components/src/components/Link/Link.tsx
Labels: Needs Review

#1912 add topics carousels to v2 drawer
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV2.test.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV2.tsx
  frontends/main/src/page-components/ResourceCarousel/ResourceCarousel.test.tsx
  frontends/main/src/page-components/ResourceCarousel/ResourceCarousel.tsx
Labels: Waiting on author

#1917 Update version of react used in tests to same as production
  frontends/api/package.json
  frontends/main/package.json
  frontends/main/src/app-pages/ChannelPage/ChannelPage.test.tsx
  frontends/main/src/test-utils/index.tsx
  frontends/ol-components/package.json
  frontends/ol-utilities/package.json
  yarn.lock
Labels: Needs Review

#1911 create default collections on local dev initialization
  docker-compose.apps.yml
  docker-compose.services.yml
  scripts/run-django-dev.sh
  vector_search/management/commands/create_qdrant_collections.py
Labels: Needs Review

#1915 Enable use of ollama (GPU powered) embeddings
  main/settings.py
  vector_search/encoders/litellm.py
Labels: Needs Review

#1918 Demo Course Recommendation Chatbot (not production-ready, for RC only)
  .devcontainer/devcontainer.json
  Dockerfile-litellm
  ai_chat/__init__.py
  ai_chat/agents.py
  ai_chat/agents_test.py
  ai_chat/apps.py
  ai_chat/conftest.py
  ai_chat/constants.py
  ai_chat/factories.py
  ai_chat/migrations/0001_initial.py
  ai_chat/migrations/__init__.py
  ai_chat/permissions.py
  ai_chat/proxy.py
  ai_chat/serializers.py
  ai_chat/urls.py
  ai_chat/utils.py
  ai_chat/views.py
  ai_chat/views_test.py
  app.json
  config/litellm_config.yml
  docker-compose.litellm.yml
  fixtures/common.py
  frontends/api/src/generated/v0/api.ts
  frontends/main/package.json
  frontends/main/public/images/mit_mascot_tim.png
  frontends/main/src/app-pages/ChatPage/ChatPage.tsx
  frontends/main/src/app-pages/ChatPage/send.ts
  frontends/main/src/app/chat/page.tsx
  frontends/main/src/common/feature_flags.ts
  frontends/main/src/page-components/Nlux-AiChat/AiChat.stories.tsx
  frontends/main/src/page-components/Nlux-AiChat/AiChat.tsx
  frontends/main/src/page-components/Nlux-AiChat/mit_mascot_tim.png
  frontends/main/src/page-components/Nlux-AiChat/mock-send.ts
  frontends/main/src/page-components/Nlux-AiChat/nlux-theme.css
  frontends/main/src/page-components/Nlux-AiChat/personas.tsx
  frontends/ol-utilities/src/lib/index.ts
  frontends/ol-utilities/src/lib/utils.ts
  generate_env.py
  main/settings.py
  main/urls.py
  openapi/specs/v0.yaml
  package.json
  poetry.lock
  pyproject.toml
  uwsgi.ini
  yarn.lock
Labels: Needs Review

#1907 Content File Vector Search Endpoint
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/generated/v1/api.ts
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  learning_resources_search/api.py
  main/settings.py
  openapi/specs/v0.yaml
  openapi/specs/v1.yaml
  poetry.lock
  pyproject.toml
  vector_search/constants.py
  vector_search/serializers.py
  vector_search/tasks.py
  vector_search/urls.py
  vector_search/utils.py
  vector_search/utils_test.py
  vector_search/views.py
  vector_search/views_test.py
Labels: Needs Review

#1923 Track chatbot activity in posthog
  ai_chat/agents.py
  ai_chat/agents_test.py
Labels: Needs Review
