Repository mitodl/mit-learn, pull requests merged in 2024-04, with the labels that each got.

#695 display image and description in userlists
  frontends/mit-open/src/page-components/CardTemplate/CardTemplate.test.tsx
  frontends/mit-open/src/page-components/CardTemplate/CardTemplate.tsx
  frontends/mit-open/src/page-components/LearningResourceCardTemplate/LearningResourceCardTemplate.tsx
  frontends/mit-open/src/page-components/UserListCardTemplate/UserListCardTemplate.test.tsx
  frontends/mit-open/src/page-components/UserListCardTemplate/UserListCardTemplate.tsx
  frontends/mit-open/src/pages/UserListListingPage/UserListListingPage.tsx
  frontends/ol-utilities/src/learning-resources/learning-resources.ts
Labels: Needs Review, product:mit-open

#686 Basic learning resources drawer
  frontends/api/src/test-utils/factories/learningResources.ts
  frontends/mit-open/.storybook/main.ts
  frontends/mit-open/.storybook/preview.tsx
  frontends/mit-open/src/GlobalStyles.tsx
  frontends/mit-open/src/common/constants.ts
  frontends/mit-open/src/common/urls.ts
  frontends/mit-open/src/page-components/CardTemplate/CardTemplate.tsx
  frontends/mit-open/src/page-components/LearningResourceCard/LearningResourceCard.test.tsx
  frontends/mit-open/src/page-components/LearningResourceCard/LearningResourceCard.tsx
  frontends/mit-open/src/page-components/LearningResourceCardTemplate/LearningResourceCardTemplate.tsx
  frontends/mit-open/src/page-components/LearningResourceDrawer/LearningResourceDrawer.test.tsx
  frontends/mit-open/src/page-components/LearningResourceDrawer/LearningResourceDrawer.tsx
  frontends/mit-open/src/routes.tsx
  frontends/mit-open/src/test-utils/index.tsx
  frontends/ol-ckeditor/src/components/CkeditorArticle.test.tsx
  frontends/ol-ckeditor/src/components/CkeditorArticle.tsx
  frontends/ol-ckeditor/src/components/CkeditorDisplay.tsx
  frontends/ol-components/jest.config.ts
  frontends/ol-components/package.json
  frontends/ol-components/src/components/EmbedlyCard/EmbedlyCard.test.tsx
  frontends/ol-components/src/components/EmbedlyCard/EmbedlyCard.tsx
  frontends/ol-components/src/components/EmbedlyCard/util.test.ts
  frontends/ol-components/src/components/EmbedlyCard/util.ts
  frontends/ol-components/src/components/RoutedDrawer/RoutedDrawer.test.tsx
  frontends/ol-components/src/components/RoutedDrawer/RoutedDrawer.tsx
  frontends/ol-components/src/components/ThemeProvider/ThemeProvider.tsx
  frontends/ol-components/src/components/learning-resources/ExpandedLearningResourceDisplay/ExpandedLearningResourceDisplay.stories.tsx
  frontends/ol-components/src/components/learning-resources/ExpandedLearningResourceDisplay/ExpandedLearningResourceDisplay.test.tsx
  frontends/ol-components/src/components/learning-resources/ExpandedLearningResourceDisplay/ExpandedLearningResourceDisplay.tsx
  frontends/ol-components/src/index.ts
  frontends/ol-components/src/types/theme.d.ts
  frontends/ol-utilities/jest.config.ts
  frontends/ol-utilities/package.json
  frontends/ol-utilities/src/components/embedly/index.ts
  frontends/ol-utilities/src/components/index.ts
  frontends/ol-utilities/src/learning-resources/learning-resources.ts
  frontends/ol-widgets/package.json
  frontends/ol-widgets/src/components/EmbeddedUrlWidgetContent.tsx
  frontends/ol-widgets/src/components/Widget-EmbeddedUrl.test.tsx
  frontends/ol-widgets/src/components/editing/ManageWidgetDialog-EmbeddedUrl.test.tsx
  frontends/ol-widgets/src/components/editing/UrlField.tsx
  yarn.lock
Labels: Waiting on author

#711 Group Renovate CKEditor PRs
  renovate.json
Labels: Needs Review

#718 add UserList modals and wire up buttons
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/test-utils/factories/userLists.ts
  frontends/mit-open/src/GlobalStyles.tsx
  frontends/mit-open/src/page-components/LearningResourceCard/AddToListDialog.test.tsx
  frontends/mit-open/src/page-components/LearningResourceCard/AddToListDialog.tsx
  frontends/mit-open/src/page-components/ManageListDialogs/ManageListDialogs.test.tsx
  frontends/mit-open/src/page-components/ManageListDialogs/ManageListDialogs.tsx
  frontends/mit-open/src/page-components/UserListCardTemplate/UserListCardTemplate.tsx
  frontends/mit-open/src/pages/LearningPathListingPage/LearningPathListingPage.test.tsx
  frontends/mit-open/src/pages/LearningPathListingPage/LearningPathListingPage.tsx
  frontends/mit-open/src/pages/ListDetailsPage/LearningPathDetailsPage.tsx
  frontends/mit-open/src/pages/ListDetailsPage/ListDetailsPage.test.ts
  frontends/mit-open/src/pages/ListDetailsPage/UserListDetailsPage.tsx
  frontends/mit-open/src/pages/UserListListingPage/UserListListingPage.test.tsx
  frontends/mit-open/src/pages/UserListListingPage/UserListListingPage.tsx
Labels: Needs Review, product:mit-open

#719 Revert "bump to 2024.3.22"
  openapi/specs/version.yaml
Labels: Needs Review

#720 fix flaky test in ManageListDialogs
  frontends/mit-open/src/page-components/ManageListDialogs/ManageListDialogs.test.tsx
Labels: Needs Review, product:mit-open

#717 Shanbady/add record hash field for hightouch sync
  frontends/api/src/generated/v1/api.ts
  frontends/api/src/test-utils/factories/programLetters.ts
  openapi/specs/v1.yaml
  profiles/factories.py
  profiles/migrations/0020_alter_programcertificate_options.py
  profiles/migrations/0021_programcertificate_record_hash.py
  profiles/migrations/0022_fill_programcertificate_record_hash.py
  profiles/models.py
  profiles/models_test.py
Labels: Needs Review

#723 adding initial models for user subscription
  learning_resources_search/migrations/0001_initial.py
  learning_resources_search/migrations/__init__.py
  learning_resources_search/models.py
Labels: Waiting on author

#730 Remove dupe line from learning_resources/urls.py file
  learning_resources/urls.py
Labels: Needs Review

#725 Channel types
  channels/api.py
  channels/apps.py
  channels/constants.py
  channels/factories.py
  channels/migrations/0003_channel_type.py
  channels/migrations/0004_unique_type_name_combo.py
  channels/models.py
  channels/permissions.py
  channels/permissions_test.py
  channels/schema.py
  channels/serializers.py
  channels/serializers_test.py
  channels/urls.py
  channels/views.py
  channels/views_test.py
  frontends/api/src/clients.ts
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/hooks/fields/index.ts
  frontends/api/src/hooks/fields/keyFactory.ts
  frontends/api/src/test-utils/factories/fields.ts
  frontends/api/src/test-utils/factories/index.ts
  frontends/api/src/test-utils/factories/learningResources.ts
  frontends/api/src/test-utils/urls.ts
  frontends/mit-open/src/common/urls.ts
  frontends/mit-open/src/components/FieldMenu/FieldMenu.test.tsx
  frontends/mit-open/src/components/FieldMenu/FieldMenu.tsx
  frontends/mit-open/src/pages/FieldPage/EditFieldAppearanceForm.test.tsx
  frontends/mit-open/src/pages/FieldPage/EditFieldAppearanceForm.tsx
  frontends/mit-open/src/pages/FieldPage/EditFieldPage.test.tsx
  frontends/mit-open/src/pages/FieldPage/EditFieldPage.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPage.test.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPage.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPageSkeleton.tsx
  learning_resources/serializers.py
  main/serializers.py
  main/urls.py
  openapi/specs/v0.yaml
Labels: Needs Review

#732 add userlist bookmark button and add to user list modal
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/hooks/learningResources/keyFactory.ts
  frontends/api/src/test-utils/factories/learningResources.ts
  frontends/api/src/test-utils/factories/userLists.ts
  frontends/mit-open/src/page-components/LearningResourceCard/AddToListDialog.test.tsx
  frontends/mit-open/src/page-components/LearningResourceCard/AddToListDialog.tsx
  frontends/mit-open/src/page-components/LearningResourceCard/LearningResourceCard.test.tsx
  frontends/mit-open/src/page-components/LearningResourceCard/LearningResourceCard.tsx
Labels: product:mit-open

#731 Configurable, Tabbed Carousels
  e2e_testing/tests/002_carousel.spec.ts
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/hooks/learningResources/keyFactory.ts
  frontends/api/src/test-utils/urls.ts
  frontends/mit-open/src/page-components/TabbedCarousel/TabbedCarousel.test.tsx
  frontends/mit-open/src/page-components/TabbedCarousel/TabbedCarousel.tsx
  frontends/mit-open/src/page-components/TabbedCarousel/types.ts
  frontends/mit-open/src/pages/HomePage/HomePage.test.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.tsx
  frontends/mit-open/src/pages/HomePage/HomePageCarousel.tsx
  frontends/ol-components/src/components/Carousel/Carousel.stories.tsx
  frontends/ol-components/src/components/Carousel/Carousel.test.tsx
  frontends/ol-components/src/components/Carousel/Carousel.tsx
  frontends/ol-components/src/components/FilledIconButton/FilledIconButton.tsx
  frontends/ol-components/src/components/TitledCarousel/TitledCarousel.stories.tsx
  frontends/ol-components/src/components/TitledCarousel/TitledCarousel.tsx
  frontends/ol-components/src/index.ts
Labels: Needs Review

#743 fix channel configuration
  channels/migrations/0005_alter_fieldchannel_configuration.py
  channels/models.py
Labels: Waiting on author

#741 fixing readonly exception in migration
  profiles/migrations/0022_fill_programcertificate_record_hash.py
Labels: Needs Review

#740 channel search ui
  frontends/api/src/clients.ts
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/hooks/learningResources/keyFactory.ts
  frontends/api/src/test-utils/factories/learningResources.ts
  frontends/api/src/test-utils/urls.ts
  frontends/mit-open/src/pages/FieldPage/EditFieldAppearanceForm.test.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPage.test.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPage.tsx
  frontends/mit-open/src/pages/FieldPage/FieldSearch.test.tsx
  frontends/mit-open/src/pages/FieldPage/FieldSearch.tsx
  frontends/mit-open/src/pages/FieldPage/FieldSearchFacetDisplay.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.tsx
  frontends/ol-components/src/index.ts
Labels: Waiting on author

#737 Shanbady/define percolate index schema
  learning_resources/hooks.py
  learning_resources_search/apps.py
  learning_resources_search/connection.py
  learning_resources_search/connection_test.py
  learning_resources_search/constants.py
  learning_resources_search/factories.py
  learning_resources_search/indexing_api.py
  learning_resources_search/indexing_api_test.py
  learning_resources_search/management/commands/recreate_index.py
  learning_resources_search/management/commands/update_index.py
  learning_resources_search/migrations/0002_alter_percolatequery_unique_together.py
  learning_resources_search/models.py
  learning_resources_search/plugins.py
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
  learning_resources_search/signals.py
  learning_resources_search/tasks.py
  learning_resources_search/utils.py
Labels: Waiting on author

#749 Add a channel for every topic, department, offeror
  channels/admin.py
  channels/plugins.py
  channels/plugins_test.py
  channels/urls.py
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/hooks.py
  learning_resources/management/commands/backpopulate_resource_channels.py
  learning_resources/management/commands/update_departments.py
  learning_resources/utils.py
  main/settings_pluggy.py
  openapi/specs/v0.yaml
Labels: Waiting on author

#754 Homepage hero section
  e2e_testing/tests/001_home.spec.ts
  frontends/mit-open/.storybook/main.ts
  frontends/mit-open/.storybook/preview.tsx
  frontends/mit-open/package.json
  frontends/mit-open/src/GlobalStyles.tsx
  frontends/mit-open/src/pages/HomePage/HeroSearch.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.test.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.tsx
  frontends/ol-components/package.json
  frontends/ol-components/src/components/ChipLink/ChipLink.stories.ts
  frontends/ol-components/src/components/ChipLink/ChipLink.tsx
  frontends/ol-components/src/components/FilledIconButton/FilledIconButton.tsx
  frontends/ol-components/src/components/SearchInput/SearchInput.tsx
  frontends/ol-components/src/components/ThemeProvider/ThemeProvider.tsx
  frontends/ol-components/src/components/ThemeProvider/Typography.mdx
  frontends/ol-components/src/components/ThemeProvider/Typography.stories.tsx
  frontends/ol-components/src/components/ThemeProvider/breakpoints.ts
  frontends/ol-components/src/components/ThemeProvider/buttons.ts
  frontends/ol-components/src/components/ThemeProvider/chips.ts
  frontends/ol-components/src/components/ThemeProvider/inputs.ts
  frontends/ol-components/src/components/ThemeProvider/typography.ts
  frontends/ol-components/src/index.ts
  frontends/ol-components/src/stories/Breakpoints.stories.tsx
  frontends/ol-components/src/types/theme.d.ts
  frontends/ol-components/src/types/typography.d.ts
  static/images/hero-background-texture.jpeg
  static/images/hero_woman.svg
  yarn.lock
Labels: Waiting on author

#779 Filter channels api by channel_type
  channels/serializers.py
  channels/views.py
  channels/views_test.py
  frontends/api/src/generated/v0/api.ts
  openapi/specs/v0.yaml
Labels: Waiting on author

#778 Add channel url to topic, department, and offeror serializers
  channels/factories.py
  channels/models.py
  channels/serializers.py
  channels/serializers_test.py
  channels/views.py
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/generated/v1/api.ts
  frontends/api/src/test-utils/factories/learningResources.ts
  frontends/mit-open/src/page-components/ManageListDialogs/ManageListDialogs.tsx
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  learning_resources_search/constants.py
  openapi/specs/v0.yaml
  openapi/specs/v1.yaml
Labels: Needs Review

#752 adding manual migration to fix foreign key type
  frontends/api/src/generated/v1/api.ts
  openapi/specs/v1.yaml
  profiles/migrations/0023_fix_program_certificate_foreign_key.py
  profiles/migrations/0024_alter_programcertificate_record_hash_and_more.py
  profiles/models.py
Labels: Needs Review

#746 Capture page views with more information
  frontends/mit-open/src/AppProviders.tsx
  frontends/mit-open/src/page-components/LearningResourceDrawer/LearningResourceDrawer.test.tsx
  frontends/mit-open/src/page-components/LearningResourceDrawer/LearningResourceDrawer.tsx
  frontends/mit-open/src/types/settings.d.ts
  frontends/mit-open/webpack.config.js
  frontends/ol-components/src/components/RoutedDrawer/RoutedDrawer.tsx
  main/views.py
Labels: product:mit-open, Waiting on author

#789 Adds ETL to pull PostHog view events into the database; adds popular resource APIs
  .env.example
  README.md
  frontends/api/src/generated/v1/api.ts
  frontends/mit-open/package.json
  learning_resources/admin.py
  learning_resources/constants.py
  learning_resources/etl/pipelines.py
  learning_resources/etl/pipelines_test.py
  learning_resources/etl/posthog.py
  learning_resources/etl/posthog_test.py
  learning_resources/exceptions.py
  learning_resources/factories.py
  learning_resources/management/commands/load_posthog_lrd_view_events.py
  learning_resources/migrations/0040_add_lrd_view_collection_table.py
  learning_resources/models.py
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  learning_resources/tasks.py
  learning_resources/views.py
  learning_resources/views_test.py
  learning_resources_search/urls.py
  main/settings.py
  main/settings_celery.py
  openapi/specs/v1.yaml
  poetry.lock
  pyproject.toml
  pytest.ini
  yarn.lock
Labels: product:mit-open, Waiting on author

#788 Add school model, api endpoint; remove school-less department channels
  channels/plugins.py
  channels/plugins_test.py
  frontends/api/src/generated/v1/api.ts
  frontends/api/src/test-utils/factories/learningResources.ts
  learning_resources/factories.py
  learning_resources/fixtures/departments.json
  learning_resources/fixtures/schools.json
  learning_resources/management/commands/update_departments.py
  learning_resources/management/commands/update_departments_schools.py
  learning_resources/management/commands/update_offered_by.py
  learning_resources/migrations/0040_schools.py
  learning_resources/models.py
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  learning_resources/urls.py
  learning_resources/utils.py
  learning_resources/views.py
  learning_resources/views_test.py
  learning_resources_search/constants.py
  openapi/specs/v1.yaml
  scripts/run-django-dev.sh
Labels: Waiting on author

#804 Merge the lrd_view migration and the schools migration
  learning_resources/migrations/0041_merge_0040_add_lrd_view_collection_table_0040_schools.py
Labels: product:mit-open, Waiting on author

#807 Fix index schema
  learning_resources_search/constants.py
Labels: Needs Review

#786 ETL for Open Learning events via API
  news_events/etl/conftest.py
  news_events/etl/ol_events.py
  news_events/etl/ol_events_test.py
  news_events/etl/utils.py
  news_events/etl/utils_test.py
  test_html/test_ol_events_item_1.html
  test_html/test_ol_events_item_2.html
  test_json/ol_events.json
  test_json/ol_events_audience.json
  test_json/ol_events_img_src.json
  test_json/ol_events_img_text.json
  test_json/ol_events_location.json
  test_json/ol_events_output.json
  test_json/ol_events_topics.json
Labels: Waiting on author

#782 create api routes for user subscribe/unsubscribe to search
  frontends/api/src/generated/v1/api.ts
  learning_resources_search/admin.py
  learning_resources_search/api.py
  learning_resources_search/migrations/0003_alter_percolatequery_unique_together.py
  learning_resources_search/models.py
  learning_resources_search/serializers.py
  learning_resources_search/signals.py
  learning_resources_search/urls.py
  learning_resources_search/utils.py
  learning_resources_search/views.py
  learning_resources_search/views_test.py
  openapi/specs/v1.yaml
Labels: Needs Review

#812 Updating the LearningResourceViewEvent to cascade delete
  learning_resources/migrations/0042_update_ondelete_for_events.py
  learning_resources/models.py
Labels: Waiting on author

#802 add certification as facet to field search
  frontends/mit-open/package.json
  frontends/mit-open/src/pages/FieldPage/FieldPage.tsx
  frontends/mit-open/src/pages/FieldPage/FieldSearch.test.tsx
  frontends/mit-open/src/pages/FieldPage/FieldSearch.tsx
  frontends/mit-open/src/pages/FieldPage/FieldSearchFacetDisplay.tsx
  yarn.lock
Labels: Needs Review

#810 "free" filter for REST/search API
  frontends/api/src/generated/v1/api.ts
  frontends/api/src/test-utils/factories/learningResources.ts
  learning_resources/filters.py
  learning_resources/filters_test.py
  learning_resources/models.py
  learning_resources_search/api_test.py
  learning_resources_search/constants.py
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
  openapi/specs/v1.yaml
Labels: Waiting on author

#817 Populate prices for mitxonline programs
  learning_resources/etl/mitxonline.py
  learning_resources/etl/mitxonline_test.py
Labels: Waiting on author

#785 Do not analyze webpack by default
  .env.example
Labels: Waiting on author

#827 Text Input + Select components
  frontends/mit-open/package.json
  frontends/mit-open/src/page-components/ArticleUpsertForm/ArticleUpsertForm.tsx
  frontends/mit-open/src/page-components/ManageListDialogs/ManageListDialogs.tsx
  frontends/mit-open/src/pages/FieldPage/EditFieldAppearanceForm.tsx
  frontends/mit-open/src/pages/FieldPage/FieldSearch.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.tsx
  frontends/ol-components/package.json
  frontends/ol-components/src/components/FormHelpers/FormHelpers.test.tsx
  frontends/ol-components/src/components/FormHelpers/FormHelpers.tsx
  frontends/ol-components/src/components/Input/Input.mdx
  frontends/ol-components/src/components/Input/Input.stories.tsx
  frontends/ol-components/src/components/Input/Input.test.tsx
  frontends/ol-components/src/components/Input/Input.tsx
  frontends/ol-components/src/components/SearchInput/SearchInput.test.tsx
  frontends/ol-components/src/components/SearchInput/SearchInput.tsx
  frontends/ol-components/src/components/SelectField/SelectField.mdx
  frontends/ol-components/src/components/SelectField/SelectField.stories.tsx
  frontends/ol-components/src/components/SelectField/SelectField.test.tsx
  frontends/ol-components/src/components/SelectField/SelectField.tsx
  frontends/ol-components/src/components/TextField/TextField.mdx
  frontends/ol-components/src/components/TextField/TextField.stories.tsx
  frontends/ol-components/src/components/TextField/TextField.test.tsx
  frontends/ol-components/src/components/TextField/TextField.tsx
  frontends/ol-components/src/components/ThemeProvider/ThemeProvider.tsx
  frontends/ol-components/src/components/ThemeProvider/colors.ts
  frontends/ol-components/src/components/ThemeProvider/inputs.ts
  frontends/ol-components/src/index.ts
  frontends/ol-components/src/types/theme.d.ts
  frontends/ol-test-utilities/src/domQueries.ts
  frontends/ol-widgets/package.json
  yarn.lock
Labels: Needs Review

#833 Minor updates for PostHog settings
  .env.example
  README.md
  app.json
  frontends/mit-open/src/AppProviders.test.tsx
  frontends/mit-open/src/AppProviders.tsx
  frontends/mit-open/src/page-components/LearningResourceDrawer/LearningResourceDrawer.test.tsx
  frontends/mit-open/src/page-components/LearningResourceDrawer/LearningResourceDrawer.tsx
  frontends/mit-open/src/types/settings.d.ts
  frontends/mit-open/webpack.config.js
  frontends/ol-utilities/src/types/settings.d.ts
  main/features.py
  main/features_test.py
  main/settings.py
  main/views.py
Labels: product:mit-open, Waiting on author

#828 Add format field to LearningResource model and ETL pipelines
  frontends/api/src/generated/v1/api.ts
  learning_resources/constants.py
  learning_resources/etl/constants.py
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/etl/prolearn.py
  learning_resources/etl/prolearn_test.py
  learning_resources/etl/utils.py
  learning_resources/etl/utils_test.py
  learning_resources/etl/xpro.py
  learning_resources/etl/xpro_test.py
  learning_resources/factories.py
  learning_resources/migrations/0043_learningresource_format.py
  learning_resources/models.py
  learning_resources/serializers_test.py
  learning_resources_search/constants.py
  openapi/specs/v1.yaml
  test_json/xpro_courses.json
  test_json/xpro_programs.json
Labels: Needs Review
