Repository mitodl/mit-learn, pull requests merged in 2024-07, with the labels that each got.

#1198 update unit names
  frontends/api/src/generated/v1/api.ts
  frontends/ol-components/src/components/Logo/Logo.tsx
  learning_resources/constants.py
  learning_resources/data/channel_templates/offerors.json
  learning_resources/etl/loaders_test.py
  learning_resources/etl/prolearn.py
  learning_resources/etl/prolearn_test.py
  learning_resources/etl/xpro.py
  learning_resources/fixtures/offered_by.json
  learning_resources/fixtures/platforms.json
  learning_resources_search/serializers_test.py
  news_events/etl/sloan_exec_news_test.py
  openapi/specs/v1.yaml
  test_json/xpro_courses.json
  test_json/xpro_programs.json
Labels: Needs Review

#1212 Fix default image height in resource cards
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.tsx
Labels: Needs Review

#1208 Privacy policy updates
  .env.example
  .github/workflows/production.yml
  .github/workflows/release-candidate.yml
  frontends/mit-open/src/pages/PrivacyPage/PrivacyPage.tsx
  frontends/mit-open/webpack.config.js
Labels: Needs Review

#1179 Removing nginx serving of the frontend for local setups
  .env.example
  .github/workflows/ci.yml
  .github/workflows/production.yml
  .github/workflows/release-candidate.yml
  .gitignore
  README.md
  app.json
  channels/models.py
  channels/serializers_test.py
  config/nginx.conf
  config/nginx.conf.erb
  config/static-app.conf
  docker-compose-e2e-tests.yml
  docker-compose.yml
  env/.gitignore
  env/backend.env
  env/backend.local.example.env
  env/ci.env
  env/frontend.env
  env/frontend.local.example.env
  env/shared.env
  env/shared.local.example.env
  fixtures/common.py
  frontends/api/src/clients.ts
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/generated/v1/api.ts
  frontends/api/src/test-utils/urls.ts
  frontends/mit-open/jest.config.ts
  frontends/mit-open/src/common/urls.test.ts
  frontends/mit-open/src/common/urls.ts
  frontends/mit-open/webpack.config.js
  learning_resources/etl/constants.py
  learning_resources/etl/podcast.py
  learning_resources/etl/podcast_test.py
  learning_resources/serializers_test.py
  learning_resources_search/indexing_api_test.py
  learning_resources_search/tasks.py
  main/settings.py
  main/settings_test.py
  main/urls.py
  main/utils.py
  main/utils_test.py
  nginx/20-compile-nginx-conf-erb.sh
  nginx/Dockerfile
  openapi/specs/v0.yaml
  openapi/specs/v1.yaml
  package.json
  profiles/models.py
  profiles/serializers.py
  profiles/urls.py
  profiles/utils.py
  profiles/views.py
  profiles/views_test.py
Labels: Waiting on author

#1216 Fix and reenable onboarding page tests
  frontends/mit-open/src/pages/OnboardingPage/OnboardingPage.test.tsx
Labels: Waiting on author

#1211 resource category tabs
  frontends/mit-open/package.json
  frontends/mit-open/src/page-components/Header/Header.tsx
  frontends/mit-open/src/page-components/SearchDisplay/ResourceCategoryTabs.tsx
  frontends/mit-open/src/page-components/SearchDisplay/SearchDisplay.tsx
  frontends/mit-open/src/pages/ChannelPage/ChannelSearch.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.test.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.tsx
  yarn.lock
Labels: Waiting on author

#1213 make primary buttons shadowy, remove edge=none
  frontends/ol-components/src/components/Button/Button.stories.tsx
  frontends/ol-components/src/components/Button/Button.tsx
Labels: Needs Review

#1157 Updates icons to use Remixicons where they don't already
  frontends/.eslintrc.js
  frontends/mit-open/package.json
  frontends/mit-open/public/images/navdrawer/certificate.svg
  frontends/mit-open/public/images/navdrawer/courses.svg
  frontends/mit-open/public/images/navdrawer/departments.svg
  frontends/mit-open/public/images/navdrawer/free.svg
  frontends/mit-open/public/images/navdrawer/learning_materials.svg
  frontends/mit-open/public/images/navdrawer/new.svg
  frontends/mit-open/public/images/navdrawer/pathways.svg
  frontends/mit-open/public/images/navdrawer/popular.svg
  frontends/mit-open/public/images/navdrawer/programs.svg
  frontends/mit-open/public/images/navdrawer/provider.svg
  frontends/mit-open/public/images/navdrawer/topics.svg
  frontends/mit-open/src/components/ChannelMenu/ChannelMenu.tsx
  frontends/mit-open/src/components/RootTopicIcon/RootTopicIcon.tsx
  frontends/mit-open/src/page-components/CardTemplate/CardTemplate.tsx
  frontends/mit-open/src/page-components/ChannelDetails/ChannelDetails.tsx
  frontends/mit-open/src/page-components/Dialogs/AddToListDialog.tsx
  frontends/mit-open/src/page-components/Header/Header.tsx
  frontends/mit-open/src/page-components/LearningResourceCard/LearningResourceCard.tsx
  frontends/mit-open/src/page-components/LearningResourceCardTemplate/LearningResourceCardTemplate.test.tsx
  frontends/mit-open/src/page-components/LearningResourceCardTemplate/LearningResourceCardTemplate.tsx
  frontends/mit-open/src/page-components/SearchDisplay/SearchInput.tsx
  frontends/mit-open/src/page-components/SearchSubscriptionToggle/SearchSubscriptionToggle.tsx
  frontends/mit-open/src/pages/DashboardPage/DashboardPage.tsx
  frontends/mit-open/src/pages/DepartmentListingPage/DepartmentListingPage.tsx
  frontends/mit-open/src/pages/HomePage/SearchInput.tsx
  frontends/mit-open/src/pages/LearningPathListingPage/LearningPathListingPage.tsx
  frontends/mit-open/src/pages/ListDetailsPage/ListDetailsPage.tsx
  frontends/mit-open/src/pages/UserListListingPage/UserListListingPage.tsx
  frontends/ol-components/package.json
  frontends/ol-components/src/components/Button/Button.mdx
  frontends/ol-components/src/components/Chips/Chip.stories.tsx
  frontends/ol-components/src/components/FormDialog/FormDialog.tsx
  frontends/ol-components/src/components/FormHelpers/FormHelpers.tsx
  frontends/ol-components/src/components/Input/Input.stories.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSection.tsx
  frontends/ol-components/src/components/NavDrawer/NavDrawer.tsx
  frontends/ol-components/src/components/SimpleMenu/SimpleMenu.stories.tsx
  frontends/ol-components/src/components/TextField/TextField.stories.tsx
  frontends/ol-widgets/package.json
  frontends/ol-widgets/src/components/Widget.tsx
  frontends/ol-widgets/src/components/editing/WidgetsListEditable.tsx
  yarn.lock
Labels: Needs Review, product:mit-open

#1221 Webpack build config loads .env files for running outside of Docker
  frontends/mit-open/package.json
  frontends/mit-open/webpack.config.js
Labels: Needs Review

#1218 Data fixtures app for loading static fixtures
  data_fixtures/__init__.py
  data_fixtures/apps.py
  data_fixtures/migrations/0001_add_testimonial_data.py
  data_fixtures/migrations/__init__.py
  main/settings.py
  scripts/heroku-release-phase.sh
  scripts/run-django-dev.sh
  testimonials/fixtures/avatars/Anesha Santhanam.png
  testimonials/fixtures/avatars/Arthur Julio Nelson.png
  testimonials/fixtures/avatars/Brenda Patel.png
  testimonials/fixtures/avatars/Chansa Kabwe.png
  testimonials/fixtures/avatars/Claudio Mirti.png
  testimonials/fixtures/avatars/Emily R. Wright.png
  testimonials/fixtures/avatars/Emmanuel Kasigazi.png
  testimonials/fixtures/avatars/Jasmine Latham.png
  testimonials/fixtures/avatars/John Goodloe.png
  testimonials/fixtures/avatars/Lauren Moscioni.png
  testimonials/fixtures/avatars/Linda Obregon.png
  testimonials/fixtures/avatars/Maria Eduarda.png
  testimonials/fixtures/avatars/Murali Thyagarajan.png
  testimonials/fixtures/avatars/Sebastian Bello.png
  testimonials/fixtures/avatars/Stephen Okiya.png
Labels: Needs Review

#1191 Update resource drawer text and URL for podcast episodes
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.test.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.tsx
Labels: Needs Review

#1219 better spacing around pagination component
  frontends/mit-open/src/page-components/SearchDisplay/SearchDisplay.tsx
Labels: Needs Review

#1228 Navigation UI fixes
  frontends/mit-open/src/page-components/Header/Header.tsx
  frontends/ol-components/src/components/NavDrawer/NavDrawer.tsx
Labels: Needs Review

#1229 Only publish enrollable mitxonline courses
  learning_resources/etl/mitxonline.py
  learning_resources/etl/mitxonline_test.py
Labels: Needs Review

#1233 Homepage and nav drawer copy edits
  frontends/mit-open/src/page-components/Header/Header.tsx
  frontends/mit-open/src/page-components/SearchDisplay/ProfessionalToggle.tsx
  frontends/mit-open/src/page-components/SignupPopover/SignupPopover.tsx
  frontends/mit-open/src/pages/HomePage/HeroSearch.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.test.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.tsx
  frontends/mit-open/src/pages/HomePage/NewsEventsSection.tsx
  frontends/mit-open/src/pages/HomePage/PersonalizeSection.tsx
  frontends/mit-open/src/pages/HomePage/TestimonialsSection.tsx
  frontends/mit-open/src/pages/PrivacyPage/PrivacyPage.tsx
Labels: Needs Review

#1231 extra weight for instructors
  learning_resources_search/api_test.py
  learning_resources_search/constants.py
Labels: Waiting on author

#1227 Use overwrite=True when calling pluggy function from upsert_offered_by
  learning_resources/utils.py
  learning_resources/utils_test.py
Labels: Waiting on author

#1230 fix learning path count, increase item page size
  frontends/mit-open/src/pages/DashboardPage/DashboardPage.tsx
  frontends/mit-open/src/pages/ListDetailsPage/LearningPathDetailsPage.tsx
  frontends/mit-open/src/pages/ListDetailsPage/ListDetailsPage.test.ts
  frontends/mit-open/src/pages/ListDetailsPage/ListDetailsPage.tsx
  frontends/mit-open/src/pages/ListDetailsPage/UserListDetailsPage.tsx
Labels: Needs Review

#1237 resource drawer UI fixes
  frontends/mit-open/public/images/ocw-logo.png
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.tsx
  frontends/ol-components/src/components/Logo/Logo.tsx
Labels: Waiting on author

#1238 Align departments listing colors to designs
  frontends/mit-open/src/pages/DepartmentListingPage/DepartmentListingPage.tsx
Labels: Waiting on author

#1239 remove manage widgets
  frontends/mit-open/src/components/ChannelMenu/ChannelMenu.test.tsx
  frontends/mit-open/src/components/ChannelMenu/ChannelMenu.tsx
Labels: Needs Review

#1236 Fix logout view
  authentication/views.py
Labels: Waiting on author

#1249 for github pages, use main not "$default-branch"
  .github/workflows/publish-pages.yml
Labels: Waiting on author

#1234 adjust / refactor channel detail header
  frontends/mit-open/src/pages/ChannelPage/ChannelPage.test.tsx
  frontends/mit-open/src/pages/ChannelPage/ChannelPage.tsx
  frontends/mit-open/src/pages/ChannelPage/ChannelPageSkeleton.tsx
  frontends/mit-open/src/pages/ChannelPage/ChannelPageTemplate.tsx
  frontends/mit-open/src/pages/ChannelPage/ChannelSearch.test.tsx
  frontends/mit-open/src/pages/ChannelPage/DefaultChannelTemplate.tsx
  frontends/mit-open/src/pages/ChannelPage/EditChannelPage.tsx
  frontends/mit-open/src/pages/ChannelPage/UnitChannelTemplate.tsx
  frontends/mit-open/src/pages/DepartmentListingPage/DepartmentListingPage.tsx
  frontends/mit-open/src/pages/TopicListingPage/TopicsListingPage.tsx
  frontends/mit-open/src/pages/UnitsListingPage/UnitsListingPage.tsx
  frontends/ol-components/src/components/Banner/Banner.stories.tsx
  frontends/ol-components/src/components/Banner/Banner.tsx
  frontends/ol-components/src/components/Breadcrumbs/Breadcrumbs.test.tsx
  frontends/ol-components/src/components/Breadcrumbs/Breadcrumbs.tsx
Labels: Needs Review

#1232 Change readable_id values for podcasts and episodes
  learning_resources/etl/loaders.py
  learning_resources/etl/podcast.py
  learning_resources/etl/podcast_test.py
  learning_resources/management/commands/transfer_list_resources.py
  learning_resources/migrations/0056_alter_learningresource_readable_id.py
  learning_resources/models.py
  learning_resources/utils.py
  learning_resources/utils_test.py
  openapi/specs/v1.yaml
Labels: Needs Review

#1248 Plain text news/events titles/authors; standardize html cleanup
  learning_resources/etl/constants.py
  learning_resources/etl/mitxonline.py
  learning_resources/etl/mitxonline_test.py
  learning_resources/etl/ocw.py
  learning_resources/etl/ocw_test.py
  learning_resources/etl/openedx.py
  learning_resources/etl/podcast.py
  learning_resources/etl/prolearn.py
  learning_resources/etl/prolearn_test.py
  learning_resources/etl/utils.py
  learning_resources/etl/utils_test.py
  learning_resources/etl/xpro.py
  learning_resources/etl/youtube.py
  learning_resources/etl/youtube_test.py
  main/constants.py
  main/utils.py
  main/utils_test.py
  news_events/etl/medium_mit_news.py
  news_events/etl/medium_mit_news_test.py
  news_events/etl/ol_events.py
  news_events/etl/sloan_exec_news.py
  news_events/etl/sloan_exec_news_test.py
  news_events/etl/utils.py
  news_events/etl/utils_test.py
  test_html/test_medium_mit_news.rss
  test_json/ol_events_output.json
  test_json/test_sloan_exec_news.json
Labels: Needs Review

#1247 reindexing changes
  learning_resources_search/indexing_api.py
  learning_resources_search/indexing_api_test.py
  learning_resources_search/management/commands/recreate_index.py
  learning_resources_search/tasks.py
  learning_resources_search/tasks_test.py
Labels: Needs Review

#1252 change xpro ETL dict key back
  learning_resources/etl/xpro.py
  test_json/xpro_courses.json
  test_json/xpro_programs.json
Labels: Needs Review

#1250 Addresses performance issues for the topics API
  channels/migrations/0011_add_topic_detail_related_name.py
  channels/models.py
  channels/serializers.py
  channels/views.py
  channels/views_test.py
  conftest.py
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/generated/v1/api.ts
  learning_resources/models.py
  learning_resources/serializers.py
  learning_resources/views.py
  learning_resources/views_test.py
  main/settings.py
  main/urls.py
  openapi/specs/v0.yaml
  openapi/specs/v1.yaml
  poetry.lock
  pyproject.toml
Labels: Needs Review

#1253 adjust department names
  channels/plugins.py
  channels/plugins_test.py
  frontends/api/src/generated/v1/api.ts
  learning_resources/constants.py
  learning_resources/etl/openedx_test.py
  learning_resources/fixtures/departments.json
  learning_resources/fixtures/schools.json
  learning_resources/utils.py
  openapi/specs/v1.yaml
Labels: Waiting on author

#1259 Make static/hash.txt served again
  .gitignore
  bin/pre_compile
  main/settings.py
  main/urls.py
Labels: Waiting on author

#1264 Take is_enrollable attribute into account for publish status of edx resources
  learning_resources/etl/openedx.py
  learning_resources/etl/openedx_test.py
Labels: Waiting on author

#1271 Add profile option for silky to settings
  main/settings.py
Labels: Waiting on author

#1277 add a story showing platform logos
  docker-compose.yml
  frontends/mit-open/.storybook/main.ts
  frontends/ol-components/src/components/Logo/Logo.stories.tsx
Labels: Needs Review

#1266 refactor profile and onboarding
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/test-utils/factories/user.ts
  frontends/mit-open/src/common/profile.tsx
  frontends/mit-open/src/page-components/ManageListDialogs/ManageListDialogs.tsx
  frontends/mit-open/src/page-components/Profile/CertificateChoice.tsx
  frontends/mit-open/src/page-components/Profile/EducationLevelChoice.tsx
  frontends/mit-open/src/page-components/Profile/GoalsChoice.tsx
  frontends/mit-open/src/page-components/Profile/LearningFormatChoice.tsx
  frontends/mit-open/src/page-components/Profile/TimeCommitmentChoice.tsx
  frontends/mit-open/src/page-components/Profile/TopicInterestsChoice.tsx
  frontends/mit-open/src/pages/ChannelPage/EditChannelAppearanceForm.tsx
  frontends/mit-open/src/pages/DashboardPage/ProfileEditForm.tsx
  frontends/mit-open/src/pages/OnboardingPage/OnboardingPage.test.tsx
  frontends/mit-open/src/pages/OnboardingPage/OnboardingPage.tsx
  frontends/ol-components/src/components/Checkbox/Checkbox.tsx
  frontends/ol-components/src/components/Checkbox/CheckboxChoiceField.stories.tsx
  frontends/ol-components/src/components/Checkbox/CheckboxChoiceField.tsx
  frontends/ol-components/src/components/ChoiceBox/ChoiceBox.tsx
  frontends/ol-components/src/components/ChoiceBox/ChoiceBoxField.tsx
  frontends/ol-components/src/components/FormHelpers/FormHelpers.tsx
  frontends/ol-components/src/components/Input/Input.tsx
  frontends/ol-components/src/components/RadioChoiceField/RadioChoiceField.test.tsx
  frontends/ol-components/src/components/RadioChoiceField/RadioChoiceField.tsx
  frontends/ol-components/src/components/SimpleSelect/SimpleSelect.stories.tsx
  frontends/ol-components/src/index.ts
  openapi/specs/v0.yaml
  profiles/factories.py
  profiles/migrations/0028_alter_profile_goals.py
  profiles/migrations/0029_alter_profile_certificate_desired.py
  profiles/migrations/0030_alter_profile_learning_format.py
  profiles/models.py
  profiles/serializers.py
  profiles/serializers_test.py
  profiles/views_test.py
Labels: Needs Review

#1273 Shanbady/clicking item routes away from list
  frontends/mit-open/src/page-components/LearningResourceDrawer/LearningResourceDrawer.tsx
  frontends/ol-components/src/components/RoutedDrawer/RoutedDrawer.test.tsx
  frontends/ol-components/src/components/RoutedDrawer/RoutedDrawer.tsx
Labels: Needs Review

#1274 Improve offeror API performance
  channels/migrations/0012_alter_channelunitdetail_unit.py
  channels/models.py
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/generated/v1/api.ts
  learning_resources/models.py
  learning_resources/serializers.py
  learning_resources/views.py
  learning_resources/views_test.py
  openapi/specs/v0.yaml
  openapi/specs/v1.yaml
Labels: Waiting on author

#1256 Use newer Learning Resource list cards in Learning Paths lists
  frontends/mit-open/src/page-components/ItemsListing/ItemsListing.test.tsx
  frontends/mit-open/src/page-components/ItemsListing/ItemsListing.tsx
  frontends/mit-open/src/page-components/ItemsListing/ItemsListingComponent.tsx
  frontends/mit-open/src/pages/DashboardPage/DashboardPage.tsx
  frontends/mit-open/src/pages/DashboardPage/UserListDetailsTab.tsx
  frontends/mit-open/src/pages/ListDetailsPage/ListDetailsPage.test.ts
  frontends/mit-open/src/pages/ListDetailsPage/ListDetailsPage.tsx
Labels: Needs Review

#1279 fix keyboard drag and drop
  frontends/ol-components/src/components/SortableList/SortableList.tsx
Labels: Needs Review

#1270 Shanbady/ingest sloan events
  main/settings_celery.py
  news_events/etl/pipelines.py
  news_events/etl/sloan_webinars.py
  news_events/etl/sloan_webinars_test.py
  news_events/tasks.py
  poetry.lock
  pyproject.toml
  test_json/sloan_webinars_output.json
Labels: Waiting on author

#1276 adding migrations for copy update
  data_fixtures/migrations/0003_unit_page_copy_updates.py
Labels: Needs Review

#1280 Shanbady/clicking item routes away from list fix
  frontends/ol-components/src/components/RoutedDrawer/RoutedDrawer.tsx
Labels: Needs Review

#1272 Unit Detail Banner Updates
  frontends/mit-open/src/page-components/ChannelDetails/ChannelDetails.tsx
  frontends/mit-open/src/page-components/SearchSubscriptionToggle/SearchSubscriptionToggle.tsx
  frontends/mit-open/src/pages/ChannelPage/ChannelPage.test.tsx
  frontends/mit-open/src/pages/ChannelPage/UnitChannelTemplate.tsx
  frontends/ol-components/src/components/Banner/Banner.tsx
  frontends/ol-components/src/components/Button/Button.stories.tsx
  frontends/ol-components/src/components/Button/Button.tsx
  frontends/ol-components/src/index.ts
Labels: Needs Review

#1282 Draggable list card styles
  frontends/mit-open/src/page-components/ItemsListing/ItemsListing.test.tsx
  frontends/mit-open/src/page-components/ItemsListing/ItemsListing.tsx
  frontends/mit-open/src/page-components/LearningResourceCard/LearningResourceCard.test.tsx
  frontends/mit-open/src/page-components/LearningResourceCard/LearningResourceCard.tsx
  frontends/mit-open/src/page-components/LearningResourceCardTemplate/LearningResourceCardTemplate.test.tsx
  frontends/mit-open/src/page-components/LearningResourceCardTemplate/LearningResourceCardTemplate.tsx
  frontends/mit-open/src/page-components/UserListCardTemplate/UserListCardTemplate.tsx
  frontends/mit-open/src/pages/DashboardPage/UserListDetailsTab.tsx
  frontends/mit-open/src/test-utils/setupJest.ts
  frontends/ol-components/src/components/Card/ListCard.tsx
  frontends/ol-components/src/components/Card/ListCardCondensed.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.stories.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCardCondensed.stories.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCardCondensed.tsx
  frontends/ol-components/src/components/SortableList/SortableList.tsx
Labels: Needs Review

#1278 Improve channel API performance
  channels/migrations/0013_alter_channel_channel_type.py
  channels/models.py
  channels/serializers.py
  channels/views.py
  channels/views_test.py
Labels: Needs Review

#1289 Revert "Fix bug with background image obscuring search controls"
  frontends/mit-open/src/pages/SearchPage/SearchPage.tsx
Labels: Waiting on author

#1287 fix restricted redirect
  frontends/mit-open/package.json
  frontends/mit-open/src/common/urls.ts
  frontends/mit-open/src/components/RestrictedRoute/RestrictedRoute.test.tsx
  frontends/mit-open/src/components/RestrictedRoute/RestrictedRoute.tsx
  frontends/mit-open/src/pages/ErrorPage/ForbiddenPage.test.tsx
  frontends/mit-open/src/pages/ErrorPage/ForbiddenPage.tsx
  frontends/mit-open/webpack.config.js
Labels: Waiting on author

#1293 Fix bug with background image obscuring search controls
  frontends/mit-open/src/pages/SearchPage/SearchPage.tsx
Labels: Waiting on author

#1283 add staleness penalty slider
  frontends/api/src/generated/v1/api.ts
  frontends/mit-open/src/page-components/SearchDisplay/SearchDisplay.tsx
  frontends/mit-open/src/page-components/SearchDisplay/StalenessPenaltySlider.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.test.tsx
  frontends/ol-components/src/index.ts
  learning_resources_search/api.py
  learning_resources_search/api_test.py
  learning_resources_search/constants.py
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
  openapi/specs/v1.yaml
Labels: Waiting on author

#1298 set search page size to 20
  frontends/mit-open/src/page-components/SearchDisplay/SearchDisplay.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.test.tsx
Labels: Waiting on author

#1290 Save resource prices in a new database model and calculate during ETL/nightly task
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/migrations/0045_learningresource_next_start_date.py
  learning_resources/migrations/0057_learningresource_next_prices.py
  learning_resources/models.py
  learning_resources/models_test.py
  learning_resources/serializers.py
  learning_resources/tasks.py
  learning_resources/tasks_test.py
  learning_resources/views_test.py
  main/settings_celery.py
  openapi/specs/v1.yaml
Labels: Needs Review

#1304 Database index on FeedEventDetail.event_datetime
  news_events/migrations/0003_alter_feedeventdetail_event_datetime.py
  news_events/models.py
Labels: Waiting on author

#1299 Enable User List sorting for non Learning Path editors
  frontends/mit-open/src/page-components/ItemsListing/ItemsListingComponent.tsx
  frontends/mit-open/src/page-components/ManageListDialogs/ManageListDialogs.test.tsx
  frontends/mit-open/src/page-components/ManageListDialogs/ManageListDialogs.tsx
  frontends/mit-open/src/pages/DashboardPage/UserListDetailsTab.tsx
  frontends/mit-open/src/pages/ListDetailsPage/LearningPathDetailsPage.tsx
  frontends/mit-open/src/pages/ListDetailsPage/ListDetailsPage.test.ts
  frontends/mit-open/src/pages/ListDetailsPage/ListDetailsPage.tsx
  frontends/mit-open/src/pages/ListDetailsPage/UserListDetailsPage.tsx
Labels: Needs Review, Waiting on author

#1308 Extract department info for mitxonline from correct external API fields
  learning_resources/etl/mitxonline.py
  learning_resources/etl/mitxonline_test.py
  learning_resources/etl/utils.py
  learning_resources/etl/utils_test.py
Labels: Waiting on author

#1312 free section css
  frontends/mit-open/src/page-components/SearchDisplay/SearchDisplay.tsx
Labels: Waiting on author

#1318 Fix channel views test
  channels/views_test.py
Labels: Needs Review

#1296 fix price display and update vertical cards
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.stories.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.stories.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.test.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCardCondensed.stories.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCardCondensed.tsx
  frontends/ol-components/src/components/LearningResourceCard/story_utils.ts
  frontends/ol-components/src/components/LearningResourceCard/utils.test.ts
  frontends/ol-components/src/components/LearningResourceCard/utils.ts
Labels: Needs Review

#1315 fix banner background width
  frontends/mit-open/src/pages/ChannelPage/UnitChannelTemplate.tsx
  frontends/ol-components/src/components/Banner/Banner.tsx
Labels: Needs Review

#1314 Reorder where the testimonial displays in the unit/offeror page to fix spacing and background
  frontends/mit-open/src/page-components/TestimonialDisplay/TestimonialDisplay.tsx
  frontends/mit-open/src/pages/ChannelPage/ChannelPage.tsx
  frontends/mit-open/src/pages/ChannelPage/UnitChannelTemplate.tsx
Labels: Needs Review, product:mit-open

#1305 No prices for archived runs or resources w/out certificates
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
Labels: Needs Review

#1317 Convert durations to ISO8601 format (podcast episodes)
  learning_resources/etl/podcast.py
  learning_resources/etl/podcast_test.py
  learning_resources/etl/utils.py
  learning_resources/etl/utils_test.py
Labels: Waiting on author

#1275 Update topics code for PWT topic mappings
  data_fixtures/migrations/0004_upsert_initial_topic_data.py
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/generated/v1/api.ts
  frontends/mit-open/src/components/RootTopicIcon/RootTopicIcon.test.tsx
  frontends/mit-open/src/components/RootTopicIcon/RootTopicIcon.tsx
  learning_resources/data/README-topics.md
  learning_resources/data/edx-topic-mappings.csv
  learning_resources/data/ocw-topics.yaml
  learning_resources/data/topics.yaml
  learning_resources/data/ucc-topic-mappings.csv
  learning_resources/etl/mit_edx.py
  learning_resources/etl/mit_edx_test.py
  learning_resources/etl/mitxonline.py
  learning_resources/etl/mitxonline_test.py
  learning_resources/etl/ocw.py
  learning_resources/etl/prolearn.py
  learning_resources/etl/prolearn_test.py
  learning_resources/etl/utils.py
  learning_resources/etl/xpro.py
  learning_resources/etl/xpro_test.py
  learning_resources/factories.py
  learning_resources/management/commands/update_topics.py
  learning_resources/migrations/0058_add_icon_uuid_and_mappings_to_topics.py
  learning_resources/models.py
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  learning_resources/test_utils.py
  learning_resources/utils.py
  learning_resources/utils_test.py
  openapi/specs/v0.yaml
  openapi/specs/v1.yaml
  test_json/test_topic_update.almost-yaml
  test_json/test_topics.yaml
  testimonials/views_test.py
Labels: product:mit-open, Waiting on author

#1321 Fix podcast duration frontend display
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSection.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.test.tsx
Labels: Waiting on author

#1322 Remap topic icons according to what's in the topics listing
  frontends/mit-open/src/components/RootTopicIcon/RootTopicIcon.test.tsx
  frontends/mit-open/src/components/RootTopicIcon/RootTopicIcon.tsx
Labels: Needs Review, product:mit-open

#1310 Moves all env vars to global APP_SETTINGS
  frontends/README.md
  frontends/api/jest.config.ts
  frontends/api/src/axios.ts
  frontends/api/src/clients.ts
  frontends/api/src/test-utils/urls.ts
  frontends/api/src/types/settings.d.ts
  frontends/jest.jsdom.config.ts
  frontends/mit-open/.storybook/main.ts
  frontends/mit-open/jest.config.ts
  frontends/mit-open/src/App.tsx
  frontends/mit-open/src/AppProviders.test.tsx
  frontends/mit-open/src/AppProviders.tsx
  frontends/mit-open/src/common/urls.test.ts
  frontends/mit-open/src/common/urls.ts
  frontends/mit-open/src/page-components/Footer/Footer.tsx
  frontends/mit-open/src/page-components/LearningResourceDrawer/LearningResourceDrawer.test.tsx
  frontends/mit-open/src/page-components/LearningResourceDrawer/LearningResourceDrawer.tsx
  frontends/mit-open/src/page-components/SignupPopover/SignupPopover.tsx
  frontends/mit-open/src/pages/AboutPage/AboutPage.tsx
  frontends/mit-open/src/pages/LearningPathListingPage/LearningPathListingPage.test.tsx
  frontends/mit-open/src/pages/PrivacyPage/PrivacyPage.tsx
  frontends/mit-open/src/pages/UserListListingPage/UserListListingPage.test.tsx
  frontends/mit-open/src/types/settings.d.ts
  frontends/mit-open/webpack.config.js
  frontends/ol-ckeditor/jest.config.ts
  frontends/ol-ckeditor/src/components/cloudServices.test.ts
  frontends/ol-ckeditor/src/components/cloudServices.ts
  frontends/ol-ckeditor/src/types/settings.d.ts
  frontends/ol-components/jest.config.ts
  frontends/ol-components/src/components/EmbedlyCard/util.ts
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.tsx
  frontends/ol-components/src/constants/imgConfigs.ts
  frontends/ol-utilities/src/components/MITLogoLink.tsx
  frontends/ol-utilities/src/components/MetaTags.tsx
  frontends/ol-utilities/src/types/settings.d.ts
  frontends/ol-widgets/jest.config.ts
  frontends/package.json
  package.json
Labels: Needs Review

#1326 urlencode search_filter
  channels/plugins.py
  channels/plugins_test.py
  learning_resources/management/commands/backpopulate_resource_channels.py
Labels: Needs Review

#1328 Remove some styling for topic box names so they wrap, adjusting icons
  frontends/mit-open/src/components/RootTopicIcon/RootTopicIcon.test.tsx
  frontends/mit-open/src/components/RootTopicIcon/RootTopicIcon.tsx
  frontends/mit-open/src/pages/HomePage/BrowseTopicsSection.tsx
Labels: Needs Review, product:mit-open

#1316 styling and icon updates
  frontends/mit-open/src/components/RootTopicIcon/RootTopicIcon.tsx
  frontends/mit-open/src/page-components/ChannelDetails/ChannelDetails.tsx
  frontends/mit-open/src/page-components/Header/Header.tsx
  frontends/mit-open/src/page-components/Header/MenuButton.tsx
  frontends/mit-open/src/pages/DashboardPage/DashboardPage.tsx
  frontends/ol-components/src/components/NavDrawer/NavDrawer.tsx
Labels: Needs Review

#1301 Resource availability: backend changes
  frontends/api/src/generated/v1/api.ts
  learning_resources/constants.py
  learning_resources/etl/deduplication.py
  learning_resources/etl/deduplication_test.py
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/etl/micromasters.py
  learning_resources/etl/micromasters_test.py
  learning_resources/etl/mitxonline.py
  learning_resources/etl/mitxonline_test.py
  learning_resources/etl/ocw.py
  learning_resources/etl/openedx.py
  learning_resources/etl/openedx_test.py
  learning_resources/etl/podcast.py
  learning_resources/etl/podcast_test.py
  learning_resources/etl/prolearn.py
  learning_resources/etl/prolearn_test.py
  learning_resources/etl/utils.py
  learning_resources/etl/utils_test.py
  learning_resources/etl/xpro.py
  learning_resources/etl/xpro_test.py
  learning_resources/etl/youtube.py
  learning_resources/etl/youtube_test.py
  learning_resources/factories.py
  learning_resources/migrations/0046_learningresource_certification.py
  learning_resources/migrations/0059_learningresource_availability.py
  learning_resources/migrations/0060_partially_populate_availability.py
  learning_resources/models.py
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  openapi/specs/v1.yaml
  test_json/mitxonline_courses.json
  test_json/mitxonline_programs.json
Labels: Waiting on author

#1309 tab widths
  frontends/mit-open/src/page-components/SearchDisplay/ResourceCategoryTabs.tsx
  frontends/mit-open/src/page-components/SearchDisplay/SearchDisplay.tsx
Labels: Waiting on author

#1295 Add subscription confirmation dialog on unit pages
  frontends/mit-open/src/page-components/ArticleUpsertForm/ArticleUpsertForm.tsx
  frontends/mit-open/src/page-components/Dialogs/AddToListDialog.tsx
  frontends/mit-open/src/page-components/ManageListDialogs/ManageListDialogs.tsx
  frontends/mit-open/src/page-components/SearchSubscriptionToggle/SearchSubscriptionToggle.test.tsx
  frontends/mit-open/src/page-components/SearchSubscriptionToggle/SearchSubscriptionToggle.tsx
  frontends/mit-open/src/pages/ArticleUpsertPages/ArticleEditPage.test.tsx
  frontends/mit-open/src/pages/ChannelPage/ChannelPage.tsx
  frontends/mit-open/src/pages/ChannelPage/DefaultChannelTemplate.tsx
  frontends/mit-open/src/pages/ChannelPage/UnitChannelTemplate.tsx
  frontends/ol-components/src/components/BasicDialog/BasicDialog.stories.tsx
  frontends/ol-components/src/components/Dialog/Dialog.stories.tsx
  frontends/ol-components/src/components/Dialog/Dialog.tsx
  frontends/ol-components/src/index.ts
Labels: Blocked

#1330 add default yearly_decay_percent
  frontends/mit-open/src/page-components/SearchDisplay/SearchDisplay.tsx
  learning_resources_search/api.py
  learning_resources_search/serializers.py
  openapi/specs/v1.yaml
Labels: Waiting on author

#1335 Assign mitxonline certificate type from api values
  learning_resources/etl/mitxonline.py
  learning_resources/etl/mitxonline_test.py
  test_json/mitxonline_courses.json
  test_json/mitxonline_programs.json
Labels: Needs Review

#1332 Avoid course overwrites in program ETL pipelines
  learning_resources/etl/constants.py
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/etl/pipelines.py
  learning_resources/etl/pipelines_test.py
Labels: Needs Review

#1325 Updated designs for the unit page
  data_fixtures/migrations/0005_unit_page_copy_updates.py
  frontends/mit-open/src/pages/UnitsListingPage/UnitCard.tsx
  frontends/mit-open/src/pages/UnitsListingPage/UnitsListingPage.tsx
Labels: Needs Review

#1333 dev mode for search
  frontends/api/src/generated/v1/api.ts
  learning_resources_search/api.py
  learning_resources_search/api_test.py
  learning_resources_search/constants.py
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
  learning_resources_search/views.py
  openapi/specs/v1.yaml
Labels: Needs Review

#1343 Flatten OCW topics so all of them get mapped to PWT topics when running the ETL pipeline
  learning_resources/etl/ocw.py
  learning_resources/etl/utils.py
Labels: product:mit-open, Waiting on author

#1334 topic / privacy / onboarding / profile copy updates
  data_fixtures/migrations/0006_update_parent_topic_channel_descriptions.py
  frontends/api/src/generated/v0/api.ts
  frontends/mit-open/src/common/profile.tsx
  frontends/mit-open/src/pages/ChannelPage/DefaultChannelTemplate.tsx
  frontends/mit-open/src/pages/DepartmentListingPage/DepartmentListingPage.tsx
  frontends/mit-open/src/pages/HomePage/PersonalizeSection.tsx
  frontends/mit-open/src/pages/PrivacyPage/PrivacyPage.tsx
  frontends/mit-open/src/pages/TopicListingPage/TopicsListingPage.tsx
  frontends/ol-components/src/components/Banner/Banner.tsx
  openapi/specs/v0.yaml
  profiles/migrations/0031_alter_profile_goals.py
  profiles/models.py
Labels: Needs Review

#1342 Handle alternate unique id fields better in load_course
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
Labels: Waiting on author

#1336 Show "Start Anytime" based on resource "availability" property
  frontends/mit-open/.storybook/main.ts
  frontends/mit-open/.storybook/preview-head.html
  frontends/ol-components/src/components/Card/Card.test.tsx
  frontends/ol-components/src/components/Card/Card.tsx
  frontends/ol-components/src/components/Card/ListCard.test.tsx
  frontends/ol-components/src/components/Card/ListCard.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.stories.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.test.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.stories.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.test.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.tsx
  frontends/ol-components/src/components/LearningResourceCard/story_utils.ts
  frontends/ol-components/src/components/LearningResourceCard/utils.ts
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.stories.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.test.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.tsx
  frontends/ol-utilities/src/date/format.ts
Labels: Needs Review
