Repository mitodl/mit-learn, pull requests merged in 2024-10, with the labels that each got.

#1622 updated header
  frontends/mit-learn/public/images/mit-learn-logo.svg
  frontends/mit-learn/public/images/mit-logo-black.svg
  frontends/mit-learn/public/images/mit-logo-color.svg
  frontends/mit-learn/public/images/mit-logo-learn-white.svg
  frontends/mit-learn/public/images/mit-logo-transparent2.svg
  frontends/mit-learn/public/images/mit-logo-transparent3.svg
  frontends/mit-learn/public/images/mit-logo-transparent4.svg
  frontends/mit-learn/public/images/mit-logo-transparent5.jpg
  frontends/mit-learn/public/images/mit-logo-transparent5.png
  frontends/mit-learn/public/images/mit-logo-transparent5.svg
  frontends/mit-learn/public/images/mit-logo-white.svg
  frontends/mit-learn/src/page-components/Footer/Footer.test.tsx
  frontends/mit-learn/src/page-components/Footer/Footer.tsx
  frontends/mit-learn/src/page-components/Header/Header.tsx
  frontends/mit-learn/src/page-components/Header/MenuButton.tsx
  frontends/mit-learn/src/page-components/Header/UserMenu.tsx
  frontends/mit-learn/src/page-components/MITLogoLink/MITLogoLink.tsx
  frontends/ol-components/src/components/Banner/Banner.stories.tsx
  frontends/ol-components/src/components/NavDrawer/NavDrawer.tsx
  frontends/ol-components/src/components/ThemeProvider/colors.ts
  frontends/ol-components/src/types/theme.d.ts
  frontends/ol-utilities/src/components/MITLogoLink.tsx
  frontends/ol-utilities/src/components/index.ts
  frontends/ol-utilities/src/index.ts
Labels: Needs Review

#1619 Email for saved searches
  learning_resources_search/models.py
  learning_resources_search/models_test.py
  learning_resources_search/tasks.py
  learning_resources_search/tasks_test.py
  main/settings_celery.py
Labels: Waiting on author

#1615 Retry recreate_index subtasks on worker exit
  docker-compose.apps.yml
  learning_resources_search/tasks.py
Labels: Waiting on author

#1631 fix Safari MIT logo bug
  frontends/mit-learn/src/GlobalStyles.tsx
  frontends/mit-learn/src/page-components/Header/UserMenu.tsx
Labels: Waiting on author

#1633 fix units page cards in Safari
  frontends/mit-learn/src/pages/UnitsListingPage/UnitsListingPage.tsx
Labels: Needs Review, Waiting on author

#1636 remove border and shadow
  frontends/mit-learn/src/page-components/Header/Header.tsx
  frontends/mit-learn/src/page-components/Header/MenuButton.tsx
Labels: Waiting on author

#1635 raise SystemExit as a RetryError
  learning_resources_search/tasks.py
  learning_resources_search/tasks_test.py
Labels: Needs Review

#1628 "unfollow" confirmation modal and "Unfollow All" button
  frontends/mit-learn/src/pages/DashboardPage/SettingsPage.test.tsx
  frontends/mit-learn/src/pages/DashboardPage/SettingsPage.tsx
Labels: Needs Review

#1627 add is_incomplete_or_stale to the search index
  learning_resources/factories.py
  learning_resources_search/api_test.py
  learning_resources_search/constants.py
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
Labels: Waiting on author

#1639 Restore nextjs main workspace tests
  frontends/jest.jsdom.config.ts
  frontends/main/jest.config.ts
  frontends/main/src/app-pages/ProgramLetterPage/[id]/view/ProgramLetter.test.tsx
  frontends/ol-test-utilities/src/filemocks/imagemock.js
Labels: Needs Review

#1638 updating email template with new logo
  data_fixtures/migrations/0015_unit_page_copy_updates.py
  frontends/mit-learn/public/images/mit-block-logo.jpg
  frontends/mit-learn/public/images/mit-learn-logo.jpg
  frontends/mit-learn/public/images/mit-logo-learn.jpg
  main/templates/email/email_base.html
  main/templates/email/subscribed_channel_digest.html
Labels: Waiting on author

#1647 reset search page in SearchField
  frontends/mit-learn/src/page-components/SearchField/SearchField.tsx
  frontends/mit-learn/src/pages/ChannelPage/ChannelSearch.test.tsx
  frontends/mit-learn/src/pages/ChannelPage/ChannelSearch.tsx
  frontends/mit-learn/src/pages/SearchPage/SearchPage.test.tsx
  frontends/mit-learn/src/pages/SearchPage/SearchPage.tsx
  frontends/ol-components/package.json
  frontends/ol-components/src/components/SearchInput/SearchInput.test.tsx
  frontends/ol-components/src/components/SearchInput/SearchInput.tsx
  frontends/ol-components/src/index.ts
  yarn.lock
Labels: Needs Review

#1644 Adds PostHog back into the NextJS build
  frontends/main/next.config.js
  frontends/main/src/app/providers.tsx
  frontends/main/src/components/ConfiguredPostHogProvider/ConfiguredPostHogProvider.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawer.test.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawer.tsx
  frontends/main/validateEnv.js
Labels: Needs Review, product:mit-open

#1634 Adds base infra for the Unified Ecommerce frontend
  frontends/mit-learn/src/common/feature_flags.ts
  frontends/mit-learn/src/common/urls.ts
  frontends/mit-learn/src/page-components/EcommerceFeature/EcommerceFeature.tsx
  frontends/mit-learn/src/pages/EcommercePages/CartPage.test.tsx
  frontends/mit-learn/src/pages/EcommercePages/CartPage.tsx
  frontends/mit-learn/src/pages/EcommercePages/README.md
  frontends/mit-learn/src/routes.tsx
Labels: product:mit-open, Waiting on author

#1642 set default minimum score cutoff
  frontends/mit-learn/webpack.config.js
  main/settings.py
Labels: Needs Review

#1641 add is_incomplete_or_stale to default sort
  learning_resources_search/api.py
  learning_resources_search/api_test.py
Labels: Needs Review

#1652 instructor search mode
  learning_resources_search/api.py
  learning_resources_search/api_test.py
  learning_resources_search/constants.py
Labels: Waiting on author

#1658 update og-image with new logo
  frontends/mit-learn/public/images/learn-og-image.jpg
  frontends/mit-learn/src/page-components/MetaTags/MetaTags.tsx
Labels: Waiting on author

#1654 Ignore NotFoundErrors in switch_indices function
  learning_resources_search/indexing_api.py
  learning_resources_search/indexing_api_test.py
Labels: Needs Review

#1653 Shanbady/randomize featured resources
  frontends/api/src/generated/v1/api.ts
  frontends/api/src/hooks/learningResources/index.test.ts
  frontends/api/src/hooks/learningResources/keyFactory.ts
  frontends/api/src/test-utils/factories/learningResources.ts
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  learning_resources/views.py
  learning_resources/views_test.py
  openapi/specs/v1.yaml
Labels: Waiting on author

#1661 Cached department and topic page counts
  frontends/mit-learn/src/common/utils.ts
  frontends/mit-learn/src/pages/DepartmentListingPage/DepartmentListingPage.test.tsx
  frontends/mit-learn/src/pages/DepartmentListingPage/DepartmentListingPage.tsx
  frontends/mit-learn/src/pages/OnboardingPage/OnboardingPage.tsx
  frontends/mit-learn/src/pages/TopicListingPage/TopicsListingPage.test.tsx
  frontends/mit-learn/src/pages/TopicListingPage/TopicsListingPage.tsx
  frontends/mit-learn/src/pages/UnitsListingPage/UnitsListingPage.tsx
Labels: Needs Review

#1604 Add location field, populate for Sloan courses
  frontends/api/src/generated/v1/api.ts
  learning_resources/etl/constants.py
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/etl/sloan.py
  learning_resources/etl/sloan_test.py
  learning_resources/migrations/0070_learningresource_location.py
  learning_resources/models.py
  learning_resources/serializers_test.py
  learning_resources_search/constants.py
  openapi/specs/v1.yaml
Labels: Needs Review

#1660 Always delete past events during ETL, and filter them out from api results too just in case
  news_events/etl/conftest.py
  news_events/etl/loaders.py
  news_events/etl/loaders_test.py
  news_events/factories.py
  news_events/views.py
  news_events/views_test.py
Labels: Needs Review

#1626 Next.js Migration Bug Fixes
  frontends/api/src/test-utils/factories/learningResources.ts
  frontends/main/src/app-pages/ChannelPage/ChannelPage.test.tsx
  frontends/main/src/app-pages/ChannelPage/ChannelPage.tsx
  frontends/main/src/app-pages/ChannelPage/ChannelSearch.test.tsx
  frontends/main/src/app-pages/DepartmentListingPage/DepartmentListingPage.test.tsx
  frontends/main/src/app-pages/DepartmentListingPage/DepartmentListingPage.tsx
  frontends/main/src/app-pages/HomePage/BrowseTopicsSection.tsx
  frontends/main/src/app-pages/OnboardingPage/OnboardingPage.tsx
  frontends/main/src/app-pages/SearchPage/SearchPage.test.tsx
  frontends/main/src/app-pages/TopicsListingPage/TopicsListingPage.test.tsx
  frontends/main/src/app-pages/TopicsListingPage/TopicsListingPage.tsx
  frontends/main/src/app-pages/UnitsListingPage/UnitCard.tsx
  frontends/main/src/components/ErrorBoundary/ErrorBoundary.tsx
  frontends/main/src/page-components/Header/Header.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawer.test.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawer.tsx
  frontends/main/src/test-utils/index.tsx
  frontends/ol-components/src/components/Button/Button.tsx
  frontends/ol-components/src/components/Card/Card.tsx
  frontends/ol-components/src/components/Card/ListCard.tsx
  frontends/ol-components/src/components/Card/ListCardCondensed.tsx
  frontends/ol-components/src/components/Dialog/Dialog.stories.tsx
  frontends/ol-components/src/components/Link/Link.stories.tsx
  frontends/ol-components/src/components/RoutedDrawer/RoutedDrawer.tsx
  frontends/ol-test-utilities/src/mocks/nextNavigation.test.ts
  frontends/ol-test-utilities/src/mocks/nextNavigation.ts
Labels: Needs Review

#1666 remove unnecessary padding adjustment on Input base styles
  frontends/ol-components/src/components/Input/Input.tsx
Labels: Waiting on author

#1667 content file weight
  frontends/api/src/generated/v1/api.ts
  frontends/mit-learn/src/page-components/SearchDisplay/SearchDisplay.tsx
  learning_resources_search/api.py
  learning_resources_search/api_test.py
  learning_resources_search/constants.py
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
  openapi/specs/v1.yaml
Labels: Waiting on author

#1670 Fix search page hydration error
  frontends/main/src/app/search/page.tsx
Labels: Needs Review

#1643 Restore program letter intercept view
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/generated/v1/api.ts
  openapi/specs/v0.yaml
  openapi/specs/v1.yaml
  profiles/serializers.py
  profiles/urls.py
  profiles/views.py
  profiles/views_test.py
Labels: Waiting on author

#1672 bump course search utils
  frontends/main/package.json
  frontends/ol-test-utilities/src/mocks/nextNavigation.test.ts
  frontends/ol-test-utilities/src/mocks/nextNavigation.ts
  yarn.lock
Labels: Needs Review

#1671 Set metadataBase url
  frontends/main/src/app/page.tsx
  frontends/main/src/common/metadata.ts
Labels: Needs Review

#1646 topic detail banner / subtopic logic revisions
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/hooks/learningResources/keyFactory.ts
  frontends/api/src/test-utils/urls.ts
  frontends/mit-learn/public/images/background_steps.jpeg
  frontends/mit-learn/public/images/background_steps.jpg
  frontends/mit-learn/src/pages/ChannelPage/ChannelPage.test.tsx
  frontends/mit-learn/src/pages/ChannelPage/ChannelPage.tsx
  frontends/mit-learn/src/pages/ChannelPage/ChannelPageTemplate.tsx
  frontends/mit-learn/src/pages/ChannelPage/ChannelSearch.test.tsx
  frontends/mit-learn/src/pages/ChannelPage/DefaultChannelTemplate.tsx
  frontends/mit-learn/src/pages/ChannelPage/EditChannelAppearanceForm.test.tsx
  frontends/mit-learn/src/pages/ChannelPage/EditChannelPage.test.tsx
  frontends/mit-learn/src/pages/ChannelPage/TopicChannelTemplate.tsx
  frontends/mit-learn/src/pages/ChannelPage/UnitChannelTemplate.tsx
  frontends/mit-learn/src/pages/DepartmentListingPage/DepartmentListingPage.tsx
  frontends/mit-learn/src/pages/TopicListingPage/TopicsListingPage.tsx
  frontends/mit-learn/src/pages/UnitsListingPage/UnitsListingPage.tsx
  frontends/ol-components/src/components/Banner/Banner.stories.tsx
  frontends/ol-components/src/components/Banner/Banner.tsx
  frontends/ol-components/src/components/Breadcrumbs/Breadcrumbs.tsx
  frontends/ol-components/src/components/Chips/Chip.stories.tsx
  frontends/ol-components/src/components/ThemeProvider/chips.tsx
  frontends/ol-components/src/types/theme.d.ts
Labels: Needs Review

#1617 Positioning for search utils input close button
  frontends/main/src/page-components/SearchDisplay/SearchDisplay.tsx
  frontends/ol-components/src/components/Alert/Alert.tsx
  frontends/ol-components/src/components/Input/Input.tsx
  yarn.lock
Labels: Needs Review

#1677 Make metadataBase apply to all pages, not just homepage
  frontends/main/src/app/c/[channelType]/[name]/page.tsx
  frontends/main/src/app/layout.tsx
  frontends/main/src/app/page.tsx
  frontends/ol-components/src/index.ts
Labels: Needs Review

#1673 prevent featured course carousel from re-randomizing
  frontends/api/src/hooks/learningResources/index.test.ts
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/hooks/learningResources/keyFactory.ts
Labels: Waiting on author

#1679 Updates when search events are triggered
  frontends/mit-learn/src/page-components/SearchDisplay/SearchDisplay.tsx
  frontends/mit-learn/src/page-components/SearchField/SearchField.tsx
  frontends/mit-learn/src/pages/HomePage/HeroSearch.tsx
  frontends/mit-learn/src/pages/SearchPage/SearchPage.tsx
Labels: product:mit-open, Waiting on author

#1685 fix spacing issues on nextjs branch
  frontends/main/src/app/styled.tsx
  frontends/main/src/page-components/HeroSearch/HeroSearch.tsx
  frontends/ol-components/src/components/Input/Input.tsx
  frontends/ol-components/src/components/ThemeProvider/MITLearnGlobalStyles.tsx
Labels: Waiting on author

#1681 search defaults fix
  app.json
  frontends/api/src/clients.ts
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/hooks/adminSearchParams/index.ts
  frontends/api/src/test-utils/urls.ts
  frontends/mit-learn/jest.config.ts
  frontends/mit-learn/src/page-components/SearchDisplay/SearchDisplay.tsx
  frontends/mit-learn/src/pages/SearchPage/SearchPage.test.tsx
  frontends/mit-learn/webpack.config.js
  frontends/ol-utilities/src/types/settings.d.ts
  learning_resources_search/urls.py
  learning_resources_search/views.py
  main/settings.py
  openapi/specs/v0.yaml
Labels: Waiting on author

#1689 Make add to list dialog scrollable
  frontends/mit-learn/src/page-components/Dialogs/AddToListDialog.test.tsx
  frontends/mit-learn/src/page-components/Dialogs/AddToListDialog.tsx
  frontends/ol-components/src/components/Dialog/Dialog.tsx
  frontends/ol-components/src/components/FormDialog/FormDialog.tsx
  frontends/ol-components/src/components/ThemeProvider/ThemeProvider.tsx
Labels: Waiting on author

#1684 Shanbady/consolidate static fixtures
  .devcontainer/devcontainer.json
  data_fixtures/fixtures/departments.json
  data_fixtures/fixtures/offered_by.json
  data_fixtures/fixtures/platforms.json
  data_fixtures/fixtures/schools.json
  data_fixtures/migrations/0001_add_testimonial_data.py
  data_fixtures/migrations/0004_upsert_initial_topic_data.py
  data_fixtures/migrations/0007_topic_mappings_edx_add_programming_coding_to_computer_science.py
  data_fixtures/migrations/0009_topics_update_engineering_add_manufacturing.py
  data_fixtures/migrations/0012_topic_mappings_adjust_sustainable_business_finance_accounting.py
  data_fixtures/migrations/0014_add_department_SP.py
  data_fixtures/utils.py
  learning_resources/etl/prolearn_test.py
  learning_resources/management/commands/update_departments_schools.py
  learning_resources/management/commands/update_offered_by.py
  learning_resources/management/commands/update_platforms.py
  learning_resources/test_utils.py
  learning_resources/utils.py
  learning_resources/utils_test.py
  scripts/run-django-dev.sh
Labels: Needs Review

#1692 increase learning path listing limit to 100
  frontends/mit-learn/src/pages/LearningPathListingPage/LearningPathListingPage.test.tsx
  frontends/mit-learn/src/pages/LearningPathListingPage/LearningPathListingPage.tsx
Labels: Waiting on author

#1690 missing chevrons for admin facets
  frontends/main/src/page-components/SearchDisplay/SearchDisplay.tsx
Labels: Needs Review

#1693 exclude topics with no associated channel in api responses
  learning_resources/views.py
  learning_resources/views_test.py
Labels: Needs Review

#1698 search facet accessibility fixes
  frontends/mit-learn/package.json
  frontends/mit-learn/src/page-components/SearchDisplay/SearchDisplay.tsx
  yarn.lock
Labels: Waiting on author

#1695 Shanbady/xpro logo for all xpro offerings
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.test.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.tsx
Labels: Needs Review

#1699 Shanbady/improve bookmark button label
  frontends/mit-learn/src/page-components/ResourceCard/ResourceCard.test.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.test.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.test.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCardCondensed.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSection.tsx
Labels: Needs Review

#1700 Config to set cache control headers
  frontends/main/next.config.js
  frontends/main/package.json
  yarn.lock
Labels: Needs Review

#1696 NextJS - re-enable program letter tests
  frontends/main/src/app-pages/ProgramLetterPage/[id]/view/ProgramLetter.test.tsx
  frontends/main/src/app-pages/ProgramLetterPage/[id]/view/ProgramLetterPage.tsx
Labels: Needs Review

#1704 Remove unnecessary webpack customizations
  frontends/main/next.config.js
Labels: Needs Review

#1701 NextJS Sentry Integration
  .github/workflows/ci.yml
  frontends/main/.gitignore
  frontends/main/Dockerfile.web
  frontends/main/next.config.js
  frontends/main/package.json
  frontends/main/sentry.client.config.ts
  frontends/main/sentry.edge.config.ts
  frontends/main/sentry.server.config.ts
  frontends/main/src/app-pages/ErrorPage/ErrorPageTemplate.tsx
  frontends/main/src/app-pages/ErrorPage/FallbackErrorPage.tsx
  frontends/main/src/app/error.test.tsx
  frontends/main/src/app/error.tsx
  frontends/main/src/app/global-error.tsx
  frontends/main/src/app/layout.tsx
  frontends/main/src/components/ErrorBoundary/ErrorBoundary.tsx
  frontends/main/src/instrumentation.ts
  yarn.lock
Labels: Needs Review

#1697 Ab/search synonyms
  learning_resources_search/constants.py
  learning_resources_search/indexing_api.py
Labels: Waiting on author

#1709 Updates search_update event tracking to fire later
  frontends/mit-learn/src/page-components/SearchDisplay/SearchDisplay.tsx
Labels: Needs Review, product:mit-open

#1682 Update user profile on login / SCIM
  authentication/backends/ol_open_id_connect.py
  authentication/hooks.py
  authentication/pipeline/user.py
  authentication/pipeline/user_test.py
  learning_resources/plugins.py
  learning_resources/plugins_test.py
  main/settings.py
  profiles/adapters.py
  profiles/plugins.py
  profiles/scim/__init__.py
  profiles/scim/adapters.py
  profiles/scim/filters.py
  profiles/scim/views_test.py
Labels: Waiting on author

#1707 bundle analyzer, fix search page + channel page JS sizes
  frontends/main/next.config.js
  frontends/main/package.json
  yarn.lock
Labels: Needs Review

#1721 Update for Storybook's new home in ol-components
  .github/workflows/publish-pages.yml
Labels: Waiting on author

#1722 Fix path to Storybook build
  .github/workflows/publish-pages.yml
Labels: Waiting on author

#1713 Announce search count for screen readers
  frontends/main/src/app-pages/SearchPage/SearchPage.test.tsx
  frontends/main/src/page-components/SearchDisplay/SearchDisplay.tsx
Labels: Needs Review, Waiting on author

#1730 Search count inside label
  frontends/main/package.json
  frontends/main/src/app-pages/SearchPage/SearchPage.test.tsx
  frontends/main/src/page-components/SearchDisplay/SearchDisplay.tsx
  yarn.lock
Labels: Waiting on author

#1726 Navigation Accessibility
  frontends/main/src/page-components/Header/Header.tsx
  frontends/main/src/page-components/Header/MenuButton.tsx
  frontends/ol-components/src/components/NavDrawer/NavDrawer.test.tsx
  frontends/ol-components/src/components/NavDrawer/NavDrawer.tsx
  frontends/ol-components/src/components/ThemeProvider/ThemeProvider.tsx
  frontends/ol-components/src/index.ts
  frontends/ol-components/src/types/theme.d.ts
Labels: Needs Review

#1738 remove frontends/ol-template
  frontends/ol-template/package.json
  frontends/ol-template/plop-templates/package/jest.config.ts.hbs
  frontends/ol-template/plop-templates/package/package.json.hbs
  frontends/ol-template/plop-templates/package/src/index.ts.hbs
  frontends/ol-template/plop-templates/package/tsconfig.json
  frontends/ol-template/plopfile.js
  frontends/ol-template/src/index.ts
  frontends/ol-template/tsconfig.json
  yarn.lock
Labels: Needs Review

#1749 fix list duplication when editing lists
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  learning_resources/views.py
  learning_resources/views_learningpath_test.py
  learning_resources/views_userlist_test.py
Labels: Waiting on author

#1743 Shanbady/similar resources endpoint
  frontends/api/src/generated/v1/api.ts
  learning_resources/views.py
  learning_resources/views_test.py
  learning_resources_search/api.py
  openapi/specs/v1.yaml
Labels: Needs Review

#1739 Replace plain <a> tags with Next.js <Link> components
  frontends/main/src/common/urls.ts
  frontends/main/src/page-components/Footer/Footer.tsx
  frontends/main/src/page-components/Header/Header.tsx
  frontends/ol-components/src/components/NavDrawer/NavDrawer.test.tsx
  frontends/ol-components/src/components/NavDrawer/NavDrawer.tsx
Labels: Needs Review

#1753 remove learning_path from search
  learning_resources/serializers.py
  learning_resources/views.py
  learning_resources/views_learningpath_test.py
  learning_resources_search/api_test.py
  learning_resources_search/connection_test.py
  learning_resources_search/constants.py
Labels: Waiting on author

#1765 Add the ol-profile openid scope to auth
  main/settings.py
Labels: Needs Review

#1767 Handle dupe prices during migration
  learning_resources/migrations/0071_learningresourceprice.py
Labels: Waiting on author

#1770 adding fix for pruning percolate queries
  learning_resources_search/utils.py
Labels: Needs Review, Waiting on author

#1773 fix intermittent failure for flaky test
  learning_resources/views_test.py
Labels: Needs Review

#1775 Fix prolearn bug for existing resources whose urls have changed
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
Labels: Needs Review

#1778 Card Accessibility Improvements
  frontends/main/src/app-pages/HomePage/HomePage.test.tsx
  frontends/main/src/app-pages/HomePage/NewsEventsSection.tsx
  frontends/main/src/page-components/UserListCard/UserListCardCondensed.tsx
  frontends/ol-components/src/components/Card/Card.test.tsx
  frontends/ol-components/src/components/Card/Card.tsx
  frontends/ol-components/src/components/Card/ListCard.test.tsx
  frontends/ol-components/src/components/Card/ListCard.tsx
  frontends/ol-components/src/components/Card/ListCardCondensed.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.test.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.test.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCardCondensed.tsx
Labels: Needs Review

#1751 move facets first in tab order
  frontends/main/src/app-pages/ChannelPage/ChannelPage.test.tsx
  frontends/main/src/app-pages/SearchPage/SearchPage.test.tsx
  frontends/main/src/page-components/SearchDisplay/SearchDisplay.tsx
Labels: Needs Review

#1737 Change frontend to use resource_prices field instead of prices field
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.stories.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.stories.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.test.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCardCondensed.stories.tsx
  frontends/ol-components/src/components/LearningResourceCard/testUtils.ts
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.stories.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.test.tsx
  frontends/ol-utilities/package.json
  frontends/ol-utilities/src/learning-resources/pricing.test.ts
  frontends/ol-utilities/src/learning-resources/pricing.ts
  yarn.lock
Labels: Needs Review

#1711 add new learning resource drawer layout
  frontends/main/src/common/feature_flags.ts
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawer.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV1.test.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV1.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV2.test.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV2.tsx
  frontends/ol-components/src/components/EmbedlyCard/EmbedlyCard.tsx
  frontends/ol-components/src/components/LearningResourceCard/testUtils.ts
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSectionV1.test.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSectionV1.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSectionV2.test.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSectionV2.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.stories.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpandedV1.test.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpandedV1.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpandedV2.test.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpandedV2.tsx
  frontends/ol-components/src/components/RoutedDrawer/RoutedDrawer.tsx
  frontends/ol-components/src/index.ts
  frontends/ol-utilities/src/learning-resources/learning-resources.ts
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/etl/youtube.py
  learning_resources/etl/youtube_test.py
  main/templates/email/email_base.html
  main/templates/email/subscribed_channel_digest.html
Labels: Needs Review

#1777 Fix issue with hero image causing horizontal scroll
  frontends/main/src/app-pages/HomePage/HomePage.tsx
  frontends/main/src/page-components/HeroSearch/HeroSearch.tsx
Labels: Waiting on author
