Repository mitodl/mit-learn, pull requests merged in 2024-05, with the labels that each got.

#830 Remove pytz
  learning_resources/etl/posthog.py
  learning_resources/factories.py
  poetry.lock
  pyproject.toml
Labels: Waiting on author

#842 Alert handler for percolate matches
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/hooks.py
  learning_resources/utils.py
  learning_resources/utils_test.py
  learning_resources/views_learningpath_test.py
  learning_resources_search/api.py
  learning_resources_search/api_test.py
  learning_resources_search/indexing_api.py
  learning_resources_search/plugins.py
  learning_resources_search/plugins_test.py
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
  learning_resources_search/signals.py
  learning_resources_search/tasks.py
  learning_resources_search/utils.py
  learning_resources_search/views.py
  learning_resources_search/views_test.py
Labels: Waiting on author

#854 allow configuring Axios defaults.withCredentials
  .env.example
  app.json
  frontends/api/jest.config.ts
  frontends/api/src/axios.ts
  frontends/api/src/types/settings.d.ts
  frontends/mit-open/webpack.config.js
  frontends/ol-utilities/src/types/settings.d.ts
Labels: Needs Review

#863 configure api BASE_PATH
  .env.example
  app.json
  frontends/api/jest.config.ts
  frontends/api/src/clients.ts
  frontends/api/src/types/settings.d.ts
  frontends/mit-open/webpack.config.js
  frontends/ol-utilities/src/types/settings.d.ts
Labels: Needs Review

#846 fix sorting
  frontends/api/src/generated/v1/api.ts
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/hooks/learningResources/keyFactory.ts
  frontends/api/src/test-utils/urls.ts
  frontends/mit-open/src/page-components/TabbedCarousel/TabbedCarousel.test.tsx
  frontends/mit-open/src/page-components/TabbedCarousel/TabbedCarousel.tsx
  frontends/mit-open/src/page-components/TabbedCarousel/types.ts
  frontends/mit-open/src/pages/HomePage/HomePage.test.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.tsx
  learning_resources/constants.py
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/filters.py
  learning_resources/filters_test.py
  learning_resources/migrations/0045_learningresource_next_start_date.py
  learning_resources/models.py
  learning_resources/serializers_test.py
  learning_resources/tasks.py
  learning_resources/tasks_test.py
  learning_resources/views.py
  learning_resources/views_test.py
  learning_resources_search/api_test.py
  learning_resources_search/constants.py
  main/settings_celery.py
  openapi/specs/v1.yaml
Labels: Needs Review

#867 create exported components bundle
  .github/workflows/ci.yml
  .gitignore
  README.md
  frontends/.eslintrc.js
  frontends/mit-open/package.json
  frontends/mit-open/src/ExportedComponentProviders.tsx
  frontends/mit-open/src/ExportedComponents.tsx
  frontends/mit-open/src/page-components/LearningResourceCard/AddToListDialog.tsx
  frontends/mit-open/tsconfig.json
  frontends/mit-open/webpack.exports.js
  main/settings.py
  yarn.lock
Labels: Needs Review

#877 only show clear all if it would do something
  frontends/mit-open/package.json
  frontends/mit-open/src/pages/SearchPage/SearchPage.test.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.tsx
  yarn.lock
Labels: Needs Review

#865 Departments Listing Page
  frontends/api/src/clients.ts
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/hooks/learningResources/keyFactory.ts
  frontends/api/src/test-utils/factories/learningResources.ts
  frontends/api/src/test-utils/mockAxios.ts
  frontends/api/src/test-utils/urls.ts
  frontends/mit-open/package.json
  frontends/mit-open/public/images/background_steps.jpeg
  frontends/mit-open/src/common/urls.ts
  frontends/mit-open/src/components/CardRowList/CardRowList.tsx
  frontends/mit-open/src/pages/DepartmentListingPage/DepartmentListingPage.test.tsx
  frontends/mit-open/src/pages/DepartmentListingPage/DepartmentListingPage.tsx
  frontends/mit-open/src/pages/FieldPage/FieldSearch.tsx
  frontends/mit-open/src/pages/LearningPathListingPage/LearningPathListingPage.tsx
  frontends/mit-open/src/pages/ListDetailsPage/ItemsListing.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.tsx
  frontends/mit-open/src/pages/UserListListingPage/UserListListingPage.tsx
  frontends/mit-open/src/routes.tsx
  frontends/ol-components/src/components/Lists/ListItemLink.tsx
  frontends/ol-components/src/components/PlainList/PlainList.stories.tsx
  frontends/ol-components/src/components/PlainList/PlainList.tsx
  frontends/ol-components/src/components/ThemeProvider/chips.tsx
  frontends/ol-components/src/components/ThemeProvider/typography.ts
  frontends/ol-components/src/index.ts
  frontends/ol-components/src/types/typography.d.ts
  main/urls.py
  yarn.lock
Labels: Needs Review

#880 fix spacing between department groups
  frontends/mit-open/src/pages/DepartmentListingPage/DepartmentListingPage.tsx
  frontends/ol-components/src/components/PlainList/PlainList.tsx
Labels: Waiting on author

#883 allow Button to hold a ref
  frontends/ol-components/src/components/Button/Button.tsx
Labels: Waiting on author

#862 Add certificate as a real database field to LearningResource
  frontends/api/src/generated/v1/api.ts
  learning_resources/etl/mitxonline.py
  learning_resources/etl/mitxonline_test.py
  learning_resources/etl/openedx.py
  learning_resources/etl/openedx_test.py
  learning_resources/etl/prolearn.py
  learning_resources/etl/prolearn_test.py
  learning_resources/etl/utils.py
  learning_resources/etl/utils_test.py
  learning_resources/etl/xpro.py
  learning_resources/etl/xpro_test.py
  learning_resources/migrations/0046_learningresource_certification.py
  learning_resources/models.py
  learning_resources/models_test.py
  openapi/specs/v1.yaml
Labels: Needs Review

#885 Apply free filter to all resources
  learning_resources/filters.py
  learning_resources/filters_test.py
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
Labels: Waiting on author

#888 Add Format as a facet to the search page
  frontends/mit-open/package.json
  frontends/mit-open/src/pages/SearchPage/SearchPage.test.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.tsx
  yarn.lock
Labels: Needs Review

#884 Fix n+1 queries
  learning_resources/models.py
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  learning_resources/views_test.py
Labels: Waiting on author

#894 Do not show unpublished runs in learning resource serializer data
  learning_resources/etl/loaders.py
  learning_resources/serializers.py
  learning_resources/serializers_test.py
Labels: Needs Review

#896 Replace react-dotdotdot with CSS
  frontends/mit-open/package.json
  frontends/mit-open/src/page-components/CardTemplate/CardTemplate.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.tsx
  frontends/ol-components/src/components/TruncateText/TruncateText.mdx
  frontends/ol-components/src/components/TruncateText/TruncateText.stories.tsx
  frontends/ol-components/src/components/TruncateText/TruncateText.tsx
  frontends/ol-components/src/index.ts
  yarn.lock
Labels: Needs Review

#878 Shanbady/add subscribe button to pages
  frontends/api/src/clients.ts
  frontends/api/src/generated/v1/api.ts
  frontends/api/src/hooks/searchSubscription/index.ts
  frontends/api/src/hooks/searchSubscription/keyFactory.ts
  frontends/api/src/test-utils/factories/index.ts
  frontends/api/src/test-utils/factories/percolateQueries.ts
  frontends/api/src/test-utils/urls.ts
  frontends/mit-open/src/page-components/SearchSubscriptionToggle/SearchSubscriptionToggle.tsx
  frontends/mit-open/src/pages/FieldPage/EditFieldPage.test.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPage.test.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPageSkeleton.tsx
  frontends/mit-open/src/pages/FieldPage/FieldSearch.test.tsx
  frontends/mit-open/src/pages/UserListListingPage/UserListListingPage.test.tsx
  frontends/ol-ckeditor/jest.config.ts
  frontends/ol-ckeditor/src/types/settings.d.ts
  frontends/ol-components/package.json
  learning_resources_search/views.py
  learning_resources_search/views_test.py
  openapi/specs/v1.yaml
  yarn.lock
Labels: Needs Review

#889 use neue-haas-grotesk font
  frontends/.eslintrc.js
  frontends/mit-open/.storybook/preview-head.html
  frontends/mit-open/public/index.html
  frontends/mit-open/src/components/FieldAvatar/FieldAvatar.test.tsx
  frontends/mit-open/src/components/FieldAvatar/FieldAvatar.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.tsx
  frontends/ol-components/src/components/Button/Button.tsx
  frontends/ol-components/src/components/Input/Input.tsx
  frontends/ol-components/src/components/ThemeProvider/typography.ts
  frontends/ol-components/src/types/typography.d.ts
Labels: Needs Review

#887 Featured API endpoint
  docker-compose-notebook.yml
  frontends/api/src/generated/v1/api.ts
  learning_resources/constants.py
  learning_resources/factories.py
  learning_resources/filters.py
  learning_resources/filters_test.py
  learning_resources/management/commands/populate_featured_lists.py
  learning_resources/urls.py
  learning_resources/views.py
  learning_resources/views_test.py
  openapi/specs/v1.yaml
Labels: Needs Review

#899 Null start dates for OCW course runs
  learning_resources/etl/ocw.py
  learning_resources/etl/ocw_test.py
  learning_resources/migrations/0048_null_ocw_start_dates.py
  learning_resources/utils.py
  learning_resources/utils_test.py
Labels: Waiting on author

#891 Adds learner testimonials support
  frontends/api/src/generated/v0/api.ts
  main/settings.py
  main/urls.py
  openapi/specs/v0.yaml
  testimonials/__init__.py
  testimonials/admin.py
  testimonials/apps.py
  testimonials/factories.py
  testimonials/filters.py
  testimonials/migrations/0001_add_attestation_table.py
  testimonials/migrations/__init__.py
  testimonials/models.py
  testimonials/serializers.py
  testimonials/urls.py
  testimonials/utils.py
  testimonials/utils_test.py
  testimonials/views.py
  testimonials/views_test.py
Labels: product:mit-open, Waiting on author

#890 navigation menu
  frontends/mit-open/src/GlobalStyles.tsx
  frontends/mit-open/src/common/urls.ts
  frontends/mit-open/src/page-components/Header/Header.tsx
  frontends/mit-open/src/page-components/Header/MenuButton.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.tsx
  frontends/ol-components/src/components/NavDrawer/NavDrawer.stories.tsx
  frontends/ol-components/src/components/NavDrawer/NavDrawer.test.tsx
  frontends/ol-components/src/components/NavDrawer/NavDrawer.tsx
  frontends/ol-components/src/components/RoutedDrawer/RoutedDrawer.tsx
  frontends/ol-components/src/components/learning-resources/ExpandedLearningResourceDisplay/ExpandedLearningResourceDisplay.stories.tsx
  frontends/ol-components/src/index.ts
Labels: Needs Review

#906 Fix 500 error loading attestations without a cover image
  frontends/api/src/generated/v0/api.ts
  openapi/specs/v0.yaml
  testimonials/serializers.py
Labels: product:mit-open, Waiting on author

#909 Use our ActionButton, no more MUI IconButton
  frontends/mit-open/src/components/FieldMenu/FieldMenu.test.tsx
  frontends/mit-open/src/components/FieldMenu/FieldMenu.tsx
  frontends/mit-open/src/page-components/LearningResourceCard/LearningResourceCard.tsx
  frontends/mit-open/src/pages/ArticleDetailsPage/ArticleDetailsPage.tsx
  frontends/mit-open/src/pages/ErrorPage/ErrorPageTemplate.tsx
  frontends/mit-open/src/pages/LearningPathListingPage/LearningPathListingPage.tsx
  frontends/mit-open/src/pages/ListDetailsPage/ListDetailsPage.tsx
  frontends/mit-open/src/pages/UserListListingPage/UserListListingPage.tsx
  frontends/ol-components/package.json
  frontends/ol-components/src/components/BasicDialog/BasicDialog.tsx
  frontends/ol-components/src/components/Button/Button.mdx
  frontends/ol-components/src/components/Button/Button.stories.tsx
  frontends/ol-components/src/components/Button/Button.tsx
  frontends/ol-components/src/components/ButtonLink/ButtonLink.mdx
  frontends/ol-components/src/components/ButtonLink/ButtonLink.stories.tsx
  frontends/ol-components/src/components/ButtonLink/ButtonLink.tsx
  frontends/ol-components/src/components/Carousel/Carousel.test.tsx
  frontends/ol-components/src/components/Carousel/Carousel.tsx
  frontends/ol-components/src/components/FilledIconButton/FilledIconButton.tsx
  frontends/ol-components/src/components/FormDialog/FormDialog.tsx
  frontends/ol-components/src/components/RoutedDrawer/RoutedDrawer.test.tsx
  frontends/ol-components/src/components/RoutedDrawer/RoutedDrawer.tsx
  frontends/ol-components/src/index.ts
  yarn.lock
Labels: Needs Review

#895 Fix schema generation warnings errors
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  Dockerfile
  channels/migrations/0006_remove_channel_type_default.py
  channels/models.py
  channels/schema.py
  channels/serializers.py
  channels/serializers_test.py
  channels/views_test.py
  ckeditor/serializers.py
  ckeditor/urls.py
  ckeditor/views.py
  ckeditor/views_test.py
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/generated/v1/api.ts
  frontends/mit-open/src/pages/FieldPage/EditFieldAppearanceForm.tsx
  frontends/ol-ckeditor/src/components/cloudServices.test.ts
  frontends/ol-ckeditor/src/components/cloudServices.ts
  learning_resources/urls.py
  learning_resources/views.py
  learning_resources_search/views.py
  openapi/management/commands/generate_openapi_spec.py
  openapi/specs/v0.yaml
  openapi/specs/v1.yaml
  profiles/serializers.py
  profiles/urls.py
  profiles/views.py
  profiles/views_test.py
  scripts/openapi-configs/typescript-axios-v0.yaml
  scripts/openapi-configs/typescript-axios-v1.yaml
  scripts/test/openapi_spec_check.sh
  testimonials/views.py
  widgets/serializers/widget_instance.py
Labels: Waiting on author

#892 Give video/podcast/learning_path resources a default learning format of ["online"]
  learning_resources/etl/loaders_test.py
  learning_resources/migrations/0049_alter_learning_format.py
  learning_resources/models.py
Labels: Waiting on author

#914 adding fix for program letter route in nginx
  config/nginx.conf
Labels: Needs Review

#920 Fix schema issue that was breaking redoc
  channels/schema.py
  frontends/api/src/generated/v0/api.ts
  openapi/specs/v0.yaml
Labels: Waiting on author

#919 Fix schema documentation for news_events feed items
  frontends/api/src/generated/v0/api.ts
  news_events/apps.py
  news_events/schema.py
  openapi/specs/v0.yaml
Labels: Needs Review

#911 serve react app on 40x errors
  .github/workflows/ci.yml
  main/settings.py
  main/templates/index.html
  main/views.py
  poetry.lock
  pyproject.toml
  scripts/test/python_tests.sh
Labels: Waiting on author

#936 Use `profiles` to enable running frontend on host, simplify `watch` setup.
  .env.example
  .secrets.baseline
  README.md
  docker-compose.yml
  frontends/Dockerfile
  frontends/README.md
Labels: Waiting on author

#917 Add Free, Certification, and Professional Facets to Search UI
  frontends/mit-open/package.json
  frontends/mit-open/src/pages/FieldPage/FieldSearch.tsx
  frontends/mit-open/src/pages/FieldPage/FieldSearchFacetDisplay.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.test.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.tsx
  yarn.lock
Labels: Needs Review

#939 Fix several ETL bugs
  learning_resources/etl/mitxonline.py
  learning_resources/etl/mitxonline_test.py
  learning_resources/etl/pipelines.py
  learning_resources/etl/pipelines_test.py
Labels: Waiting on author

#907 Update profile API with onboarding data fields
  .pre-commit-config.yaml
  .secrets.baseline
  frontends/api/src/generated/v0/api.ts
  openapi/specs/v0.yaml
  profiles/admin.py
  profiles/forms.py
  profiles/migrations/0025_add_onboarding_fields.py
  profiles/models.py
  profiles/serializers.py
  profiles/serializers_test.py
  profiles/views_test.py
Labels: Waiting on author

#910 header updates
  frontends/github-pages/src/Header.tsx
  frontends/mit-open/public/images/mit-logo-transparent4.svg
  frontends/mit-open/src/GlobalStyles.tsx
  frontends/mit-open/src/page-components/Header/Header.test.tsx
  frontends/mit-open/src/page-components/Header/Header.tsx
  frontends/mit-open/src/page-components/Header/MenuButton.tsx
  frontends/mit-open/src/page-components/Header/UserMenu.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.tsx
  frontends/ol-components/src/components/NavDrawer/NavDrawer.tsx
  frontends/ol-components/src/components/SimpleMenu/SimpleMenu.tsx
  frontends/ol-components/src/index.ts
  frontends/ol-utilities/src/components/MITLogoLink.tsx
Labels: Needs Review

#942 fix install and storybook
  docker-compose.yml
Labels: Waiting on author

#923 Additional offeror details
  channels/serializers.py
  channels/serializers_test.py
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/generated/v1/api.ts
  frontends/api/src/test-utils/factories/fields.ts
  frontends/api/src/test-utils/factories/learningResources.ts
  frontends/mit-open/src/pages/SearchPage/SearchPage.test.tsx
  learning_resources/fixtures/offered_by.json
  learning_resources/migrations/0050_offeror_details.py
  learning_resources/models.py
  learning_resources/serializers.py
  learning_resources/views.py
  learning_resources/views_test.py
  openapi/specs/v0.yaml
  openapi/specs/v1.yaml
Labels: Needs Review

#951 side nav updates
  frontends/mit-open/public/images/navdrawer/certificate.svg
  frontends/mit-open/public/images/navdrawer/course_materials.svg
  frontends/mit-open/public/images/navdrawer/courses.svg
  frontends/mit-open/public/images/navdrawer/departments.svg
  frontends/mit-open/public/images/navdrawer/free.svg
  frontends/mit-open/public/images/navdrawer/new.svg
  frontends/mit-open/public/images/navdrawer/pathways.svg
  frontends/mit-open/public/images/navdrawer/popular.svg
  frontends/mit-open/public/images/navdrawer/programs.svg
  frontends/mit-open/public/images/navdrawer/provider.svg
  frontends/mit-open/public/images/navdrawer/topics.svg
  frontends/mit-open/public/images/navdrawer/upcoming.svg
  frontends/mit-open/src/page-components/Header/Header.tsx
  frontends/mit-open/src/page-components/Header/MenuButton.tsx
  frontends/ol-components/src/components/NavDrawer/NavDrawer.test.tsx
  frontends/ol-components/src/components/NavDrawer/NavDrawer.tsx
Labels: Needs Review

#945 Homepage News and Events section
  frontends/api/src/clients.ts
  frontends/api/src/hooks/newsEvents/index.ts
  frontends/api/src/hooks/newsEvents/keyFactory.ts
  frontends/api/src/test-utils/factories/index.ts
  frontends/api/src/test-utils/factories/newsEvents.ts
  frontends/api/src/test-utils/urls.ts
  frontends/mit-open/src/pages/HomePage/BrowseTopicsSection.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.test.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.tsx
  frontends/mit-open/src/pages/HomePage/NewsEventsSection.tsx
Labels: Needs Review

#954 Fix flaky test
  learning_resources/migrations/0051_instructor_sort.py
  learning_resources/models.py
Labels: Needs Review

#948 Filtering by free=true should exclude all professional courses
  frontends/api/src/generated/v1/api.ts
  learning_resources/filters.py
  learning_resources/filters_test.py
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  learning_resources/views_test.py
  learning_resources_search/api_test.py
  learning_resources_search/constants.py
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
  openapi/specs/v1.yaml
Labels: Waiting on author

#937 daily subscription email to subscribers
  frontends/api/src/generated/v1/api.ts
  frontends/mit-open/src/page-components/SearchSubscriptionToggle/SearchSubscriptionToggle.tsx
  frontends/mit-open/src/pages/FieldPage/EditFieldPage.test.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPage.test.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPageSkeleton.tsx
  frontends/mit-open/src/pages/FieldPage/FieldSearch.test.tsx
  learning_resources/factories.py
  learning_resources_search/api.py
  learning_resources_search/factories.py
  learning_resources_search/migrations/0004_alter_percolatequery_source_type.py
  learning_resources_search/models.py
  learning_resources_search/serializers.py
  learning_resources_search/tasks.py
  learning_resources_search/tasks_test.py
  learning_resources_search/views.py
  main/settings.py
  main/settings_celery.py
  main/templates/email/email_base.html
  main/templates/email/subscribed_channel_digest.html
  openapi/specs/v1.yaml
  profiles/utils.py
Labels: Waiting on author

#922 workflow changes to publish static assets to s3
  .github/workflows/production.yml
  .github/workflows/release-candidate.yml
Labels: DevOps, enhancement, product:mit-open, Waiting on author

#959 Featured Courses Carousel
  frontends/api/src/clients.ts
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/hooks/learningResources/keyFactory.ts
  frontends/api/src/test-utils/urls.ts
  frontends/mit-open/src/page-components/TabbedCarousel/TabbedCarousel.tsx
  frontends/mit-open/src/page-components/TabbedCarousel/types.ts
  frontends/mit-open/src/pages/HomePage/FeaturedResourcesSection.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.test.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.tsx
  frontends/mit-open/src/pages/HomePage/UpcomingCoursesSection.tsx
Labels: Needs Review

#965 Fix a flaky test
  learning_resources/factories.py
  learning_resources/views_test.py
Labels: Waiting on author

#966 Featured Courses: add All tab
  frontends/mit-open/src/pages/HomePage/FeaturedResourcesSection.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.test.tsx
Labels: Needs Review

#955 Do not ingest prolearn courses/programs from the past
  learning_resources/etl/prolearn.py
  learning_resources/etl/prolearn_test.py
  test_json/prolearn_csail_programs.json
  test_json/prolearn_mitpe_courses.json
Labels: Waiting on author

#946 Topics Listing Page
  frontends/api/src/test-utils/factories/learningResources.ts
  frontends/github-pages/src/style.css
  frontends/mit-open/jest.config.ts
  frontends/mit-open/package.json
  frontends/mit-open/src/GlobalStyles.tsx
  frontends/mit-open/src/common/urls.ts
  frontends/mit-open/src/components/RootTopicIcon/RootTopicIcon.test.tsx
  frontends/mit-open/src/components/RootTopicIcon/RootTopicIcon.tsx
  frontends/mit-open/src/page-components/Header/Header.tsx
  frontends/mit-open/src/page-components/LearningResourceCardTemplate/LearningResourceCardTemplate.tsx
  frontends/mit-open/src/pages/DepartmentListingPage/DepartmentListingPage.tsx
  frontends/mit-open/src/pages/HomePage/BrowseTopicsSection.tsx
  frontends/mit-open/src/pages/HomePage/HeroSearch.tsx
  frontends/mit-open/src/pages/TopicListingPage/TopicsListingPage.test.tsx
  frontends/mit-open/src/pages/TopicListingPage/TopicsListingPage.tsx
  frontends/mit-open/src/routes.tsx
  frontends/ol-components/src/components/Banner/Banner.stories.tsx
  frontends/ol-components/src/components/Banner/Banner.tsx
  frontends/ol-components/src/components/Chips/Chip.stories.tsx
  frontends/ol-components/src/components/Chips/ChipLink.tsx
  frontends/ol-components/src/components/Link/Link.stories.tsx
  frontends/ol-components/src/components/Link/Link.tsx
  frontends/ol-components/src/components/RoutedDrawer/RoutedDrawer.stories.tsx
  frontends/ol-components/src/components/ThemeProvider/ThemeProvider.tsx
  frontends/ol-components/src/components/ThemeProvider/chips.tsx
  frontends/ol-components/src/components/ThemeProvider/typography.ts
  frontends/ol-components/src/index.ts
  frontends/ol-components/src/types/theme.d.ts
  package.json
  yarn.lock
Labels: Needs Review

#967 Fix detect-secrets baseline file
  .secrets.baseline
Labels: Waiting on author

#960 Upgrade NukaCarousel to v8
  frontends/jest-shared-setup.ts
  frontends/mit-open/src/page-components/TabbedCarousel/TabbedCarousel.tsx
  frontends/ol-ckeditor/jest.config.ts
  frontends/ol-ckeditor/src/setupJest.ts
  frontends/ol-components/package.json
  frontends/ol-components/src/components/Carousel/Carousel.test.tsx
  frontends/ol-components/src/components/Carousel/Carousel.tsx
  yarn.lock
Labels: product:mit-open, Waiting on author

#952 Adding call to update program topics during ETL loads
  learning_resources/etl/loaders.py
Labels: product:mit-open, Waiting on author

#956 add the footer & privacy, terms and about us pages
  frontends/mit-open/public/images/mit-dome-2.jpg
  frontends/mit-open/public/images/mit-logo-transparent5.svg
  frontends/mit-open/src/GlobalStyles.tsx
  frontends/mit-open/src/common/urls.ts
  frontends/mit-open/src/page-components/Footer/Footer.test.tsx
  frontends/mit-open/src/page-components/Footer/Footer.tsx
  frontends/mit-open/src/pages/AboutPage/AboutPage.test.tsx
  frontends/mit-open/src/pages/AboutPage/AboutPage.tsx
  frontends/mit-open/src/pages/PrivacyPage/PrivacyPage.test.tsx
  frontends/mit-open/src/pages/PrivacyPage/PrivacyPage.tsx
  frontends/mit-open/src/pages/TermsPage/TermsPage.test.tsx
  frontends/mit-open/src/pages/TermsPage/TermsPage.tsx
  frontends/mit-open/src/routes.tsx
  frontends/ol-utilities/src/components/MITLogoLink.tsx
Labels: Waiting on author

#970 Fix Featured API requests
  frontends/mit-open/src/pages/HomePage/FeaturedResourcesSection.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.test.tsx
Labels: Waiting on author

#957 Clean up resource descriptions
  learning_resources/etl/constants.py
  learning_resources/etl/mitxonline.py
  learning_resources/etl/mitxonline_test.py
  learning_resources/etl/ocw.py
  learning_resources/etl/openedx.py
  learning_resources/etl/podcast.py
  learning_resources/etl/podcast_test.py
  learning_resources/etl/prolearn.py
  learning_resources/etl/prolearn_test.py
  learning_resources/etl/utils.py
  learning_resources/etl/utils_test.py
  learning_resources/etl/xpro.py
  learning_resources/etl/youtube.py
  learning_resources/etl/youtube_test.py
Labels: Needs Review

#969 Updated hero page
  frontends/mit-open/public/images/hero_woman.svg
  frontends/mit-open/public/images/person_with_headphones.png
  frontends/mit-open/src/page-components/Header/Header.tsx
  frontends/mit-open/src/pages/HomePage/FeaturedResourcesSection.tsx
  frontends/mit-open/src/pages/HomePage/HeroSearch.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.test.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.tsx
  frontends/ol-components/src/components/Input/Input.tsx
  frontends/ol-components/src/components/ThemeProvider/ThemeProvider.tsx
Labels: Needs Review

#971 Randomize featured api order by offeror, keep sorting by position
  learning_resources/views.py
  learning_resources/views_test.py
Labels: Needs Review

#978 remove package-lock.json
  package-lock.json
Labels: Needs Review

#973 extract images for news articles
  news_events/etl/medium_mit_news.py
  news_events/etl/medium_mit_news_test.py
Labels: Waiting on author

#985 Fix celerybeat schedule
  learning_resources_search/tasks.py
  main/settings_celery.py
Labels: Waiting on author

#986 Error if using npm to install
  .npmrc
  package.json
Labels: Needs Review

#987 CDN Cutover fixes
  .github/workflows/production.yml
  .github/workflows/release-candidate.yml
Labels: DevOps, Needs Review, bug, product:mit-open

#958 Learning resource drawer design updates
  frontends/.eslintrc.js
  frontends/api/src/test-utils/factories/learningResources.ts
  frontends/mit-open/.storybook/main.ts
  frontends/mit-open/public/images/edx_logo.svg
  frontends/mit-open/src/components/RootTopicIcon/RootTopicIcon.test.tsx
  frontends/mit-open/src/page-components/LearningResourceDrawer/LearningResourceDrawer.test.tsx
  frontends/mit-open/src/page-components/LearningResourceDrawer/LearningResourceDrawer.tsx
  frontends/mit-open/src/pages/ErrorPage/ForbiddenPage.test.tsx
  frontends/mit-open/src/pages/ErrorPage/NotFoundPage.test.tsx
  frontends/mit-open/src/pages/HomePage/NewsEventsSection.tsx
  frontends/ol-ckeditor/src/components/CkeditorArticle.test.tsx
  frontends/ol-ckeditor/src/components/CkeditorDisplay.test.tsx
  frontends/ol-components/package.json
  frontends/ol-components/src/components/Carousel/Carousel.test.tsx
  frontends/ol-components/src/components/EmbedlyCard/EmbedlyCard.test.tsx
  frontends/ol-components/src/components/EmbedlyCard/util.test.ts
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSection.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.stories.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.test.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.tsx
  frontends/ol-components/src/components/Logo/Logo.tsx
  frontends/ol-components/src/components/NavDrawer/NavDrawer.tsx
  frontends/ol-components/src/components/RoutedDrawer/RoutedDrawer.tsx
  frontends/ol-components/src/components/SortableList/SortableList.test.tsx
  frontends/ol-components/src/components/learning-resources/ExpandedLearningResourceDisplay/ExpandedLearningResourceDisplay.stories.tsx
  frontends/ol-components/src/components/learning-resources/ExpandedLearningResourceDisplay/ExpandedLearningResourceDisplay.test.tsx
  frontends/ol-components/src/components/learning-resources/ExpandedLearningResourceDisplay/ExpandedLearningResourceDisplay.tsx
  frontends/ol-components/src/index.ts
  frontends/ol-test-utilities/src/domQueries.ts
  frontends/ol-widgets/src/components/Widget-RichText.test.tsx
  frontends/ol-widgets/src/components/Widget.test.tsx
  frontends/ol-widgets/src/components/editing/ManageWidgetDialog-EmbeddedUrl.test.tsx
  frontends/ol-widgets/src/components/editing/ManageWidgetDialog.test.tsx
  frontends/ol-widgets/src/components/editing/WidgetsListEditable.test.tsx
  yarn.lock
Labels: Needs Review

#977 Certification types
  frontends/api/src/generated/v1/api.ts
  learning_resources/constants.py
  learning_resources/etl/micromasters.py
  learning_resources/etl/micromasters_test.py
  learning_resources/etl/mitxonline.py
  learning_resources/etl/mitxonline_test.py
  learning_resources/etl/openedx.py
  learning_resources/etl/openedx_test.py
  learning_resources/etl/prolearn.py
  learning_resources/etl/prolearn_test.py
  learning_resources/etl/xpro.py
  learning_resources/etl/xpro_test.py
  learning_resources/factories.py
  learning_resources/filters.py
  learning_resources/filters_test.py
  learning_resources/migrations/0052_learningresource_certification_type.py
  learning_resources/models.py
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  learning_resources_search/constants.py
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
  openapi/specs/v1.yaml
Labels: Needs Review

#980 search pages code sharing
  frontends/mit-open/src/page-components/SearchDisplay/ResourceTypeTabs.tsx
  frontends/mit-open/src/page-components/SearchDisplay/SearchDisplay.tsx
  frontends/mit-open/src/pages/FieldPage/FieldSearch.tsx
  frontends/mit-open/src/pages/FieldPage/FieldSearchFacetDisplay.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.tsx
Labels: Needs Review
