Repository mitodl/mit-learn, pull requests merged in 2024-03, with the labels that each got.

#559 fix OpenAPI response for content_file_search
  frontends/api/src/generated/api.ts
  learning_resources/serializers.py
  learning_resources_search/serializers.py
  learning_resources_search/views.py
  openapi/specs/v1.yaml
Labels: Waiting on author

#561 Create program certificate django model
  profiles/migrations/0015_programcertificate.py
  profiles/migrations/0016_alter_programcertificate_options.py
  profiles/models.py
  profiles/models_test.py
Labels: Needs Review

#558 Youtube video ETL and search
  app.json
  frontends/api/src/generated/api.ts
  frontends/api/src/test-utils/factories/learningResources.ts
  frontends/ol-utilities/src/learning-resources/learning-resources.ts
  learning_resources/admin.py
  learning_resources/constants.py
  learning_resources/etl/constants.py
  learning_resources/etl/exceptions.py
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/etl/pipelines.py
  learning_resources/etl/youtube.py
  learning_resources/etl/youtube_test.py
  learning_resources/factories.py
  learning_resources/fixtures/platforms.json
  learning_resources/hooks.py
  learning_resources/management/commands/backpopulate_youtube_data.py
  learning_resources/migrations/0039_videos.py
  learning_resources/models.py
  learning_resources/serializers.py
  learning_resources/tasks.py
  learning_resources/tasks_test.py
  learning_resources/utils.py
  learning_resources_search/api_test.py
  learning_resources_search/connection_test.py
  learning_resources_search/constants.py
  learning_resources_search/plugins.py
  learning_resources_search/tasks.py
  main/settings_celery.py
  main/settings_course_etl.py
  openapi/specs/v1.yaml
  poetry.lock
  pyproject.toml
  test_json/youtube/playlistItems.list.2.json
  test_json/youtube/playlistItems.list.3.json
  test_json/youtube/playlists.list.2.json
  test_json/youtube/playlists.list.3.json
  test_json/youtube/videos.list.3.json
  test_json/youtube/videos.list.4.json
Labels: Waiting on author

#583 content file isn't a resource type
  learning_resources_search/api.py
  learning_resources_search/api_test.py
  learning_resources_search/constants.py
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
  learning_resources_search/views.py
  learning_resources_search/views_test.py
Labels: Waiting on author

#585 Add daily micromasters ETL task to celerybeat schedule
  main/settings_celery.py
Labels: Waiting on author

#584 Assign topics to videos and playlists
  learning_resources/admin.py
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/etl/utils.py
  learning_resources/etl/utils_test.py
  learning_resources/hooks.py
  learning_resources/models.py
  learning_resources/utils.py
  learning_resources/utils_test.py
  learning_resources_search/api.py
  learning_resources_search/api_test.py
  learning_resources_search/plugins.py
  learning_resources_search/plugins_test.py
Labels: Needs Review

#595 Type-specific api endpoints for videos and video playlists
  frontends/api/src/generated/api.ts
  learning_resources/etl/loaders_test.py
  learning_resources/factories.py
  learning_resources/urls.py
  learning_resources/views.py
  learning_resources/views_test.py
  openapi/specs/v1.yaml
Labels: Waiting on author

#603 Avoid duplicate courses
  learning_resources/etl/constants.py
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/etl/ocw.py
  learning_resources/etl/prolearn.py
  learning_resources/etl/prolearn_test.py
Labels: Needs Review

#605 Program Letter View
  frontends/api/src/clients.ts
  frontends/api/src/generated/api.ts
  frontends/api/src/hooks/programLetters/index.ts
  frontends/api/src/hooks/programLetters/keyFactory.ts
  frontends/api/src/test-utils/factories/index.ts
  frontends/api/src/test-utils/factories/programLetters.ts
  frontends/api/src/test-utils/urls.ts
  frontends/mit-open/src/common/urls.ts
  frontends/mit-open/src/pages/ProgramLetterPage/ProgramLetter.test.tsx
  frontends/mit-open/src/pages/ProgramLetterPage/ProgramLetterPage.tsx
  frontends/mit-open/src/routes.tsx
  learning_resources/urls.py
  main/settings.py
  main/urls.py
  openapi/specs/v1.yaml
  profiles/factories.py
  profiles/migrations/0017_programletter.py
  profiles/models.py
  profiles/models_test.py
  profiles/serializers.py
  profiles/urls.py
  profiles/utils.py
  profiles/utils_test.py
  profiles/views.py
  profiles/views_test.py
  templates/program_letter.html
Labels: Waiting on author

#608 Endpoint for user program certificate info and program letter links
  frontends/api/src/generated/api.ts
  frontends/api/src/test-utils/factories/programLetters.ts
  openapi/specs/v1.yaml
  profiles/factories.py
  profiles/serializers.py
  profiles/urls.py
  profiles/views.py
  profiles/views_test.py
Labels: Waiting on author

#617 shanbady/separate database router and schema for program certificates
  main/routers.py
  main/routers_test.py
  main/settings.py
  profiles/migrations/0018_alter_programletter_certificate_and_more.py
  profiles/migrations/0019_alter_programcertificate_options_and_more.py
  profiles/models.py
  profiles/models_test.py
  profiles/utils_test.py
  profiles/views_test.py
Labels: Waiting on author

#631 fix for test failure in main
  profiles/views_test.py
Labels: Waiting on author

#618 Add a Search Page
  frontends/api/src/clients.ts
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/hooks/learningResources/keyFactory.ts
  frontends/api/src/test-utils/urls.ts
  frontends/mit-open/package.json
  frontends/mit-open/src/common/urls.ts
  frontends/mit-open/src/components/PlainVerticalList/PlainVerticalList.tsx
  frontends/mit-open/src/page-components/LearningResourceCard/LearningResourceCard.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.test.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.tsx
  frontends/mit-open/src/pages/LearningPathListingPage/LearningPathListingPage.tsx
  frontends/mit-open/src/pages/SearchPage/ResourceTypeTabs.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.test.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.tsx
  frontends/mit-open/src/routes.tsx
  frontends/ol-components/package.json
  frontends/ol-components/src/components/RoutedDrawer/RoutedDrawer.tsx
  frontends/ol-components/src/components/SearchInput/SearchInput.test.tsx
  frontends/ol-components/src/components/SearchInput/SearchInput.tsx
  frontends/ol-components/src/index.ts
  frontends/ol-utilities/package.json
  frontends/ol-utilities/src/hooks/index.ts
  frontends/ol-utilities/src/hooks/useSearchParams.test.tsx
  frontends/ol-utilities/src/hooks/useSearchParams.ts
  yarn.lock
Labels: Waiting on author

#637 Update jest-dom, make TS aware
  package.json
  tsconfig.json
  yarn.lock
Labels: Waiting on author

#639 allow filtering by readable id in the api
  frontends/api/src/generated/api.ts
  learning_resources/filters.py
  learning_resources/filters_test.py
  openapi/specs/v1.yaml
Labels: Waiting on author

#646 Remove all usages of pytz
  learning_resources/etl/deduplication_test.py
  learning_resources/etl/mitxonline.py
  learning_resources/etl/ocw_test.py
  learning_resources/etl/openedx.py
  learning_resources/etl/pipelines_test.py
  learning_resources/etl/podcast_test.py
  learning_resources/etl/prolearn.py
  learning_resources/etl/prolearn_test.py
  learning_resources/etl/utils.py
  learning_resources/etl/utils_test.py
  learning_resources/etl/xpro.py
  learning_resources/etl/youtube_test.py
  learning_resources/factories.py
  learning_resources/management/commands/backpopulate_youtube_data.py
  learning_resources/tasks.py
  learning_resources/utils.py
  learning_resources/utils_test.py
  main/utils.py
  main/utils_test.py
Labels: Waiting on author

#651 generate v0 apis
  .github/workflows/ci.yml
  frontends/api/package.json
  frontends/api/src/clients.ts
  frontends/api/src/generated/v0/.openapi-generator/FILES
  frontends/api/src/generated/v0/.openapi-generator/VERSION
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/generated/v0/base.ts
  frontends/api/src/generated/v0/common.ts
  frontends/api/src/generated/v0/configuration.ts
  frontends/api/src/generated/v0/index.ts
  frontends/api/src/generated/v1/.openapi-generator/FILES
  frontends/api/src/generated/v1/.openapi-generator/VERSION
  frontends/api/src/generated/v1/api.ts
  frontends/api/src/generated/v1/base.ts
  frontends/api/src/generated/v1/common.ts
  frontends/api/src/generated/v1/configuration.ts
  frontends/api/src/generated/v1/index.ts
  frontends/api/src/hooks/articles/index.ts
  frontends/api/src/hooks/articles/keyFactory.ts
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/hooks/learningResources/keyFactory.ts
  frontends/api/src/test-utils/factories/articles.ts
  frontends/api/src/test-utils/factories/programLetters.ts
  frontends/api/src/test-utils/urls.ts
  scripts/generate_openapi.sh
  scripts/openapi-configs/typescript-axios-v0.yaml
  scripts/openapi-configs/typescript-axios-v1.yaml
Labels: Needs Review

#638 News & Events API
  frontends/api/src/generated/v0/api.ts
  learning_resources/filters.py
  learning_resources/views.py
  main/filters.py
  main/urls.py
  news_events/factories.py
  news_events/filters.py
  news_events/filters_test.py
  news_events/serializers.py
  news_events/serializers_test.py
  news_events/urls.py
  news_events/views.py
  news_events/views_test.py
  openapi/specs/v0.yaml
Labels: Waiting on author

#635 fix learningpath invalidation
  frontends/api/src/hooks/learningResources/index.test.ts
  frontends/api/src/hooks/learningResources/index.ts
Labels: Waiting on author

#633 First iteration of field pages
  channels/serializers.py
  frontends/api/src/clients.ts
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/hooks/fields/index.ts
  frontends/api/src/hooks/fields/keyFactory.ts
  frontends/api/src/hooks/widget_lists/index.ts
  frontends/api/src/hooks/widget_lists/keyFactory.ts
  frontends/api/src/test-utils/factories/fields.ts
  frontends/api/src/test-utils/factories/index.ts
  frontends/api/src/test-utils/urls.ts
  frontends/mit-open/src/common/urls.ts
  frontends/mit-open/src/components/FieldAvatar/FieldAvatar.test.tsx
  frontends/mit-open/src/components/FieldAvatar/FieldAvatar.tsx
  frontends/mit-open/src/components/FieldMenu/FieldMenu.test.tsx
  frontends/mit-open/src/components/FieldMenu/FieldMenu.tsx
  frontends/mit-open/src/pages/FieldPage/EditFieldAppearanceForm.test.tsx
  frontends/mit-open/src/pages/FieldPage/EditFieldAppearanceForm.tsx
  frontends/mit-open/src/pages/FieldPage/EditFieldPage.test.tsx
  frontends/mit-open/src/pages/FieldPage/EditFieldPage.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPage.test.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPage.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPageSkeleton.tsx
  frontends/mit-open/src/pages/FieldPage/WidgetsList.test.tsx
  frontends/mit-open/src/pages/FieldPage/WidgetsList.tsx
  frontends/mit-open/src/routes.tsx
  frontends/ol-components/src/index.ts
  main/urls.py
  openapi/specs/v0.yaml
  widgets/serializers/widget_list.py
  widgets/urls.py
  widgets/views_test.py
Labels: Waiting on author

#650 Add userlists page and refactor LearningResourceCardTemplate
  frontends/api/src/clients.ts
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/hooks/learningResources/keyFactory.ts
  frontends/api/src/test-utils/factories/index.ts
  frontends/api/src/test-utils/factories/userLists.ts
  frontends/api/src/test-utils/urls.ts
  frontends/mit-open/src/common/urls.ts
  frontends/mit-open/src/page-components/CardTemplate/CardTemplate.test.tsx
  frontends/mit-open/src/page-components/CardTemplate/CardTemplate.tsx
  frontends/mit-open/src/page-components/Header/UserMenu.tsx
  frontends/mit-open/src/page-components/LearningResourceCard/AddToListDialog.test.tsx
  frontends/mit-open/src/page-components/LearningResourceCard/AddToListDialog.tsx
  frontends/mit-open/src/page-components/LearningResourceCardTemplate/LearningResourceCardTemplate.test.tsx
  frontends/mit-open/src/page-components/LearningResourceCardTemplate/LearningResourceCardTemplate.tsx
  frontends/mit-open/src/page-components/ManageListDialogs/ManageListDialogs.test.tsx
  frontends/mit-open/src/page-components/ManageListDialogs/ManageListDialogs.tsx
  frontends/mit-open/src/page-components/UserListCardTemplate/UserListCardTemplate.test.tsx
  frontends/mit-open/src/page-components/UserListCardTemplate/UserListCardTemplate.tsx
  frontends/mit-open/src/pages/LearningPathDetailsPage/LearningPathDetailsPage.test.ts
  frontends/mit-open/src/pages/LearningPathDetailsPage/LearningPathDetailsPage.tsx
  frontends/mit-open/src/pages/LearningPathListingPage/LearningPathListingPage.test.tsx
  frontends/mit-open/src/pages/LearningPathListingPage/LearningPathListingPage.tsx
  frontends/mit-open/src/pages/UserListListingPage/UserListListingPage.test.tsx
  frontends/mit-open/src/pages/UserListListingPage/UserListListingPage.tsx
  frontends/mit-open/src/routes.tsx
  main/urls.py
Labels: Needs Review, product:mit-open

#653 Shanbady/retrieve environment config
  frontends/mit-open/jest.config.ts
  frontends/mit-open/src/App.tsx
  frontends/mit-open/src/common/constants.ts
  frontends/mit-open/src/test-utils/setupJest.ts
  frontends/mit-open/src/types/settings.d.ts
  frontends/mit-open/webpack.config.js
  frontends/ol-ckeditor/jest.config.ts
  frontends/ol-ckeditor/src/components/cloudServices.test.ts
  frontends/ol-ckeditor/src/components/cloudServices.ts
  frontends/ol-ckeditor/src/setupJest.ts
  frontends/ol-ckeditor/src/types/settings.d.ts
  frontends/ol-utilities/jest.config.ts
  frontends/ol-utilities/src/components/embedly/util.ts
  frontends/ol-utilities/src/types/settings.d.ts
  frontends/ol-widgets/jest.config.ts
  frontends/ol-widgets/src/setupJest.ts
  frontends/ol-widgets/src/types/settings.d.ts
  main/views.py
Labels: Needs Review

#675 Search page cleanup
  frontends/api/src/clients.ts
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/hooks/learningResources/keyFactory.ts
  frontends/api/src/test-utils/factories/learningResources.ts
  frontends/api/src/test-utils/urls.ts
  frontends/mit-open/package.json
  frontends/mit-open/src/components/CardRowList/CardRowList.tsx
  frontends/mit-open/src/components/PlainVerticalList/PlainVerticalList.tsx
  frontends/mit-open/src/pages/SearchPage/ResourceTypeTabs.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.test.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.tsx
  frontends/ol-components/src/components/ThemeProvider/ThemeProvider.tsx
  frontends/ol-components/src/index.ts
  yarn.lock
Labels: Needs Review

#679 Sloan Executive Education blog ETL
  app.json
  main/settings_celery.py
  news_events/etl/conftest.py
  news_events/etl/loaders.py
  news_events/etl/loaders_test.py
  news_events/etl/medium_mit_news_test.py
  news_events/etl/pipelines.py
  news_events/etl/pipelines_test.py
  news_events/etl/sloan_exec_news.py
  news_events/etl/sloan_exec_news_test.py
  news_events/management/commands/backpopulate_news_events.py
  news_events/migrations/0002_alter_feeditem_guid.py
  news_events/models.py
  news_events/tasks.py
  news_events/tasks_test.py
  test_json/test_sloan_exec_news.json
Labels: Waiting on author

#647 Shanbady/endpoint to retrieve session data
  openapi/specs/v0.yaml
  profiles/serializers.py
  profiles/serializers_test.py
  profiles/urls.py
  profiles/views_test.py
Labels: Needs Review

#688 updating openapi spec
  frontends/api/src/generated/v0/api.ts
Labels: Needs Review

#684 Ab/fix new upcoming
  learning_resources/views.py
  learning_resources/views_test.py
Labels: Waiting on author

#682 Add Posthog integration to backend
  .env.example
  app.json
  main/apps.py
  main/features.py
  main/features_test.py
  main/permissions.py
  main/settings.py
  main/urls.py
  main/views.py
  poetry.lock
  pyproject.toml
  scripts/heroku-release-phase.sh
Labels: product:mit-open, Waiting on author

#691 Add UserListDetails page
  frontends/api/package.json
  frontends/api/src/common/constants.ts
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/test-utils/factories/learningResources.ts
  frontends/api/src/test-utils/factories/userLists.ts
  frontends/mit-open/src/common/urls.ts
  frontends/mit-open/src/page-components/UserListCardTemplate/UserListCardTemplate.tsx
  frontends/mit-open/src/pages/LearningPathDetailsPage/ItemsListing.test.tsx
  frontends/mit-open/src/pages/LearningPathDetailsPage/LearningPathDetailsPage.tsx
  frontends/mit-open/src/pages/ListDetailsPage/ItemsListing.test.tsx
  frontends/mit-open/src/pages/ListDetailsPage/ItemsListing.tsx
  frontends/mit-open/src/pages/ListDetailsPage/LearningPathDetailsPage.tsx
  frontends/mit-open/src/pages/ListDetailsPage/ListDetailsPage.test.ts
  frontends/mit-open/src/pages/ListDetailsPage/ListDetailsPage.tsx
  frontends/mit-open/src/pages/ListDetailsPage/UserListDetailsPage.tsx
  frontends/mit-open/src/pages/UserListListingPage/UserListListingPage.tsx
  frontends/mit-open/src/routes.tsx
Labels: Needs Review, product:mit-open

#692 Add botocore to ignored deprecation warnings, remove old python 3.7 ignore line
  fixtures/common.py
Labels: Needs Review, Waiting on author
