Repository mitodl/mit-learn, pull requests merged in 2024-06, with the labels that each got.

#984 Reduce functions occurring under atomic transactions; fix dedupe comparison in load_course function
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
Labels: Waiting on author

#989 Sortby parameter for news_events
  frontends/api/src/generated/v0/api.ts
  frontends/mit-open/src/pages/HomePage/HomePage.test.tsx
  frontends/mit-open/src/pages/HomePage/NewsEventsSection.tsx
  news_events/constants.py
  news_events/filters.py
  news_events/filters_test.py
  openapi/specs/v0.yaml
Labels: Waiting on author

#991 Add "tertiary" button and align button terminology with Figma
  frontends/mit-open/src/page-components/ArticleUpsertForm/ArticleUpsertForm.tsx
  frontends/mit-open/src/page-components/Header/Header.tsx
  frontends/mit-open/src/page-components/Header/UserMenu.tsx
  frontends/mit-open/src/page-components/LearningResourceCard/LearningResourceCard.tsx
  frontends/mit-open/src/page-components/SearchSubscriptionToggle/SearchSubscriptionToggle.tsx
  frontends/mit-open/src/pages/ArticleDetailsPage/ArticleDetailsPage.tsx
  frontends/mit-open/src/pages/ErrorPage/ErrorPageTemplate.tsx
  frontends/mit-open/src/pages/HomePage/BrowseTopicsSection.tsx
  frontends/mit-open/src/pages/LearningPathListingPage/LearningPathListingPage.tsx
  frontends/mit-open/src/pages/UserListListingPage/UserListListingPage.tsx
  frontends/ol-components/src/components/BasicDialog/BasicDialog.tsx
  frontends/ol-components/src/components/Button/Button.mdx
  frontends/ol-components/src/components/Button/Button.stories.tsx
  frontends/ol-components/src/components/Button/Button.tsx
  frontends/ol-components/src/components/Carousel/Carousel.tsx
  frontends/ol-components/src/components/FormDialog/FormDialog.tsx
  frontends/ol-components/src/components/ThemeProvider/Typography.stories.tsx
  frontends/ol-widgets/src/components/editing/ManageWidgetDialog.tsx
  frontends/ol-widgets/src/components/editing/WidgetsListEditable.tsx
Labels: Needs Review

#974 units page
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/generated/v1/api.ts
  frontends/mit-open/public/images/unit_logos/bootcamps.svg
  frontends/mit-open/public/images/unit_logos/mitpe.svg
  frontends/mit-open/public/images/unit_logos/mitx.svg
  frontends/mit-open/public/images/unit_logos/ocw.svg
  frontends/mit-open/public/images/unit_logos/see.svg
  frontends/mit-open/public/images/unit_logos/xpro.svg
  frontends/mit-open/src/common/urls.ts
  frontends/mit-open/src/page-components/Header/Header.tsx
  frontends/mit-open/src/pages/UnitsListingPage/UnitsListingPage.test.tsx
  frontends/mit-open/src/pages/UnitsListingPage/UnitsListingPage.tsx
  frontends/mit-open/src/routes.tsx
  learning_resources/fixtures/offered_by.json
  learning_resources/migrations/0052_learningresourceofferor_description.py
  learning_resources/migrations/0053_merge_20240531_1657.py
  learning_resources/migrations/0054_rename_description_learningresourceofferor_value_prop.py
  learning_resources/models.py
  openapi/specs/v0.yaml
  openapi/specs/v1.yaml
Labels: Waiting on author

#975 Shanbady/additional details on offeror channel pages
  frontends/mit-open/src/page-components/ChannelDetails/ChannelDetails.test.tsx
  frontends/mit-open/src/page-components/ChannelDetails/ChannelDetails.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPageSkeleton.tsx
  frontends/ol-components/src/components/BannerPage/BannerPage.tsx
  frontends/ol-components/src/index.ts
Labels: Needs Review

#1003 Update profile fields to align to LR data
  frontends/api/src/generated/v0/api.ts
  openapi/specs/v0.yaml
  profiles/apps.py
  profiles/factories.py
  profiles/forms.py
  profiles/migrations/0026_onboarding_lr_fields.py
  profiles/models.py
  profiles/schema.py
  profiles/serializers.py
  profiles/serializers_test.py
  profiles/views_test.py
Labels: Needs Review

#1006 Add nullalbe offerors and channels to the testimonials model/API
  frontends/api/src/generated/v0/api.ts
  openapi/specs/v0.yaml
  testimonials/filters.py
  testimonials/migrations/0002_add_offeror_to_testimonials.py
  testimonials/models.py
Labels: product:mit-open, Waiting on author

#1011 Absolute URL to backend for login routes
  frontends/api/src/test-utils/urls.ts
  frontends/mit-open/jest.config.ts
  frontends/mit-open/src/common/urls.test.ts
  frontends/mit-open/src/common/urls.ts
  frontends/mit-open/src/page-components/Header/Header.test.tsx
Labels: Needs Review

#1005 professional toggle
  frontends/mit-open/src/page-components/SearchDisplay/ProfessionalToggle.tsx
  frontends/mit-open/src/page-components/SearchDisplay/SearchDisplay.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.test.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.tsx
  frontends/ol-components/src/index.ts
Labels: Needs Review

#1012 Style tab components to match figma
  frontends/ol-components/src/components/Button/Button.tsx
  frontends/ol-components/src/components/TabButtons/TabButtonList.mdx
  frontends/ol-components/src/components/TabButtons/TabButtonList.stories.tsx
  frontends/ol-components/src/components/TabButtons/TabButtonList.tsx
  frontends/ol-components/src/index.ts
Labels: Needs Review

#964 Add onboarding UX
  authentication/pipeline/user.py
  frontends/api/src/clients.ts
  frontends/api/src/hooks/profile/index.ts
  frontends/api/src/test-utils/factories/index.ts
  frontends/api/src/test-utils/factories/profiles.ts
  frontends/api/src/test-utils/mockAxios.ts
  frontends/api/src/test-utils/urls.ts
  frontends/jest-shared-setup.ts
  frontends/mit-open/src/common/urls.ts
  frontends/mit-open/src/pages/OnboardingPage/CertificateStep.tsx
  frontends/mit-open/src/pages/OnboardingPage/EducationLevelStep.tsx
  frontends/mit-open/src/pages/OnboardingPage/GoalsStep.tsx
  frontends/mit-open/src/pages/OnboardingPage/LearningFormatStep.tsx
  frontends/mit-open/src/pages/OnboardingPage/OnboardingPage.test.tsx
  frontends/mit-open/src/pages/OnboardingPage/OnboardingPage.tsx
  frontends/mit-open/src/pages/OnboardingPage/Prompt.tsx
  frontends/mit-open/src/pages/OnboardingPage/TimeCommitmentStep.tsx
  frontends/mit-open/src/pages/OnboardingPage/TopicInterestsStep.tsx
  frontends/mit-open/src/pages/OnboardingPage/types.ts
  frontends/mit-open/src/routes.tsx
  frontends/ol-components/src/components/ChoiceBox/ChoiceBox.tsx
  frontends/ol-components/src/index.ts
  frontends/package.json
  frontends/tsconfig.json
  main/settings.py
  main/settings_pluggy.py
  profiles/plugins.py
  profiles/views.py
  yarn.lock
Labels: Waiting on author

#1016 Add channel links to unit cards
  frontends/mit-open/src/pages/UnitsListingPage/UnitsListingPage.test.tsx
  frontends/mit-open/src/pages/UnitsListingPage/UnitsListingPage.tsx
Labels: Waiting on author

#992 Insert learning_path_parents/user_list_parents values into search results
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
Labels: Waiting on author

#1018 Add certification_type to search facets UI
  frontends/mit-open/package.json
  frontends/mit-open/src/pages/FieldPage/FieldSearch.test.tsx
  frontends/mit-open/src/pages/FieldPage/FieldSearch.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.test.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.tsx
  yarn.lock
Labels: Needs Review

#1015 Learning Resource Card
  frontends/mit-open/.storybook/main.ts
  frontends/mit-open/.storybook/preview-head.html
  frontends/mit-open/src/ExportedComponents.tsx
  frontends/mit-open/src/page-components/CardTemplate/CardTemplate.tsx
  frontends/mit-open/src/page-components/Dialogs/AddToListDialog.test.tsx
  frontends/mit-open/src/page-components/Dialogs/AddToListDialog.tsx
  frontends/mit-open/src/page-components/LearningResourceCard/LearningResourceCard.test.tsx
  frontends/mit-open/src/page-components/LearningResourceCard/LearningResourceCard.tsx
  frontends/mit-open/src/page-components/LearningResourceDrawer/LearningResourceDrawer.tsx
  frontends/mit-open/src/page-components/SearchDisplay/SearchDisplay.tsx
  frontends/mit-open/src/page-components/TabbedCarousel/TabbedCarousel.tsx
  frontends/mit-open/src/page-components/TabbedCarousel/types.ts
  frontends/mit-open/src/pages/ErrorPage/ErrorPageTemplate.tsx
  frontends/mit-open/src/pages/HomePage/FeaturedResourcesSection.tsx
  frontends/mit-open/src/pages/HomePage/HomePageCarousel.tsx
  frontends/mit-open/src/pages/HomePage/MediaSection.tsx
  frontends/mit-open/src/pages/HomePage/NewsEventsSection.tsx
  frontends/mit-open/src/pages/LearningPathListingPage/LearningPathListingPage.tsx
  frontends/mit-open/src/pages/UnitsListingPage/UnitsListingPage.tsx
  frontends/mit-open/src/pages/UserListListingPage/UserListListingPage.tsx
  frontends/ol-components/src/components/Button/Button.stories.tsx
  frontends/ol-components/src/components/Button/Button.tsx
  frontends/ol-components/src/components/Card/Card.stories.tsx
  frontends/ol-components/src/components/Card/Card.tsx
  frontends/ol-components/src/components/Carousel/Carousel.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.stories.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.test.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.tsx
  frontends/ol-components/src/components/ThemeProvider/ThemeProvider.tsx
  frontends/ol-components/src/constants/imgConfigs.ts
  frontends/ol-components/src/index.ts
  frontends/ol-widgets/src/components/Widget.tsx
Labels: Needs Review

#1024 Fix bug with onboarding steps not saving
  frontends/mit-open/src/pages/OnboardingPage/OnboardingPage.tsx
Labels: Needs Review

#1017 Profile-based search filter preferences
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/test-utils/factories/profiles.ts
  openapi/specs/v0.yaml
  profiles/factories.py
  profiles/serializers.py
  profiles/serializers_test.py
  profiles/views_test.py
Labels: Waiting on author

#1008 OLL contentfiles
  fixtures/aws.py
  learning_resources/etl/edx_shared.py
  learning_resources/etl/edx_shared_test.py
  learning_resources/etl/utils.py
  learning_resources/management/commands/backpopulate_oll_files.py
  learning_resources/tasks.py
  learning_resources/tasks_test.py
  main/settings_celery.py
  main/settings_course_etl.py
Labels: Needs Review

#916 Add learner testimonials homepage UI
  frontends/api/src/clients.ts
  frontends/api/src/hooks/testimonials/index.test.ts
  frontends/api/src/hooks/testimonials/index.ts
  frontends/api/src/hooks/testimonials/keyFactory.ts
  frontends/api/src/test-utils/factories/index.ts
  frontends/api/src/test-utils/factories/testimonials.ts
  frontends/api/src/test-utils/urls.ts
  frontends/mit-open/package.json
  frontends/mit-open/src/GlobalStyles.tsx
  frontends/mit-open/src/page-components/TabbedCarousel/types.ts
  frontends/mit-open/src/pages/HomePage/HomePage.test.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.tsx
  frontends/mit-open/src/pages/HomePage/TestimonialsSection.tsx
  frontends/ol-components/src/components/Button/Button.tsx
  frontends/ol-components/src/components/Carousel/Carousel.tsx
  frontends/ol-components/src/index.ts
  yarn.lock
Labels: product:mit-open

#1020 Carousel Makeover: New tabs and Fixed Width Cards
  frontends/mit-open/src/page-components/ResourceCarousel/ResourceCarousel.test.tsx
  frontends/mit-open/src/page-components/ResourceCarousel/ResourceCarousel.tsx
  frontends/mit-open/src/page-components/ResourceCarousel/types.ts
  frontends/mit-open/src/page-components/TabbedCarousel/TabbedCarousel.tsx
  frontends/mit-open/src/pages/HomePage/FeaturedResourcesSection.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.test.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.tsx
  frontends/mit-open/src/pages/HomePage/MediaSection.tsx
  frontends/mit-open/src/pages/HomePage/UpcomingCoursesSection.tsx
  frontends/mit-open/src/pages/HomePage/carousels.ts
  frontends/ol-components/package.json
  frontends/ol-components/src/components/Carousel/Carousel.stories.tsx
  frontends/ol-components/src/components/Carousel/Carousel.test.tsx
  frontends/ol-components/src/components/Carousel/Carousel.tsx
  frontends/ol-components/src/components/ThemeProvider/ThemeProvider.tsx
  frontends/ol-components/src/index.ts
  yarn.lock
Labels: Needs Review

#1026 mitxonline etl v2 api
  learning_resources/etl/mitxonline.py
  learning_resources/etl/mitxonline_test.py
  test_json/mitxonline_courses.json
  test_json/mitxonline_programs.json
Labels: Waiting on author

#1030 Add backpopulate command for user profiles
  profiles/management/commands/backpopulate_profiles.py
Labels: Waiting on author

#1032 Add a setting for CSRF_COOKIE_DOMAIN
  app.json
  main/settings.py
Labels: Needs Review

#1009 dashboard menu
  frontends/mit-open/public/images/user_menu_background.svg
  frontends/mit-open/src/pages/DashboardPage/Dashboard.test.tsx
  frontends/mit-open/src/pages/DashboardPage/DashboardPage.tsx
  frontends/mit-open/src/pages/ListDetailsPage/LearningPathDetailsPage.tsx
  frontends/mit-open/src/pages/ListDetailsPage/ListDetailsPage.tsx
  frontends/mit-open/src/pages/ListDetailsPage/UserListDetailsPage.tsx
  frontends/mit-open/src/pages/UserListListingPage/UserListListingPage.test.tsx
  frontends/mit-open/src/pages/UserListListingPage/UserListListingPage.tsx
  frontends/mit-open/src/routes.tsx
  frontends/ol-components/src/index.ts
Labels: Needs Review

#1039 Fixing authentication issue, and fixing some filtering and test issues
  frontends/api/src/generated/v0/api.ts
  openapi/specs/v0.yaml
  testimonials/filters.py
  testimonials/views.py
  testimonials/views_test.py
Labels: product:mit-open, Waiting on author

#1042 adding configurable csrf settings and including withXSRFToken in axio…
  frontends/api/src/axios.ts
  main/settings.py
Labels: Needs Review, SSO

#1034 homepage hero bug fixes
  frontends/mit-open/src/GlobalStyles.tsx
  frontends/mit-open/src/pages/HomePage/HeroSearch.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.tsx
  frontends/ol-components/src/components/Input/Input.tsx
  frontends/ol-components/src/components/ThemeProvider/chips.tsx
Labels: Needs Review

#1056 search prefs learning format as list
  frontends/api/src/generated/v0/api.ts
  openapi/specs/v0.yaml
  profiles/serializers.py
  profiles/serializers_test.py
  profiles/views_test.py
Labels: Needs Review

#1048 Carousel: Align loading and loaded card sizes
  frontends/mit-open/src/page-components/ResourceCarousel/ResourceCarousel.test.tsx
  frontends/mit-open/src/page-components/ResourceCarousel/ResourceCarousel.tsx
Labels: Needs Review

#1052 Absolute login return URL
  .github/workflows/ci.yml
  docker-compose.yml
  frontends/api/src/clients.ts
  frontends/api/src/hooks/testimonials/index.test.ts
  frontends/api/src/test-utils/urls.ts
  frontends/mit-open/jest.config.ts
  frontends/mit-open/package.json
  frontends/mit-open/src/common/urls.test.ts
  frontends/mit-open/src/common/urls.ts
  frontends/mit-open/webpack.config.js
  package.json
Labels: Needs Review

#1053 Copies static assets to the root build directory
  frontends/mit-open/public/logo192.png
  frontends/mit-open/public/logo512.png
  frontends/mit-open/webpack.config.js
Labels: Needs Review

#1031 Change channel type and url from "offeror" to "unit"
  channels/constants.py
  channels/factories.py
  channels/migrations/0007_alter_channel_type.py
  channels/migrations/0008_rename_offerordetail_unitdetail.py
  channels/models.py
  channels/plugins.py
  channels/plugins_test.py
  channels/serializers.py
  channels/serializers_test.py
  channels/views.py
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/test-utils/factories/fields.ts
  frontends/mit-open/src/page-components/ChannelDetails/ChannelDetails.test.tsx
  frontends/mit-open/src/page-components/ChannelDetails/ChannelDetails.tsx
  frontends/mit-open/src/pages/FieldPage/EditFieldAppearanceForm.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPageSkeleton.tsx
  frontends/mit-open/src/pages/FieldPage/FieldSearch.test.tsx
  frontends/mit-open/src/pages/FieldPage/FieldSearch.tsx
  frontends/mit-open/src/pages/UnitsListingPage/UnitsListingPage.test.tsx
  frontends/mit-open/src/pages/UnitsListingPage/UnitsListingPage.tsx
  learning_resources/management/commands/backpopulate_resource_channels.py
  learning_resources/management/commands/populate_featured_lists.py
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  learning_resources/views.py
  learning_resources/views_test.py
  openapi/specs/v0.yaml
Labels: Needs Review

#1059 Add featured courses carousel to unit channel page
  frontends/mit-open/src/common/utils.test.ts
  frontends/mit-open/src/common/utils.ts
  frontends/mit-open/src/page-components/SearchSubscriptionToggle/SearchSubscriptionToggle.tsx
  frontends/mit-open/src/pages/FieldPage/EditFieldAppearanceForm.test.tsx
  frontends/mit-open/src/pages/FieldPage/EditFieldPage.test.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPage.test.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPageSkeleton.tsx
  frontends/mit-open/src/pages/FieldPage/FieldSearch.test.tsx
Labels: Needs Review

#1065 local dev: Read `MITOPEN_AXIOS_BASE_PATH` from env
  docker-compose.yml
  frontends/mit-open/package.json
  frontends/mit-open/webpack.config.js
  yarn.lock
Labels: Waiting on author

#1069 Update education options and add to schema
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/generated/v1/api.ts
  frontends/mit-open/src/pages/OnboardingPage/CertificateStep.tsx
  frontends/mit-open/src/pages/OnboardingPage/EducationLevelStep.tsx
  frontends/mit-open/src/pages/OnboardingPage/GoalsStep.tsx
  frontends/mit-open/src/pages/OnboardingPage/LearningFormatStep.tsx
  frontends/mit-open/src/pages/OnboardingPage/OnboardingPage.test.tsx
  frontends/mit-open/src/pages/OnboardingPage/TimeCommitmentStep.tsx
  openapi/exceptions.py
  openapi/hooks.py
  openapi/settings_spectacular.py
  openapi/specs/v0.yaml
  openapi/specs/v1.yaml
  profiles/constants.py
  profiles/migrations/0027_update_profile_education_choices.py
  profiles/models.py
  profiles/views_test.py
  scripts/openapi-configs/templates/modelEnum.mustache
  scripts/openapi-configs/typescript-axios-v0.yaml
  scripts/openapi-configs/typescript-axios-v1.yaml
Labels: Waiting on author

#1062 dashboard home
  frontends/api/src/test-utils/urls.ts
  frontends/mit-open/src/page-components/ResourceCarousel/ResourceCarousel.tsx
  frontends/mit-open/src/pages/DashboardPage/Dashboard.test.tsx
  frontends/mit-open/src/pages/DashboardPage/DashboardPage.tsx
  frontends/mit-open/src/pages/DashboardPage/carousels.ts
Labels: Needs Review

#1075 Change LOGIN_REDIRECT_URL and LOGOUT_REDIRECT_URL to use the base URL
  main/settings.py
Labels: Needs Review, product:mit-open

#1071 Adds ScrollRestoration to the spot in the routes
  frontends/mit-open/src/routes.tsx
  frontends/mit-open/src/test-utils/setupJest.ts
Labels: Needs Review, product:mit-open

#1074 Add pytest-xdist and use it for CI builds
  learning_resources_search/serializers_test.py
  poetry.lock
  pyproject.toml
  scripts/test/python_tests.sh
Labels: Waiting on author

#1073 Fixing image width and position on the homepage carousel; prefer cover image over avatar if it exists
  frontends/mit-open/src/pages/HomePage/TestimonialsSection.tsx
Labels: Needs Review, product:mit-open

#1001 Adds learner testimonials component for interior pages
  frontends/mit-open/src/page-components/TestimonialDisplay/TestimonialDisplay.tsx
  frontends/mit-open/src/pages/FieldPage/EditFieldAppearanceForm.test.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPage.test.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPage.tsx
  frontends/mit-open/src/pages/FieldPage/FieldSearch.test.tsx
  yarn.lock
Labels: Needs Review, product:mit-open

#1068 Homepage "Personalize"
  frontends/api/src/test-utils/factories/index.ts
  frontends/api/src/test-utils/factories/user.ts
  frontends/mit-open/public/images/homepage/personalize-bg.png
  frontends/mit-open/public/images/homepage/personalize-image.png
  frontends/mit-open/src/page-components/Header/Header.tsx
  frontends/mit-open/src/page-components/Header/UserMenu.tsx
  frontends/mit-open/src/pages/DashboardPage/Dashboard.test.tsx
  frontends/mit-open/src/pages/HomePage/BrowseTopicsSection.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.test.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.tsx
  frontends/mit-open/src/pages/HomePage/PersonalizeSection.tsx
  frontends/mit-open/src/pages/OnboardingPage/OnboardingPage.test.tsx
  frontends/ol-components/src/components/Button/Button.mdx
  frontends/ol-components/src/components/Button/Button.stories.tsx
  frontends/ol-components/src/components/Button/Button.test.tsx
  frontends/ol-components/src/components/Button/Button.tsx
  frontends/ol-components/src/components/Link/Link.tsx
  frontends/ol-components/src/components/ThemeProvider/ThemeProvider.tsx
  frontends/ol-components/src/components/ThemeProvider/typography.ts
Labels: Needs Review

#1086 Expose thenew user login url as an environment var
  app.json
  main/settings.py
Labels: Waiting on author

#1063 Shanbady/topic channel page header fixes
  frontends/mit-open/public/images/unit_banners/see.jpg
  frontends/mit-open/public/images/unit_banners/xpro.jpg
  frontends/mit-open/src/page-components/ChannelDetails/ChannelDetails.tsx
  frontends/mit-open/src/page-components/SearchSubscriptionToggle/SearchSubscriptionToggle.tsx
  frontends/mit-open/src/pages/ArticleDetailsPage/ArticleDetailsPage.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPage.test.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPageSkeleton.tsx
  frontends/mit-open/src/pages/LearningPathListingPage/LearningPathListingPage.tsx
  frontends/mit-open/src/pages/ListDetailsPage/ListDetailsPage.tsx
  frontends/mit-open/src/pages/UserListListingPage/UserListListingPage.tsx
  frontends/ol-components/src/components/BannerPage/BannerPage.tsx
Labels: Needs Review

#1084 Update OCW unit name in offerors.json
  learning_resources/data/channel_templates/offerors.json
Labels: Waiting on author

#1081 Shanbady/browse by topics UI fix
  frontends/mit-open/public/images/open-bg-texture-with-gradient.svg
  frontends/mit-open/src/pages/HomePage/BrowseTopicsSection.tsx
Labels: Needs Review

#1082 fix dashboard home certificate course carousel
  frontends/mit-open/src/pages/DashboardPage/Dashboard.test.tsx
  frontends/mit-open/src/pages/DashboardPage/DashboardPage.tsx
  frontends/mit-open/src/pages/DashboardPage/carousels.ts
Labels: Needs Review

#1051 search page styling
  frontends/mit-open/package.json
  frontends/mit-open/public/images/search_page_vector.png
  frontends/mit-open/src/GlobalStyles.tsx
  frontends/mit-open/src/page-components/Header/Header.tsx
  frontends/mit-open/src/page-components/SearchDisplay/ProfessionalToggle.tsx
  frontends/mit-open/src/page-components/SearchDisplay/ResourceTypeTabs.tsx
  frontends/mit-open/src/page-components/SearchDisplay/SearchDisplay.tsx
  frontends/mit-open/src/pages/FieldPage/FieldSearch.test.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.test.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.tsx
  frontends/ol-components/src/components/SearchInput/SearchInput.tsx
  frontends/ol-components/src/components/SimpleSelect/SimpleSelect.tsx
  frontends/ol-components/src/index.ts
  yarn.lock
Labels: Needs Review

#1090 excluding users from serializer
  frontends/api/src/generated/v1/api.ts
  frontends/api/src/test-utils/factories/percolateQueries.ts
  learning_resources_search/serializers.py
  openapi/specs/v1.yaml
Labels: Needs Review

#1096 Homepage Personalize: fix safari image stretching, cap image width
  frontends/mit-open/src/pages/HomePage/PersonalizeSection.tsx
Labels: Needs Review

#1089 breadcrumbs component
  frontends/mit-open/src/page-components/SearchDisplay/SearchDisplay.tsx
  frontends/mit-open/src/pages/AboutPage/AboutPage.tsx
  frontends/mit-open/src/pages/DepartmentListingPage/DepartmentListingPage.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPageSkeleton.tsx
  frontends/mit-open/src/pages/FieldPage/FieldSearch.test.tsx
  frontends/mit-open/src/pages/PrivacyPage/PrivacyPage.tsx
  frontends/mit-open/src/pages/TermsPage/TermsPage.tsx
  frontends/mit-open/src/pages/TopicListingPage/TopicsListingPage.tsx
  frontends/mit-open/src/pages/UnitsListingPage/UnitsListingPage.tsx
  frontends/ol-components/src/components/Breadcrumbs/Breadcrumbs.stories.tsx
  frontends/ol-components/src/components/Breadcrumbs/Breadcrumbs.test.tsx
  frontends/ol-components/src/components/Breadcrumbs/Breadcrumbs.tsx
  frontends/ol-components/src/components/Link/Link.tsx
  frontends/ol-components/src/index.ts
Labels: Waiting on author

#1106 Fastly secret name fix
  .github/workflows/production.yml
Labels: DevOps, bug

#1083 units page fixes
  frontends/mit-open/src/pages/UnitsListingPage/UnitsListingPage.tsx
Labels: Needs Review

#1085 Sort run prices on save; make learning resource prices equal "next run" prices
  frontends/api/src/generated/v1/api.ts
  frontends/api/src/test-utils/factories/learningResources.ts
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.tsx
  learning_resources/etl/loaders.py
  learning_resources/factories.py
  learning_resources/models.py
  learning_resources/models_test.py
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  openapi/specs/v1.yaml
Labels: Needs Review

#1078 Contentfile archive comparison fix
  learning_resources/etl/edx_shared.py
  learning_resources/etl/edx_shared_test.py
  learning_resources/etl/utils.py
  learning_resources/etl/utils_test.py
  test_json/course-v1:MITxT+8.01.3x+3T2022.tar.gz
  test_json/course-v1:MITxT+8.01.3x+3T2022_minor_change.tar.gz
  test_json/course-v1:MITxT+8.01.3x+3T2022_no_change.tar.gz
Labels: Needs Review

#1077 Add marketing images to homepage testimonial, fix some styling issues
  frontends/api/src/test-utils/factories/testimonials.ts
  frontends/mit-open/public/images/testimonial_images/testimonial-image-1.png
  frontends/mit-open/public/images/testimonial_images/testimonial-image-2.png
  frontends/mit-open/public/images/testimonial_images/testimonial-image-3.png
  frontends/mit-open/public/images/testimonial_images/testimonial-image-4.png
  frontends/mit-open/public/images/testimonial_images/testimonial-image-5.png
  frontends/mit-open/public/images/testimonial_images/testimonial-image-6.png
  frontends/mit-open/src/page-components/TestimonialDisplay/AttestantBlock.tsx
  frontends/mit-open/src/page-components/TestimonialDisplay/TestimonialDisplay.test.tsx
  frontends/mit-open/src/page-components/TestimonialDisplay/TestimonialDisplay.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.test.tsx
  frontends/mit-open/src/pages/HomePage/TestimonialsSection.tsx
  frontends/ol-components/src/components/ThemeProvider/typography.ts
Labels: product:mit-open, Waiting on author

#1103 Homepage Stories & Events layout fixes
  frontends/mit-open/src/pages/HomePage/NewsEventsSection.tsx
  frontends/ol-components/src/components/Card/Card.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.tsx
Labels: Waiting on author

#1113 Fixes/simplifies marketing image selector
  frontends/mit-open/src/pages/HomePage/TestimonialsSection.tsx
Labels: Needs Review, product:mit-open

#1111 two separate search inputs
  frontends/mit-open/src/page-components/SearchDisplay/SearchInput.test.tsx
  frontends/mit-open/src/page-components/SearchDisplay/SearchInput.tsx
  frontends/mit-open/src/pages/HomePage/HeroSearch.tsx
  frontends/mit-open/src/pages/HomePage/SearchInput.test.tsx
  frontends/mit-open/src/pages/HomePage/SearchInput.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.tsx
  frontends/ol-components/src/components/SearchInput/SearchInput.stories.tsx
  frontends/ol-components/src/index.ts
Labels: Needs Review

#1115 Append `/static` to the front of the testimonial marketing card image
  frontends/mit-open/src/pages/HomePage/TestimonialsSection.tsx
Labels: Needs Review, product:mit-open

#1029 Add profile edit page
  frontends/mit-open/src/page-components/Profile/CertificateChoice.tsx
  frontends/mit-open/src/page-components/Profile/EducationLevelChoice.tsx
  frontends/mit-open/src/page-components/Profile/GoalsChoice.tsx
  frontends/mit-open/src/page-components/Profile/LearningFormatChoice.tsx
  frontends/mit-open/src/page-components/Profile/TimeCommitmentChoice.tsx
  frontends/mit-open/src/page-components/Profile/TopicInterestsChoice.tsx
  frontends/mit-open/src/page-components/Profile/types.ts
  frontends/mit-open/src/pages/DashboardPage/DashboardPage.tsx
  frontends/mit-open/src/pages/DashboardPage/ProfileEditForm.tsx
  frontends/mit-open/src/pages/OnboardingPage/CertificateStep.tsx
  frontends/mit-open/src/pages/OnboardingPage/EducationLevelStep.tsx
  frontends/mit-open/src/pages/OnboardingPage/GoalsStep.tsx
  frontends/mit-open/src/pages/OnboardingPage/LearningFormatStep.tsx
  frontends/mit-open/src/pages/OnboardingPage/OnboardingPage.tsx
  frontends/mit-open/src/pages/OnboardingPage/Prompt.tsx
  frontends/mit-open/src/pages/OnboardingPage/TimeCommitmentStep.tsx
  frontends/mit-open/src/pages/OnboardingPage/TopicInterestsStep.tsx
  frontends/mit-open/src/pages/OnboardingPage/types.ts
  frontends/ol-components/src/components/ChoiceBox/ChoiceBox.tsx
  frontends/ol-components/src/components/RadioChoiceField/RadioChoiceField.tsx
Labels: Waiting on author

#1108 Updates to learning resource price display
  frontends/api/src/test-utils/factories/learningResources.ts
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.stories.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.test.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.tsx
Labels: Needs Review

#1104 show courses and programs first in default sort
  frontends/api/src/generated/v1/api.ts
  learning_resources_search/api.py
  learning_resources_search/api_test.py
  learning_resources_search/constants.py
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
  openapi/specs/v1.yaml
Labels: Needs Review

#1097 Fix populate_featured_lists mgmt command
  learning_resources/management/commands/populate_featured_lists.py
Labels: Waiting on author

#1120 switch default sort to use popular instead of created on
  learning_resources_search/api.py
  learning_resources_search/api_test.py
Labels: Waiting on author

#1116 Make resource.prices = most recent published run prices if there is no next run
  learning_resources/models.py
  learning_resources/models_test.py
Labels: Needs Review

#1102 mitx - only ingest published courses
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/etl/mitxonline.py
  learning_resources/etl/mitxonline_test.py
  learning_resources/etl/pipelines.py
  learning_resources/etl/pipelines_test.py
Labels: Waiting on author

#1119 Shanbady/navigation UI fixes
  frontends/mit-open/src/page-components/Header/Header.tsx
  frontends/mit-open/src/page-components/Header/UserMenu.tsx
  frontends/ol-components/src/components/NavDrawer/NavDrawer.tsx
Labels: Needs Review

#1118 Shanbady/minor UI updates
  frontends/mit-open/src/page-components/Footer/Footer.test.tsx
  frontends/mit-open/src/page-components/Footer/Footer.tsx
  frontends/mit-open/src/page-components/Header/Header.test.tsx
  frontends/mit-open/src/page-components/Header/UserMenu.tsx
  frontends/mit-open/src/page-components/SearchSubscriptionToggle/SearchSubscriptionToggle.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPage.test.tsx
Labels: Needs Review

#1121 Updates to page titles
  frontends/jest.jsdom.config.ts
  frontends/mit-open/src/pages/AboutPage/AboutPage.test.tsx
  frontends/mit-open/src/pages/AboutPage/AboutPage.tsx
  frontends/mit-open/src/pages/ArticleDetailsPage/ArticleDetailsPage.test.tsx
  frontends/mit-open/src/pages/ArticleDetailsPage/ArticleDetailsPage.tsx
  frontends/mit-open/src/pages/ArticleUpsertPages/ArticleEditPage.test.tsx
  frontends/mit-open/src/pages/ArticleUpsertPages/ArticleEditPage.tsx
  frontends/mit-open/src/pages/ArticleUpsertPages/ArticleUpsertPage.tsx
  frontends/mit-open/src/pages/DashboardPage/Dashboard.test.tsx
  frontends/mit-open/src/pages/DashboardPage/DashboardPage.tsx
  frontends/mit-open/src/pages/DepartmentListingPage/DepartmentListingPage.test.tsx
  frontends/mit-open/src/pages/DepartmentListingPage/DepartmentListingPage.tsx
  frontends/mit-open/src/pages/ErrorPage/ErrorPage.test.tsx
  frontends/mit-open/src/pages/ErrorPage/ErrorPageTemplate.tsx
  frontends/mit-open/src/pages/ErrorPage/ForbiddenPage.test.tsx
  frontends/mit-open/src/pages/FieldPage/EditFieldPage.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPageSkeleton.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.tsx
  frontends/mit-open/src/pages/LearningPathListingPage/LearningPathListingPage.test.tsx
  frontends/mit-open/src/pages/LearningPathListingPage/LearningPathListingPage.tsx
  frontends/mit-open/src/pages/ListDetailsPage/ListDetailsPage.test.ts
  frontends/mit-open/src/pages/ListDetailsPage/ListDetailsPage.tsx
  frontends/mit-open/src/pages/OnboardingPage/OnboardingPage.tsx
  frontends/mit-open/src/pages/PrivacyPage/PrivacyPage.test.tsx
  frontends/mit-open/src/pages/PrivacyPage/PrivacyPage.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.tsx
  frontends/mit-open/src/pages/TermsPage/TermsPage.test.tsx
  frontends/mit-open/src/pages/TermsPage/TermsPage.tsx
  frontends/mit-open/src/pages/TopicListingPage/TopicsListingPage.test.tsx
  frontends/mit-open/src/pages/TopicListingPage/TopicsListingPage.tsx
  frontends/mit-open/src/pages/UnitsListingPage/UnitsListingPage.test.tsx
  frontends/mit-open/src/pages/UnitsListingPage/UnitsListingPage.tsx
  frontends/mit-open/src/pages/UserListListingPage/UserListListingPage.test.tsx
  frontends/mit-open/src/pages/UserListListingPage/UserListListingPage.tsx
  frontends/mit-open/webpack.config.js
  frontends/ol-utilities/src/components/MetaTags.tsx
Labels: Waiting on author

#1123 show podcast_episode in media carousel all
  frontends/mit-open/src/pages/HomePage/carousels.ts
Labels: Needs Review

#1109 Signup Popover
  frontends/api/src/test-utils/urls.ts
  frontends/mit-open/src/page-components/LearningResourceDrawer/LearningResourceDrawer.tsx
  frontends/mit-open/src/page-components/ResourceCard/ResourceCard.test.tsx
  frontends/mit-open/src/page-components/ResourceCard/ResourceCard.tsx
  frontends/mit-open/src/page-components/ResourceCarousel/ResourceCarousel.test.tsx
  frontends/mit-open/src/page-components/ResourceCarousel/ResourceCarousel.tsx
  frontends/mit-open/src/page-components/SearchDisplay/SearchDisplay.tsx
  frontends/mit-open/src/page-components/SearchSubscriptionToggle/SearchSubscriptionToggle.test.tsx
  frontends/mit-open/src/page-components/SearchSubscriptionToggle/SearchSubscriptionToggle.tsx
  frontends/mit-open/src/page-components/SignupPopover/SignupPopover.test.tsx
  frontends/mit-open/src/page-components/SignupPopover/SignupPopover.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPage.test.tsx
  frontends/ol-components/package.json
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.test.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.test.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.tsx
  frontends/ol-components/src/components/Popover/Popover.stories.tsx
  frontends/ol-components/src/components/Popover/Popover.test.tsx
  frontends/ol-components/src/components/Popover/Popover.tsx
  frontends/ol-components/src/index.ts
  yarn.lock
Labels: Waiting on author

#1125 Shanbady/copy edits for milestone demo
  frontends/mit-open/src/page-components/Header/UserMenu.tsx
  frontends/mit-open/src/pages/DepartmentListingPage/DepartmentListingPage.test.tsx
  frontends/mit-open/src/pages/DepartmentListingPage/DepartmentListingPage.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPageSkeleton.tsx
  frontends/mit-open/src/pages/HomePage/BrowseTopicsSection.tsx
  frontends/mit-open/src/pages/HomePage/HeroSearch.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.test.tsx
  frontends/mit-open/src/pages/HomePage/TestimonialsSection.tsx
  frontends/mit-open/src/pages/HomePage/carousels.ts
  frontends/mit-open/src/pages/SearchPage/SearchPage.tsx
  frontends/mit-open/src/pages/TopicListingPage/TopicsListingPage.test.tsx
  frontends/mit-open/src/pages/TopicListingPage/TopicsListingPage.tsx
Labels: Needs Review

#1134 about page updates
  frontends/mit-open/src/pages/AboutPage/AboutPage.tsx
  frontends/mit-open/src/pages/HomePage/HeroSearch.tsx
  frontends/mit-open/src/pages/PrivacyPage/PrivacyPage.tsx
  frontends/mit-open/src/pages/TermsPage/TermsPage.tsx
  frontends/mit-open/src/routes.tsx
Labels: Needs Review, product:mit-open

#1132 add learning materials tab
  frontends/mit-open/public/images/navdrawer/course_materials.svg
  frontends/mit-open/public/images/navdrawer/learning_materials.svg
  frontends/mit-open/src/page-components/Header/Header.tsx
  frontends/mit-open/src/page-components/SearchDisplay/ResourceTypeTabs.tsx
  frontends/mit-open/src/page-components/SearchDisplay/SearchDisplay.tsx
  frontends/mit-open/src/pages/FieldPage/FieldSearch.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.test.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.tsx
Labels: Needs Review

#1130 fixing sort method for panel detail display
  frontends/mit-open/src/page-components/ChannelDetails/ChannelDetails.test.tsx
  frontends/mit-open/src/page-components/ChannelDetails/ChannelDetails.tsx
Labels: Needs Review

#1131 Applies new fixes for the homepage and unit page testimonial sliders
  frontends/api/src/generated/v0/api.ts
  frontends/mit-open/src/page-components/TestimonialDisplay/AttestantBlock.tsx
  frontends/mit-open/src/page-components/TestimonialDisplay/TestimonialDisplay.tsx
  frontends/mit-open/src/pages/HomePage/TestimonialsSection.tsx
  openapi/specs/v0.yaml
  testimonials/migrations/0004_update_attestation_avatar_make_optional.py
  testimonials/models.py
  testimonials/serializers.py
Labels: product:mit-open

#1137 Search facet checkbox and label styles
  frontends/mit-open/src/page-components/SearchDisplay/SearchDisplay.tsx
Labels: Needs Review

#1140 creating profile automatically for logged in user
  profiles/views.py
  profiles/views_test.py
Labels: Needs Review

#1141 Some copy edits and minor about page styling updates
  frontends/mit-open/src/pages/AboutPage/AboutPage.tsx
  frontends/mit-open/src/pages/HomePage/HeroSearch.tsx
Labels: Needs Review

#1152 fix django hijack route
  config/nginx.conf
  config/nginx.conf.erb
Labels: Waiting on author

#1158 sort by -views instead
  frontends/mit-open/src/page-components/Header/Header.tsx
Labels: Needs Review, product:mit-open

#1154 Use course_description_html field for OCW courses
  learning_resources/etl/ocw.py
  learning_resources/etl/ocw_test.py
  test_json/courses/16-01-unified-engineering-i-ii-iii-iv-fall-2005-spring-2006/data.json
Labels: Needs Review

#1159 better chunking for content files
  learning_resources_search/indexing_api.py
  learning_resources_search/indexing_api_test.py
  learning_resources_search/tasks.py
  learning_resources_search/tasks_test.py
Labels: Waiting on author

#1122 Working search filter on topics with commas
  frontends/mit-open/src/pages/FieldPage/FieldPage.test.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPage.tsx
  learning_resources/filters_test.py
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
  main/filters.py
Labels: Needs Review

#1143 Search facet styles and animation
  frontends/mit-open/package.json
  frontends/mit-open/src/page-components/SearchDisplay/SearchDisplay.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.tsx
  yarn.lock
Labels: Waiting on author

#1144 Adds a separate pane for the filter CTAs, adds an apply button on mobile
  frontends/mit-open/src/page-components/SearchDisplay/SearchDisplay.tsx
  frontends/ol-components/src/components/Button/Button.stories.tsx
  frontends/ol-components/src/components/Button/Button.tsx
Labels: product:mit-open, Waiting on author

#1160 Update Select and Dropdown components
  frontends/mit-open/src/page-components/ManageListDialogs/ManageListDialogs.tsx
  frontends/mit-open/src/page-components/Profile/EducationLevelChoice.tsx
  frontends/mit-open/src/page-components/Profile/LearningFormatChoice.tsx
  frontends/mit-open/src/page-components/Profile/TimeCommitmentChoice.tsx
  frontends/mit-open/src/page-components/SearchDisplay/SearchDisplay.tsx
  frontends/mit-open/src/pages/FieldPage/FieldSearchFacetDisplay.tsx
  frontends/ol-components/src/components/FormHelpers/FormHelpers.tsx
  frontends/ol-components/src/components/Input/Input.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.tsx
  frontends/ol-components/src/components/MenuItem/MenuItem.tsx
  frontends/ol-components/src/components/SelectField/SelectField.mdx
  frontends/ol-components/src/components/SelectField/SelectField.stories.tsx
  frontends/ol-components/src/components/SelectField/SelectField.tsx
  frontends/ol-components/src/components/SimpleMenu/SimpleMenu.stories.tsx
  frontends/ol-components/src/components/SimpleMenu/SimpleMenu.test.tsx
  frontends/ol-components/src/components/SimpleMenu/SimpleMenu.tsx
  frontends/ol-components/src/components/SimpleSelect/SimpleSelect.stories.tsx
  frontends/ol-components/src/components/SimpleSelect/SimpleSelect.test.tsx
  frontends/ol-components/src/components/SimpleSelect/SimpleSelect.tsx
  frontends/ol-components/src/components/ThemeProvider/ThemeProvider.tsx
  frontends/ol-components/src/index.ts
Labels: Waiting on author

#1164 remove course filter from featured carousel
  frontends/mit-open/src/pages/HomePage/HomePage.test.tsx
  frontends/mit-open/src/pages/HomePage/carousels.ts
Labels: Needs Review, product:mit-open

#1156 Shanbady/search page card mobile updates
  frontends/ol-components/src/components/Card/ListCard.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.tsx
Labels: Needs Review

#1166 de-flake a test
  frontends/api/src/test-utils/factories/learningResources.ts
Labels: Needs Review

#1153 Update favicons
  frontends/github-pages/public/favicon.ico
  frontends/mit-open/public/favicon.ico
  frontends/mit-open/public/favicon.svg
  frontends/mit-open/public/images/favicon.ico
  frontends/mit-open/public/index.html
Labels: Needs Review

#1168 fix flaky test
  frontends/mit-open/src/pages/FieldPage/FieldPage.test.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPageSkeleton.tsx
Labels: Needs Review

#1165 Set default ordering by position for userlist and learningresource relationships
  learning_resources/migrations/0055_alter_relationship_options_ordering.py
  learning_resources/models.py
Labels: Needs Review

#1167 fix content file search
  frontends/api/src/generated/v1/api.ts
  frontends/mit-open/src/page-components/SearchDisplay/ResourceTypeTabs.tsx
  frontends/mit-open/src/pages/DepartmentListingPage/DepartmentListingPage.test.tsx
  frontends/mit-open/src/pages/DepartmentListingPage/DepartmentListingPage.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPage.test.tsx
  frontends/mit-open/src/pages/FieldPage/FieldSearch.test.tsx
  frontends/mit-open/src/pages/SearchPage/SearchPage.test.tsx
  frontends/mit-open/src/pages/TopicListingPage/TopicsListingPage.test.tsx
  frontends/mit-open/src/pages/TopicListingPage/TopicsListingPage.tsx
  frontends/mit-open/src/pages/UnitsListingPage/UnitsListingPage.test.tsx
  frontends/mit-open/src/pages/UnitsListingPage/UnitsListingPage.tsx
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
  learning_resources_search/views.py
  learning_resources_search/views_test.py
  openapi/specs/v1.yaml
Labels: Waiting on author

#1151 fixing width of unit page logo for small devices
  frontends/mit-open/src/components/FieldAvatar/FieldAvatar.tsx
  frontends/mit-open/src/pages/FieldPage/FieldPageSkeleton.tsx
Labels: Needs Review

#1170 rename field to channel
  channels/admin.py
  channels/api.py
  channels/api_test.py
  channels/conftest.py
  channels/constants.py
  channels/factories.py
  channels/migrations/0009_rename_field_to_channel.py
  channels/models.py
  channels/permissions.py
  channels/permissions_test.py
  channels/plugins.py
  channels/plugins_test.py
  channels/schema.py
  channels/serializers.py
  channels/serializers_test.py
  channels/signals.py
  channels/urls.py
  channels/views.py
  channels/views_test.py
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/hooks/channels/index.ts
  frontends/api/src/hooks/channels/keyFactory.ts
  frontends/api/src/test-utils/factories/channels.ts
  frontends/api/src/test-utils/factories/index.ts
  frontends/api/src/test-utils/urls.ts
  frontends/mit-open/src/common/urls.ts
  frontends/mit-open/src/components/ChannelAvatar/ChannelAvatar.test.tsx
  frontends/mit-open/src/components/ChannelAvatar/ChannelAvatar.tsx
  frontends/mit-open/src/components/ChannelMenu/ChannelMenu.test.tsx
  frontends/mit-open/src/components/ChannelMenu/ChannelMenu.tsx
  frontends/mit-open/src/page-components/ChannelDetails/ChannelDetails.test.tsx
  frontends/mit-open/src/page-components/ChannelDetails/ChannelDetails.tsx
  frontends/mit-open/src/pages/ChannelPage/ChannelPage.test.tsx
  frontends/mit-open/src/pages/ChannelPage/ChannelPage.tsx
  frontends/mit-open/src/pages/ChannelPage/ChannelPageSkeleton.tsx
  frontends/mit-open/src/pages/ChannelPage/ChannelSearch.test.tsx
  frontends/mit-open/src/pages/ChannelPage/ChannelSearch.tsx
  frontends/mit-open/src/pages/ChannelPage/ChannelSearchFacetDisplay.tsx
  frontends/mit-open/src/pages/ChannelPage/EditChannelAppearanceForm.test.tsx
  frontends/mit-open/src/pages/ChannelPage/EditChannelAppearanceForm.tsx
  frontends/mit-open/src/pages/ChannelPage/EditChannelPage.test.tsx
  frontends/mit-open/src/pages/ChannelPage/EditChannelPage.tsx
  frontends/mit-open/src/pages/ChannelPage/WidgetsList.test.tsx
  frontends/mit-open/src/pages/ChannelPage/WidgetsList.tsx
  frontends/mit-open/src/pages/UnitsListingPage/UnitsListingPage.test.tsx
  frontends/mit-open/src/pages/UnitsListingPage/UnitsListingPage.tsx
  frontends/mit-open/src/routes.tsx
  learning_resources/management/commands/backpopulate_resource_channels.py
  learning_resources/management/commands/populate_featured_lists.py
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  learning_resources/views.py
  learning_resources/views_test.py
  openapi/specs/v0.yaml
  testimonials/filters.py
  testimonials/migrations/0005_alter_attestation_channels.py
  testimonials/models.py
  testimonials/views_test.py
Labels: Needs Review

#1182 Adding the PostHog settings to the "Build frontend" step
  .github/workflows/production.yml
  .github/workflows/release-candidate.yml
Labels: product:mit-open, Work in Progress

#1181 Swap search and login button positions
  frontends/mit-open/src/page-components/Header/Header.tsx
  frontends/mit-open/src/page-components/Header/UserMenu.tsx
Labels: Waiting on author

#1136 New default image for learning resources
  frontends/mit-open/public/images/default_resource.jpg
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.tsx
  frontends/ol-utilities/src/learning-resources/learning-resources.ts
Labels: Needs Review, product:mit-open

#1186 adding command to remove old tables
  channels/migrations/0009_rename_field_to_channel.py
Labels: Needs Review

#1174 Updates to ChoiceBox; Checkbox, Radio components
  frontends/mit-open/package.json
  frontends/mit-open/src/page-components/Dialogs/AddToListDialog.tsx
  frontends/mit-open/src/page-components/Profile/CertificateChoice.tsx
  frontends/mit-open/src/page-components/Profile/GoalsChoice.tsx
  frontends/mit-open/src/page-components/SearchDisplay/SearchDisplay.tsx
  frontends/mit-open/src/pages/OnboardingPage/OnboardingPage.tsx
  frontends/ol-components/package.json
  frontends/ol-components/src/components/Checkbox/Checkbox.stories.tsx
  frontends/ol-components/src/components/Checkbox/Checkbox.tsx
  frontends/ol-components/src/components/ChoiceBox/ChoiceBox.stories.tsx
  frontends/ol-components/src/components/ChoiceBox/ChoiceBox.tsx
  frontends/ol-components/src/components/ChoiceBox/ChoiceBoxField.tsx
  frontends/ol-components/src/components/ChoiceBox/ChoiceBoxFieldCheckbox.stories.tsx
  frontends/ol-components/src/components/ChoiceBox/ChoiceBoxFieldRadio.stories.tsx
  frontends/ol-components/src/components/Radio/Radio.stories.tsx
  frontends/ol-components/src/components/Radio/Radio.tsx
  frontends/ol-components/src/index.ts
  yarn.lock
Labels: Waiting on author

#1190 Drawer CSS fixes
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.tsx
  frontends/ol-components/src/components/RoutedDrawer/RoutedDrawer.tsx
Labels: Needs Review

#1189 Scroll results into view when paginating
  frontends/jest-shared-setup.ts
  frontends/mit-open/src/page-components/SearchDisplay/SearchDisplay.tsx
Labels: Waiting on author

#1188 resource category
  frontends/api/src/generated/v1/api.ts
  learning_resources/constants.py
  learning_resources/filters.py
  learning_resources/filters_test.py
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  learning_resources_search/constants.py
  learning_resources_search/serializers.py
  learning_resources_search/serializers_test.py
  openapi/specs/v1.yaml
Labels: Needs Review

#1183 Square aspect ratio for media resource images
  frontends/mit-open/src/page-components/ResourceCarousel/types.ts
  frontends/mit-open/src/pages/HomePage/HomePage.tsx
  frontends/mit-open/src/pages/HomePage/carousels.ts
  frontends/ol-components/src/components/Card/Card.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.tsx
Labels: Needs Review

#1180 Filled vs Unfilled Bookmarks
  frontends/api/src/hooks/learningResources/index.test.ts
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/hooks/learningResources/keyFactory.ts
  frontends/mit-open/src/page-components/ResourceCard/ResourceCard.test.tsx
  frontends/mit-open/src/page-components/ResourceCard/ResourceCard.tsx
  frontends/mit-open/src/pages/LearningPathListingPage/LearningPathListingPage.tsx
  frontends/ol-components/src/components/Card/ListCard.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.tsx
  frontends/ol-components/src/index.ts
Labels: Needs Review

#1169 Don't display carousel tabs if there's no data to display
  channels/migrations/0010_alter_channel_name_regex.py
  channels/models.py
  frontends/mit-open/src/page-components/ResourceCarousel/ResourceCarousel.tsx
  frontends/mit-open/src/pages/HomePage/HomePage.test.tsx
  openapi/specs/v0.yaml
Labels: product:mit-open, Waiting on author

#1185 setting 100px as default width for buttons
  frontends/mit-open/src/page-components/Header/MenuButton.tsx
  frontends/ol-components/src/components/Button/Button.tsx
  frontends/ol-components/src/components/TabButtons/TabButtonList.tsx
Labels: Needs Review

#1197 stop publishing github pages every pr
  .github/workflows/ci.yml
Labels: Waiting on author

#1192 adding post logout redirect to logout url
  authentication/views.py
Labels: Waiting on author

#1193 update sloan executive education offerings
  learning_resources/fixtures/offered_by.json
Labels: Needs Review, Waiting on author

#1194 update mitpe unit data
  learning_resources/fixtures/offered_by.json
Labels: Waiting on author
