Repository mitodl/mit-learn, pull requests merged in 2025-04, with the labels that each got.

#2161 first pass at docker image optimization
  Dockerfile
  apt.txt
  docker-compose.apps.yml
  frontends/main/Dockerfile.web
  nginx/Dockerfile
Labels: DevOps, enhancement

#2173 adding selenium dependency
  poetry.lock
  pyproject.toml
Labels: Needs Review

#2171 reorganize dashboard tabs
  frontends/api/src/test-utils/urls.ts
  frontends/main/src/app-pages/ChannelPage/ChannelPage.test.tsx
  frontends/main/src/app-pages/DashboardPage/Dashboard.test.tsx
  frontends/main/src/app-pages/DashboardPage/DashboardLayout.test.tsx
  frontends/main/src/app-pages/DashboardPage/DashboardLayout.tsx
  frontends/main/src/app-pages/DashboardPage/HomeContent.test.tsx
  frontends/main/src/app-pages/DashboardPage/HomeContent.tsx
  frontends/main/src/app-pages/DashboardPage/ProfileContent.tsx
  frontends/main/src/app-pages/DashboardPage/SettingsContent.tsx
  frontends/main/src/app-pages/DashboardPage/UserListDetailsContent.tsx
  frontends/main/src/app/dashboard/[tab]/page.tsx
  frontends/main/src/app/dashboard/layout.tsx
  frontends/main/src/app/dashboard/my-lists/[id]/page.tsx
  frontends/main/src/app/dashboard/my-lists/page.tsx
  frontends/main/src/app/dashboard/page.tsx
  frontends/main/src/app/dashboard/profile/page.tsx
  frontends/main/src/app/dashboard/settings/page.tsx
  frontends/main/src/page-components/ResourceCarousel/ResourceCarousel.test.tsx
  frontends/main/src/page-components/ResourceCarousel/ResourceCarousel.tsx
  frontends/main/src/page-components/UserListListing/UserListListing.tsx
Labels: Needs Review

#2182 add a prop to DashboardCard to optionally disable the not complete icon
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/DashboardCard.test.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/DashboardCard.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/EnrollmentDisplay.tsx
Labels: Needs Review

#2185 remove initial messages
  frontends/main/package.json
  frontends/main/src/page-components/AiChat/AiRecommendationBotDrawer.tsx
  frontends/main/src/page-components/LearningResourceExpanded/AiChatSyllabusSlideDown.test.tsx
  frontends/main/src/page-components/LearningResourceExpanded/AiChatSyllabusSlideDown.tsx
  frontends/main/src/test-utils/index.tsx
  yarn.lock
Labels: Needs Review

#2180 Scrape marketing sites with dynamic content
  Dockerfile
  learning_resources/conftest.py
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/etl/utils.py
  learning_resources/tasks.py
  learning_resources/tasks_test.py
  learning_resources/utils.py
  main/settings.py
  main/settings_celery.py
  poetry.lock
  pyproject.toml
  vector_search/tasks_test.py
Labels: Needs Review

#2190 Add a default worker concurrency for local dev
  env/backend.env
Labels: Needs Review

#2187 enrollment dashboard mobile layout
  frontends/api/src/mitxonline/test-utils/factories/enrollment.ts
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/DashboardCard.test.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/DashboardCard.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/EnrollmentDisplay.test.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/EnrollmentDisplay.tsx
Labels: Needs Review

#2189 UAI Dashboard
  frontends/api/src/mitxonline/clients.ts
  frontends/api/src/mitxonline/generated/v0/api.ts
  frontends/api/src/mitxonline/hooks/courses/data.ts
  frontends/api/src/mitxonline/hooks/courses/index.ts
  frontends/api/src/mitxonline/hooks/courses/queries.ts
  frontends/api/src/mitxonline/hooks/enrollment/data.ts
  frontends/api/src/mitxonline/hooks/enrollment/dataForOrgs.ts
  frontends/api/src/mitxonline/hooks/enrollment/index.ts
  frontends/api/src/mitxonline/hooks/enrollment/queries.ts
  frontends/api/src/mitxonline/hooks/programs/data.ts
  frontends/api/src/mitxonline/hooks/programs/index.ts
  frontends/api/src/mitxonline/hooks/programs/queries.ts
  frontends/api/src/mitxonline/test-utils/factories/courses.ts
  frontends/api/src/mitxonline/test-utils/factories/enrollment.ts
  frontends/api/src/mitxonline/test-utils/factories/index.ts
  frontends/api/src/mitxonline/test-utils/factories/programs.ts
  frontends/api/src/mitxonline/test-utils/urls.ts
  frontends/api/src/test-utils/factories/user.ts
  frontends/api/src/test-utils/urls.ts
  frontends/main/public/images/dashboard/graduate.png
  frontends/main/public/images/icons/course-complete.svg
  frontends/main/public/images/icons/course-in-progress.svg
  frontends/main/src/app-pages/ChannelPage/ChannelPage.test.tsx
  frontends/main/src/app-pages/ChannelPage/ChannelSearch.test.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/DashboardCard.test.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/DashboardCard.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/EnrollmentDisplay.test.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/EnrollmentDisplay.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/EnrollmentStatusIndicator.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/test-utils.ts
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/transform.test.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/transform.ts
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/types.ts
  frontends/main/src/app-pages/DashboardPage/DashboardLayout.test.tsx
  frontends/main/src/app-pages/DashboardPage/DashboardLayout.tsx
  frontends/main/src/app-pages/DashboardPage/HomeContent.test.tsx
  frontends/main/src/app-pages/DashboardPage/OrganizationContent.test.tsx
  frontends/main/src/app-pages/DashboardPage/OrganizationContent.tsx
  frontends/main/src/app/dashboard/organization/[id]/page.tsx
  frontends/main/src/common/feature_flags.ts
  frontends/main/src/common/urls.ts
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawer.test.tsx
  frontends/main/src/test-utils/delete.mockAxios.ts
  frontends/main/src/test-utils/index.tsx
  frontends/ol-test-utilities/src/factories.ts
  frontends/ol-test-utilities/src/index.ts
  frontends/ol-test-utilities/src/querify.ts
Labels: Needs Review

#2194 Add OpenTelemetry Config
  main/apps.py
  main/settings.py
  main/telemetry.py
  poetry.lock
  pyproject.toml
Labels: DevOps

#2195 enrollments dashboard expand collapse
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/EnrollmentDisplay.test.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/EnrollmentDisplay.tsx
Labels: Needs Review

#2209 Rename the realm file to work under keycloak 26.2+
  .pre-commit-config.yaml
  README-keycloak.md
  config/keycloak/realms/ol-local-realm.json
Labels: Waiting on author

#2204 redirect new users to onboarding
  authentication/views.py
  authentication/views_test.py
  frontends/main/src/app-pages/OnboardingPage/OnboardingPage.test.tsx
  frontends/main/src/app-pages/OnboardingPage/OnboardingPage.tsx
  main/settings.py
  profiles/migrations/0035_profile_completed_onboarding.py
  profiles/migrations/0036_set_onboarding_complete_for_existing_users.py
  profiles/models.py
Labels: Needs Review

#2212 Increase local dev container session lifespan to 2 weeks
  config/apisix/apisix.yaml
  config/keycloak/realms/ol-local-realm.json
Labels: Needs Review

#2216 add a loading state to DashboardCard
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/DashboardCard.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/EnrollmentDisplay.tsx
Labels: Waiting on author
