Repository mitodl/mit-learn, pull requests merged in 2025-02, with the labels that each got.

#2011 track additional browse events in posthog
  frontends/main/src/app-pages/ChannelPage/TopicChannelTemplate.tsx
  frontends/main/src/app-pages/DepartmentListingPage/DepartmentListingPage.tsx
  frontends/main/src/app-pages/HomePage/BrowseTopicsSection.tsx
  frontends/main/src/app-pages/TopicsListingPage/TopicsListingPage.tsx
  frontends/main/src/app-pages/UnitsListingPage/UnitCard.tsx
  frontends/main/src/common/constants.ts
  frontends/main/src/page-components/Dialogs/AddToListDialog.tsx
  frontends/main/src/page-components/Header/Header.tsx
  frontends/main/src/page-components/HeroSearch/HeroSearch.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawer.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceExpanded.tsx
  frontends/main/src/page-components/SearchField/SearchField.tsx
Labels: Waiting on author

#2012 Remove imports for builtin django User model
  .gitignore
  channels/api.py
  channels/views.py
  channels/views_test.py
  learning_resources/management/commands/backpopulate_favorites_lists.py
  learning_resources/management/commands/populate_featured_lists.py
  learning_resources/models.py
  learning_resources/serializers.py
  learning_resources/utils.py
  main/factories.py
  main/settings.py
  profiles/views.py
  profiles/views_test.py
  pyproject.toml
Labels: Waiting on author

#2013 Add initial users app
  .gitignore
  Dockerfile
  backups/.keep
  certs/.keep
  docker-compose.services.yml
  main/settings.py
  users/__init__.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
Labels: Needs Review, Waiting on author

#2017 Skip existing embeddings
  vector_search/management/commands/create_qdrant_collections.py
  vector_search/management/commands/generate_embeddings.py
  vector_search/tasks.py
  vector_search/tasks_test.py
  vector_search/utils.py
  vector_search/utils_test.py
Labels: Waiting on author

#2021 Remove django-debug-toolbar
  main/settings.py
  main/urls.py
  poetry.lock
  pyproject.toml
Labels: Needs Review

#2015 Add custom user model
  main/settings.py
  users/migrations/0001_initial.py
  users/migrations/0002_update_user_contenttype.py
  users/models.py
Labels: Waiting on author

#2040 Remove `@lukemorales/query-key-factory`, unblock react-query v5 upgrade
  frontends/api/package.json
  frontends/api/src/hooks/articles/index.test.ts
  frontends/api/src/hooks/articles/index.ts
  frontends/api/src/hooks/articles/keyFactory.ts
  frontends/api/src/hooks/articles/queries.ts
  frontends/api/src/hooks/channels/index.ts
  frontends/api/src/hooks/channels/keyFactory.ts
  frontends/api/src/hooks/channels/queries.ts
  frontends/api/src/hooks/learningPaths/index.test.ts
  frontends/api/src/hooks/learningPaths/index.ts
  frontends/api/src/hooks/learningPaths/keyFactory.ts
  frontends/api/src/hooks/learningPaths/queries.ts
  frontends/api/src/hooks/learningResources/index.ts
  frontends/api/src/hooks/learningResources/keyFactory.ts
  frontends/api/src/hooks/learningResources/queries.ts
  frontends/api/src/hooks/newsEvents/index.ts
  frontends/api/src/hooks/newsEvents/keyFactory.ts
  frontends/api/src/hooks/newsEvents/queries.ts
  frontends/api/src/hooks/programLetters/index.ts
  frontends/api/src/hooks/programLetters/keyFactory.ts
  frontends/api/src/hooks/programLetters/queries.ts
  frontends/api/src/hooks/searchSubscription/index.ts
  frontends/api/src/hooks/searchSubscription/keyFactory.ts
  frontends/api/src/hooks/testimonials/index.ts
  frontends/api/src/hooks/testimonials/keyFactory.ts
  frontends/api/src/hooks/testimonials/queries.ts
  frontends/api/src/hooks/userLists/index.ts
  frontends/api/src/hooks/userLists/keyFactory.ts
  frontends/api/src/hooks/userLists/queries.ts
  frontends/api/src/hooks/widget_lists/index.ts
  frontends/api/src/hooks/widget_lists/keyFactory.ts
  frontends/api/src/hooks/widget_lists/queries.ts
  frontends/api/src/ssr/usePrefetchWarnings.test.ts
  frontends/api/src/test-utils/factories/learningResources.ts
  frontends/main/src/app/c/[channelType]/[name]/page.tsx
  frontends/main/src/app/departments/page.tsx
  frontends/main/src/app/page.tsx
  frontends/main/src/app/search/page.tsx
  frontends/main/src/app/topics/page.tsx
  frontends/main/src/app/units/page.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawer.test.tsx
  frontends/main/src/page-components/ResourceCard/ResourceCard.test.tsx
  frontends/main/src/page-components/ResourceCarousel/ResourceCarousel.tsx
  yarn.lock
Labels: Needs Review

#2041 Embeddings - Stay within openai request size limits
  vector_search/utils.py
Labels: Waiting on author

#2016 Rename user table from `auth_user` to `users_user`
  users/migrations/0003_rename_user_table.py
  users/models.py
Labels: Waiting on author

#2045 Point the chatbots to the Learn AI endpoints
  .github/workflows/ci.yml
  .github/workflows/production.yml
  .github/workflows/release-candidate.yml
  env/frontend.env
  frontends/main/Dockerfile.web
  frontends/main/src/app-pages/ChatPage/ChatPage.tsx
  frontends/main/src/app-pages/ChatSyllabusPage/ChatSyllabusPage.tsx
  frontends/main/src/page-components/AiRecommendationBot/AiRecommendationBot.tsx
  frontends/main/src/page-components/LearningResourceDrawer/AiChatSyllabus.tsx
  yarn.lock
Labels: Waiting on author

#2044 Celery task to embed new contentfiles
  main/settings_celery.py
  vector_search/tasks.py
  vector_search/tasks_test.py
Labels: Waiting on author

#2014 Open Learning Library CSV update
  learning_resources/data/oll_metadata.csv
  learning_resources/etl/oll_test.py
Labels: Needs Review

#2058 Recommendation bot styling and text updates
  frontends/main/src/page-components/AiRecommendationBot/AiRecommendationBot.tsx
  frontends/main/src/page-components/AiRecommendationBot/AiRecommendationBotDrawer.tsx
Labels: Needs Review

#2059 Upgrade smoot-design
  frontends/main/package.json
  frontends/ol-components/package.json
  yarn.lock
Labels: Needs Review

#2066 Fix SCIM search API sort and pagination
  scim/urls.py
  scim/views.py
  scim/views_test.py
Labels: Needs Review, wontfix

#2062 Added SCIM fields to User and populate
  profiles/admin.py
  profiles/forms.py
  scim/adapters.py
  scim/views_test.py
  users/admin.py
  users/migrations/0004_add_scim_and_timestamp_fields.py
  users/migrations/0005_set_user_scim_id.py
  users/migrations/0006_remove_auth_user_view.py
  users/models.py
Labels: Needs Review

#2061 APISIX integration
  .pre-commit-config.yaml
  .secrets.baseline
  Dockerfile
  Dockerfile-litellm
  README-keycloak.md
  config/apisix/apisix.yaml
  config/apisix/config.yaml
  config/apisix/debug.yaml
  config/keycloak/providers/README.md
  config/keycloak/realms/default-realm.json
  config/keycloak/tls/README.md
  config/keycloak/tls/tls.crt
  config/keycloak/tls/tls.crt.default
  config/keycloak/tls/tls.key
  config/keycloak/tls/tls.key.default
  config/litellm_config.yml
  config/postgres/init-keycloak.sql
  docker-compose.litellm.yml
  docker-compose.services.yml
  docker-compose.yml
  env/backend.env
  env/backend.local.example.env
  env/frontend.env
  env/shared.env
  env/shared.local.example.env
  frontends/main/src/app-pages/ChatPage/ChatPage.tsx
  frontends/main/src/app-pages/ChatSyllabusPage/ChatSyllabusPage.tsx
  frontends/main/src/common/urls.ts
  frontends/main/src/page-components/AiChat/AiRecommendationBotDrawer.tsx
  frontends/main/src/page-components/LearningResourceExpanded/AiChatSyllabusSlideDown.tsx
  main/middleware/apisix_user.py
  main/middleware/apisix_user_test.py
  main/settings.py
Labels: Needs Review

#2073 Fix SCIM view tests
  main/factories.py
  scim/views.py
  scim/views_test.py
Labels: Waiting on author

#2074 Make embedding generation task use correct run
  vector_search/tasks.py
  vector_search/tasks_test.py
Labels: Waiting on author

#2084 Fix the SCIM user search URL
  scim/urls.py
Labels: Needs Review

#2089 Fix the casing of the sort field for SCIM search
  scim/constants.py
  scim/views.py
  scim/views_test.py
Labels: Needs Review
