Repository mitodl/mit-learn, pull requests merged in 2025-09, with the labels that each got.

#2480 navigate to course after one click enroll
  frontends/api/src/mitxonline/hooks/enrollment/index.ts
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/DashboardCard.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/DashboardDialogs.tsx
Labels: Needs Review

#2473 fix popularity for learningpath items
  learning_resources/models.py
  learning_resources/models_test.py
  learning_resources/views_test.py
Labels: Waiting on author

#2481 Qdrant collection and parameter updates
  vector_search/constants.py
  vector_search/utils.py
Labels: Needs Review

#2484 canvas citation fixes for files with spaces
  learning_resources/etl/utils.py
Labels: Waiting on author

#2493 Stop running Sloan news/event tasks
  main/settings_celery.py
Labels: Needs Review

#2491 adding fix for flaky test
  learning_resources/tasks_test.py
Labels: Waiting on author

#2501 Fix userlist stale data
  frontends/api/src/hooks/learningResources/index.ts
  frontends/main/src/app/dashboard/my-lists/[id]/page.tsx
Labels: Needs Review

#2502 ingest canvas html content
  learning_resources/etl/canvas.py
  learning_resources/etl/canvas_test.py
Labels: Waiting on author

#2497 Make fields for LearningResource readonly so we can access admin pages that currently 502
  learning_resources/admin.py
Labels: Waiting on author

#2510 remove priority ordering from org dashboard programs
  frontends/main/src/app-pages/DashboardPage/OrganizationContent.test.tsx
  frontends/main/src/app-pages/DashboardPage/OrganizationContent.tsx
Labels: Needs Review

#2509 canvas: ingest files referenced in content
  learning_resources/etl/canvas.py
  learning_resources/etl/canvas_test.py
Labels: Needs Review

#2513 fix course run certificate link in org dashboard
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/EnrollmentDisplay.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/transform.test.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/transform.ts
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/types.ts
  frontends/main/src/app-pages/DashboardPage/OrganizationContent.test.tsx
  frontends/main/src/app-pages/DashboardPage/OrganizationContent.tsx
Labels: Needs Review

#2495 fix mitxonline etl pagination
  learning_resources/etl/mitxonline.py
  learning_resources/etl/mitxonline_test.py
Labels: Needs Review

#2518 Fix posthog import
  learning_resources/etl/posthog.py
  learning_resources/etl/posthog_test.py
Labels: Waiting on author

#2519 Fix flaky test
  learning_resources/tasks.py
  learning_resources/tasks_test.py
Labels: Waiting on author

#2523 fix non-lexicographical ordering in org dashboard programs / program collections
  frontends/main/src/app-pages/DashboardPage/OrganizationContent.test.tsx
  frontends/main/src/app-pages/DashboardPage/OrganizationContent.tsx
Labels: Needs Review

#2535 Separate Login and Signup URLs (again)
  authentication/views.py
  authentication/views_test.py
  frontends/main/src/app-pages/B2BAttachPage/B2BAttachPage.test.tsx
  frontends/main/src/app-pages/B2BAttachPage/B2BAttachPage.tsx
  frontends/main/src/app-pages/ErrorPage/ForbiddenPage.test.tsx
  frontends/main/src/app-pages/ErrorPage/ForbiddenPage.tsx
  frontends/main/src/app-pages/HomePage/HomePage.test.tsx
  frontends/main/src/app-pages/HomePage/PersonalizeSection.tsx
  frontends/main/src/common/client-utils.ts
  frontends/main/src/common/urls.test.ts
  frontends/main/src/common/urls.ts
  frontends/main/src/components/RestrictedRoute/RestrictedRoute.tsx
  frontends/main/src/page-components/Header/Header.test.tsx
  frontends/main/src/page-components/Header/UserMenu.tsx
  frontends/main/src/page-components/SignupPopover/SignupPopover.test.tsx
  frontends/main/src/page-components/SignupPopover/SignupPopover.tsx
Labels: Needs Review

#2544 Install Granian
  poetry.lock
  pyproject.toml
Labels: DevOps, Needs Review, enhancement, Waiting on author

#2545 Celery task tweaks
  docker-compose.apps.yml
  main/celery.py
  main/settings_celery.py
  vector_search/tasks.py
Labels: Needs Review

#2512 allow multiple problem and solution files
  learning_resources/constants.py
  learning_resources/etl/canvas.py
  learning_resources/factories.py
  learning_resources/migrations/0096_tutorproblemfile_file_name.py
  learning_resources/models.py
  learning_resources/views.py
  learning_resources/views_test.py
Labels: Waiting on author

#2548 Canvas - resolve visibility of orphaned files
  learning_resources/etl/canvas.py
  learning_resources/etl/canvas_test.py
  learning_resources/etl/canvas_utils.py
Labels: Waiting on author
