Repository mitodl/mit-learn, pull requests merged in 2025-01, with the labels that each got.

#1916 remove unncessary wrapper
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceCard.tsx
Labels: Waiting on author

#1932 Shanbady/qdrant docs
  docs/how-to/embeddings.md
Labels: Waiting on author

#1650 Duration and time commitment
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/generated/v1/api.ts
  learning_resources/data/oll_metadata.csv
  learning_resources/etl/constants.py
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/etl/mitxonline.py
  learning_resources/etl/mitxonline_test.py
  learning_resources/etl/oll.py
  learning_resources/etl/oll_test.py
  learning_resources/etl/openedx.py
  learning_resources/etl/openedx_test.py
  learning_resources/etl/utils.py
  learning_resources/etl/utils_test.py
  learning_resources/etl/xpro.py
  learning_resources/etl/xpro_test.py
  learning_resources/migrations/0080_learningresource_duration_commitment.py
  learning_resources/models.py
  learning_resources/serializers_test.py
  learning_resources_search/constants.py
  openapi/specs/v0.yaml
  openapi/specs/v1.yaml
  test_json/mitxonline_courses.json
  test_json/mitxonline_programs.json
  test_json/test_mitx_course.json
  test_json/xpro_courses.json
  test_json/xpro_programs.json
Labels: Waiting on author

#1906 Duration and/or commitment for Sloan and Professional Education
  learning_resources/etl/constants.py
  learning_resources/etl/mitpe.py
  learning_resources/etl/mitpe_test.py
  learning_resources/etl/sloan.py
  learning_resources/etl/sloan_test.py
  learning_resources/etl/utils.py
  learning_resources/etl/utils_test.py
  test_json/mitpe/professional_ed_resources_0.json
Labels: Waiting on author

#1936 Import AI agent within view post code
  ai_chat/apps.py
  ai_chat/views.py
  ai_chat/views_test.py
  main/settings.py
  main/urls.py
Labels: Needs Review

#1943 Pin ubuntu to 22 (should fix release)
  .github/workflows/ci.yml
  .github/workflows/openapi-diff.yml
  .github/workflows/production.yml
  .github/workflows/publish-pages.yml
  .github/workflows/release-candidate.yml
Labels: Needs Review

#1945 dedupe edx content files further
  learning_resources/etl/utils.py
  learning_resources/etl/utils_test.py
Labels: Waiting on author

#1952 Fix SCIM API error on patch with nested attributes
  profiles/scim/adapters.py
  profiles/scim/views_test.py
Labels: Needs Review

#1950 constraining resources for celery service
  docker-compose.apps.yml
Labels: Needs Review

#1949 Dashboard Tab Keyboard Navigation
  frontends/api/package.json
  frontends/main/package.json
  frontends/main/src/app-pages/DashboardPage/Dashboard.test.tsx
  frontends/main/src/app-pages/DashboardPage/DashboardPage.tsx
  frontends/main/src/common/urls.ts
  frontends/main/src/test-utils/index.tsx
  frontends/ol-components/package.json
  frontends/ol-components/src/index.ts
  frontends/ol-test-utilities/package.json
  frontends/ol-utilities/package.json
  frontends/package.json
  yarn.lock
Labels: Needs Review

#1955 Shanbady/rename vector search endpoints
  frontends/api/src/generated/v0/api.ts
  openapi/specs/v0.yaml
  vector_search/urls.py
  vector_search/views_test.py
Labels: Needs Review

#1953 Fix Posthog multiple inits
  frontends/main/src/page-components/ConfiguredPostHogProvider/ConfiguredPostHogProvider.test.tsx
  frontends/main/src/page-components/ConfiguredPostHogProvider/ConfiguredPostHogProvider.tsx
Labels: Needs Review

#1951 fix search text
  frontends/main/src/app-pages/ChannelPage/ChannelSearch.tsx
  frontends/main/src/app-pages/SearchPage/SearchPage.test.tsx
  frontends/main/src/app-pages/SearchPage/SearchPage.tsx
Labels: Needs Review

#1959 drawer v2 design review fixes
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV2.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSectionV2.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpandedV2.tsx
  learning_resources/views.py
Labels: Waiting on author

#1961 Basic Syllabus Bot for demo
  ai_chat/agents.py
  ai_chat/serializers.py
  ai_chat/urls.py
  ai_chat/views.py
  frontends/api/src/generated/v0/api.ts
  frontends/main/package.json
  frontends/main/src/app-pages/ChatPage/ChatPage.tsx
  frontends/main/src/app-pages/ChatPage/send.ts
  frontends/main/src/app-pages/ChatSyllabusPage/ChatSyllabusPage.tsx
  frontends/main/src/app/chat_syllabus/page.tsx
  frontends/main/src/page-components/StyledContainer/StyledContainer.tsx
  main/settings.py
  openapi/specs/v0.yaml
  yarn.lock
Labels: Waiting on author

#1964 add "courses in program" carousel
  frontends/api/src/hooks/learningResources/keyFactory.ts
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV2.tsx
  frontends/main/src/page-components/ResourceCarousel/ResourceCarousel.tsx
  frontends/main/src/page-components/ResourceCarousel/types.ts
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpandedV2.tsx
Labels: Work in Progress, Waiting on author

#1965 fix drawer v2 programs flaky test
  frontends/api/src/test-utils/urls.ts
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV2.test.tsx
Labels: Waiting on author

#1960 Onboarding Accessibility Improvements
  frontends/main/src/app-pages/OnboardingPage/OnboardingPage.test.tsx
  frontends/main/src/app-pages/OnboardingPage/OnboardingPage.tsx
Labels: Needs Review

#1967 fix line clamping of HTML description
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpandedV2.tsx
Labels: Needs Review

#1966 Remove prolearn ETL code
  app.json
  env/codespaces.env
  learning_resources/etl/constants.py
  learning_resources/etl/mitpe.py
  learning_resources/etl/mitpe_test.py
  learning_resources/etl/pipelines.py
  learning_resources/etl/pipelines_test.py
  learning_resources/etl/prolearn.py
  learning_resources/etl/prolearn_test.py
  learning_resources/etl/sloan_test.py
  learning_resources/management/commands/backpopulate_prolearn_data.py
  learning_resources/tasks.py
  learning_resources/tasks_test.py
  main/settings_celery.py
  main/settings_course_etl.py
Labels: Needs Review

#1968 drawer v2 other videos in series / videos in playlist
  frontends/api/src/hooks/learningResources/keyFactory.ts
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV2.test.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV2.tsx
Labels: Needs Review

#1981 drawer v2 podcast carousels
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV2.test.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV2.tsx
Labels: Needs Review

#1982 remove the v1 drawer and rename v2 drawer
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawer.test.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawer.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV1.test.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV1.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawerV2.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/DifferingRunsTable.test.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSection.test.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSection.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSectionV1.test.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/InfoSectionV1.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.stories.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.test.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpandedV1.test.tsx
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpandedV1.tsx
  frontends/ol-components/src/index.ts
Labels: Waiting on author

#1980 variable contentfile chunk sizes
  frontends/api/src/generated/v0/api.ts
  main/settings.py
  openapi/specs/v0.yaml
  vector_search/conftest.py
  vector_search/serializers.py
  vector_search/utils.py
  vector_search/utils_test.py
  vector_search/views.py
  vector_search/views_test.py
Labels: Needs Review

#1984 drawer topic carousels should not be filtered on just courses
  frontends/main/src/app-pages/DashboardPage/DashboardPage.tsx
  frontends/main/src/common/carousels.ts
Labels: Needs Review

#1987 move LearningResourceExpanded to main
  frontends/main/package.json
  frontends/main/src/page-components/LearningResourceDrawer/DifferingRunsTable.test.tsx
  frontends/main/src/page-components/LearningResourceDrawer/DifferingRunsTable.tsx
  frontends/main/src/page-components/LearningResourceDrawer/InfoSection.test.tsx
  frontends/main/src/page-components/LearningResourceDrawer/InfoSection.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawer.test.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawer.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceExpanded.test.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceExpanded.tsx
  frontends/main/src/page-components/LearningResourceDrawer/VideoFrame.tsx
  frontends/main/src/page-components/LearningResourceDrawer/testUtils.ts
  frontends/ol-components/package.json
  frontends/ol-components/src/components/LearningResourceExpanded/LearningResourceExpanded.stories.tsx
  frontends/ol-components/src/index.ts
  frontends/ol-utilities/package.json
  yarn.lock
Labels: Needs Review

#1989 Shanbady/chunk size dropdown
  ai_chat/agents.py
  ai_chat/agents_test.py
  ai_chat/serializers.py
  ai_chat/views.py
  frontends/api/src/generated/v0/api.ts
  frontends/main/src/app-pages/ChatSyllabusPage/ChatSyllabusPage.tsx
  openapi/specs/v0.yaml
Labels: Waiting on author

#1998 Enable Posthog session replay by env var
  .github/workflows/production.yml
  .github/workflows/release-candidate.yml
  frontends/main/Dockerfile.web
  frontends/main/src/page-components/ConfiguredPostHogProvider/ConfiguredPostHogProvider.tsx
Labels: Needs Review

#1988 remove react router
  frontends/main/src/components/ChannelMenu/ChannelMenu.test.tsx
  frontends/main/src/page-components/ChannelDetails/ChannelDetails.test.tsx
  frontends/main/src/page-components/SearchDisplay/SearchDisplay.tsx
  frontends/ol-components/package.json
  frontends/ol-components/src/components/Breadcrumbs/Breadcrumbs.test.tsx
  frontends/ol-components/src/components/LearningResourceCard/LearningResourceListCard.test.tsx
  frontends/ol-components/src/components/Link/Link.tsx
  frontends/ol-components/src/components/Lists/ListItemLink.tsx
  frontends/ol-components/src/components/SimpleMenu/SimpleMenu.test.tsx
  yarn.lock
Labels: Waiting on author

#1997 track browse actions in posthog
  frontends/main/src/app-pages/ChannelPage/TopicChannelTemplate.tsx
  frontends/main/src/app-pages/DepartmentListingPage/DepartmentListingPage.tsx
  frontends/main/src/app-pages/TopicsListingPage/TopicsListingPage.tsx
  frontends/main/src/app-pages/UnitsListingPage/UnitCard.tsx
  frontends/main/src/page-components/Header/Header.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawer.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceExpanded.tsx
  frontends/ol-components/src/components/Chips/ChipLink.tsx
  frontends/ol-components/src/components/NavDrawer/NavDrawer.test.tsx
  frontends/ol-components/src/components/NavDrawer/NavDrawer.tsx
Labels: Waiting on author

#2003 reverse nav drawer posthog events
  frontends/main/src/page-components/Header/Header.tsx
Labels: Needs Review

#2001 disable daily embed task in development
  main/settings_celery.py
Labels: Needs Review

#2006 Better React Testing Library Errors
  frontends/jest-shared-setup.ts
Labels: Waiting on author

#2000 add edx block id to content files
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/generated/v1/api.ts
  learning_resources/etl/utils.py
  learning_resources/etl/utils_test.py
  learning_resources/filters.py
  learning_resources/filters_test.py
  learning_resources/migrations/0083_contentfile_edx_block_id.py
  learning_resources/models.py
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  openapi/specs/v0.yaml
  openapi/specs/v1.yaml
Labels: Needs Review

#2005 Semantic Chunking of Content Files
  main/settings.py
  poetry.lock
  pyproject.toml
  vector_search/conftest.py
  vector_search/encoders/base.py
  vector_search/encoders/fastembed.py
  vector_search/encoders/litellm.py
  vector_search/utils.py
  vector_search/utils_test.py
Labels: Needs Review
