Repository mitodl/mit-learn, pull requests merged in 2025-10, with the labels that each got.

#2550 Refactor price assignment for mitxonline
  learning_resources/etl/mitxonline.py
  learning_resources/etl/mitxonline_test.py
  test_json/mitxonline_courses.json
  test_json/mitxonline_programs.json
Labels: Waiting on author

#2552 remove old canvas problem fields
  learning_resources/views.py
  learning_resources/views_test.py
Labels: Waiting on author

#2553 Fix qdrant payload schema type and add mechanism to keep types in sync
  vector_search/constants.py
  vector_search/utils.py
  vector_search/utils_test.py
Labels: Needs Review

#2530 add "just in time" dialog
  frontends/api/package.json
  frontends/api/src/mitxonline/clients.ts
  frontends/api/src/mitxonline/hooks/user/index.ts
  frontends/api/src/mitxonline/test-utils/factories/pages.ts
  frontends/api/src/mitxonline/test-utils/urls.ts
  frontends/api/src/test-utils/mockAxios.ts
  frontends/main/package.json
  frontends/main/src/app-pages/B2BAttachPage/B2BAttachPage.test.tsx
  frontends/main/src/app-pages/B2BAttachPage/B2BAttachPage.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/DashboardCard.test.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/DashboardCard.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/DashboardDialogs.test.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/DashboardDialogs.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/EnrollmentDisplay.test.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/test-utils.ts
  frontends/main/src/app-pages/DashboardPage/DashboardLayout.test.tsx
  frontends/main/src/app-pages/DashboardPage/DashboardLayout.tsx
  frontends/main/src/app-pages/DashboardPage/HomeContent.test.tsx
  frontends/main/src/app-pages/DashboardPage/OrganizationContent.tsx
  frontends/ol-components/src/components/LoadingSpinner/LoadingSpinner.tsx
  frontends/ol-components/src/components/SimpleSelect/SimpleSelect.tsx
  yarn.lock
Labels: Needs Review, Waiting on author

#2568 truncate csv files in tutor problems api
  learning_resources/views.py
  learning_resources/views_test.py
Labels: Waiting on author

#2581 Do not overwrite canvas content from the ContentFileWebhookView
  webhooks/views.py
  webhooks/views_test.py
Labels: Needs Review
