Repository mitodl/mit-learn, pull requests merged in 2025-03, with the labels that each got.

#2103 Update README to point to separate keycloak readme
  README.md
Labels: Needs Review

#2105 Fix SCIM startIndex parsing
  scim/views.py
  scim/views_test.py
Labels: Needs Review

#2064 Handle "next" query string param in CustomLogoutView
  authentication/views.py
Labels: Waiting on author

#2050 embed course metadata as contentfile
  vector_search/serializers.py
  vector_search/tasks_test.py
  vector_search/utils.py
  vector_search/utils_test.py
Labels: Needs Review, Waiting on author

#2081 Removes env var control on session replay
  .github/workflows/production.yml
  .github/workflows/release-candidate.yml
  frontends/main/Dockerfile.web
  frontends/main/src/page-components/ConfiguredPostHogProvider/ConfiguredPostHogProvider.tsx
Labels: Needs Review

#2111 Fix stale rendering on Syllabus chat
  frontends/main/src/page-components/AiChat/AiChatWithEntryScreen.tsx
  frontends/main/src/page-components/LearningResourceExpanded/AiChatSyllabusSlideDown.tsx
Labels: Needs Review

#2109 update and rename edx_module_id
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/generated/v1/api.ts
  learning_resources/etl/utils.py
  learning_resources/etl/utils_test.py
  learning_resources/filters.py
  learning_resources/filters_test.py
  learning_resources/migrations/0084_rename_edx_block_id_contentfile_edx_module_id.py
  learning_resources/models.py
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  openapi/specs/v0.yaml
  openapi/specs/v1.yaml
  vector_search/constants.py
  vector_search/serializers.py
Labels: Waiting on author

#2115 removing school from departments display
  vector_search/serializers.py
  vector_search/tasks_test.py
Labels: Needs Review

#2114 Always show chat entry screen when navigating courses
  frontends/main/src/page-components/LearningResourceExpanded/AiChatSyllabusSlideDown.tsx
Labels: Needs Review

#2121 fix asset ids
  learning_resources/etl/utils.py
  learning_resources/etl/utils_test.py
Labels: Waiting on author

#2120 Store (and embed) marketing page info as a contentfile
  ai_chat/agents_test.py
  ai_chat/factories.py
  learning_resources/conftest.py
  learning_resources/etl/constants.py
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/etl/utils.py
  learning_resources/migrations/0085_contentfile_learning_resource_alter_contentfile_run.py
  learning_resources/migrations/0086_contentfile_run_or_resource_defined.py
  learning_resources/models.py
  poetry.lock
  pyproject.toml
Labels: Waiting on author

#2110 Chatbot UI issues
  frontends/main/package.json
  frontends/main/src/page-components/AiChat/AiChatWithEntryScreen.tsx
  frontends/main/src/page-components/AiChat/AiRecommendationBotDrawer.tsx
  frontends/main/src/page-components/AiChat/AskTimDrawerButton.tsx
  frontends/main/src/page-components/AiChat/useScrollSnap.tsx
  frontends/main/src/page-components/LearningResourceDrawer/LearningResourceDrawer.tsx
  frontends/main/src/page-components/LearningResourceExpanded/AiChatSyllabusSlideDown.test.tsx
  frontends/main/src/page-components/LearningResourceExpanded/AiChatSyllabusSlideDown.tsx
  frontends/main/src/page-components/LearningResourceExpanded/LearningResourceExpanded.tsx
  frontends/main/src/page-components/LearningResourceExpanded/TitleSection.tsx
  frontends/ol-components/package.json
  yarn.lock
Labels: Needs Review

#2119 Create/login/logout users via apisix middleware only
  .github/workflows/production.yml
  .github/workflows/release-candidate.yml
  README-keycloak.md
  authentication/api.py
  authentication/api_test.py
  authentication/backends/ol_open_id_connect.py
  authentication/middleware.py
  authentication/middleware_test.py
  authentication/models_test.py
  authentication/pipeline/__init__.py
  authentication/pipeline/user.py
  authentication/pipeline/user_test.py
  authentication/urls.py
  authentication/views.py
  authentication/views_test.py
  config/apisix/apisix.yaml
  config/keycloak/realms/default-realm.json
  env/backend.local.example.env
  env/frontend.env
  env/shared.env
  frontends/main/Dockerfile.web
  frontends/main/src/common/urls.test.ts
  frontends/main/src/common/urls.ts
  main/factories.py
  main/features.py
  main/middleware/apisix_user.py
  main/middleware/apisix_user_test.py
  main/settings.py
  scim/adapters.py
  scim/views_test.py
  users/migrations/0006_user_global_id.py
  users/migrations/0007_user_global_id_assign.py
  users/models.py
Labels: Needs Review

#2126 Remove comma from ci files
  .github/workflows/production.yml
  .github/workflows/release-candidate.yml
Labels: Needs Review

#2135 Fix contentfile embeddings
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/generated/v1/api.ts
  learning_resources/factories.py
  learning_resources/serializers.py
  learning_resources/views_test.py
  learning_resources_search/serializers.py
  openapi/specs/v0.yaml
  openapi/specs/v1.yaml
  vector_search/tasks.py
  vector_search/tasks_test.py
  vector_search/utils.py
Labels: Waiting on author

#2140 Parameterize MITOL_API_BASE_URL in deployment workflows
  .github/workflows/production.yml
  .github/workflows/release-candidate.yml
Labels: DevOps

#2141 global_id migrations based on scim id
  main/middleware/apisix_user.py
  main/middleware/apisix_user_test.py
  users/migrations/0008_alter_user_global_id.py
  users/migrations/0009_user_global_id_assign_scim.py
  users/migrations/0010_alter_user_global_id.py
Labels: Needs Review

#2139 Consolidate learning resource display logic into the backend
  frontends/api/src/generated/v1/api.ts
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  learning_resources/urls.py
  learning_resources/utils.py
  learning_resources/utils_test.py
  learning_resources/views.py
  learning_resources/views_test.py
  learning_resources_search/serializers_test.py
  openapi/specs/v1.yaml
  poetry.lock
  pyproject.toml
  vector_search/constants.py
  vector_search/serializers.py
  vector_search/serializers_test.py
  vector_search/utils.py
  vector_search/utils_test.py
Labels: Needs Review

#2151 Fix flaky JS test
  frontends/main/src/app-pages/DashboardPage/EnrollmentDisplay/EnrollmentCard.test.tsx
Labels: Needs Review

#2144 qdrant performance tweaks
  learning_resources/views_test.py
  vector_search/constants.py
  vector_search/utils.py
Labels: Waiting on author

#2152 typeerror nonetype error
  learning_resources/serializers.py
  learning_resources/views_test.py
Labels: Needs Review

#2154 design refactor: make link black style bolder
  frontends/main/src/app-pages/DashboardPage/EnrollmentDisplay/EnrollmentCard.tsx
  frontends/main/src/app-pages/DashboardPage/SettingsContent.tsx
  frontends/main/src/app-pages/TopicsListingPage/TopicsListingPage.tsx
  frontends/main/src/page-components/HeroSearch/HeroSearch.tsx
  frontends/main/src/page-components/ItemsListing/ItemsListingComponent.tsx
  frontends/main/src/page-components/LearningResourceExpanded/CallToActionSection.tsx
  frontends/ol-components/src/components/Card/Card.tsx
  frontends/ol-components/src/components/Link/Link.tsx
Labels: Needs Review

#2155 Fix broken test test_certificate_display
  learning_resources/serializers.py
  learning_resources/serializers_test.py
Labels: Needs Review

#2145 Enable redirects on logout
  README-keycloak.md
  authentication/views.py
  authentication/views_test.py
  env/backend.local.example.env
  main/middleware/apisix_user.py
  main/settings.py
Labels: Needs Review

#2159 Make gemini optional by request
  .gemini/config.yaml
  .gemini/styleguide.md
Labels: Waiting on author

#2158 Fix for potential missing file attribute in contentfile json
  learning_resources/etl/ocw.py
  learning_resources/etl/ocw_test.py
  learning_resources/etl/pipelines_test.py
  learning_resources_search/api_test.py
  learning_resources_search/plugins.py
  test_json/courses/16-01-unified-engineering-i-ii-iii-iv-fall-2005-spring-2006/resources/resource_no_file/data.json
  test_json/courses/16-01-unified-engineering-i-ii-iii-iv-fall-2005-spring-2006/resources/video_no_file/data.json
Labels: Needs Review

#2162 Decrease lookback window for embedding new resources and contentfiles
  main/settings.py
  main/settings_celery.py
  vector_search/tasks.py
  vector_search/tasks_test.py
Labels: Waiting on author
