Repository mitodl/mit-learn, pull requests merged in 2025-05, with the labels that each got.

#2222 Force https for urls in scraper
  learning_resources/site_scrapers/utils.py
  learning_resources/site_scrapers/utils_test.py
Labels: Needs Review

#2221 Static header for accessible drawer content at page magnification
  frontends/main/src/page-components/LearningResourceExpanded/AiChatSyllabusSlideDown.tsx
  frontends/main/src/page-components/LearningResourceExpanded/LearningResourceExpanded.test.tsx
  frontends/main/src/page-components/LearningResourceExpanded/LearningResourceExpanded.tsx
  frontends/main/src/page-components/LearningResourceExpanded/TitleSection.tsx
Labels: Needs Review

#2219 update coursenumber weight in search
  learning_resources_search/api_test.py
  learning_resources_search/constants.py
Labels: Needs Review

#2217 embedding content updates and removals
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/generated/v1/api.ts
  learning_resources/etl/edx_shared_test.py
  learning_resources/etl/loaders_test.py
  learning_resources/etl/utils.py
  learning_resources/etl/utils_test.py
  learning_resources/migrations/0089_contentfile_archive_checksum.py
  learning_resources/models.py
  learning_resources/serializers.py
  learning_resources/serializers_test.py
  learning_resources_search/plugins.py
  learning_resources_search/plugins_test.py
  main/settings.py
  openapi/specs/v0.yaml
  openapi/specs/v1.yaml
  vector_search/constants.py
  vector_search/tasks.py
  vector_search/utils.py
  vector_search/utils_test.py
Labels: Needs Review

#2231 UAI dashboard - unenrolled module card changes
  frontends/main/public/images/icons/course-unenrolled.svg
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/DashboardCard.test.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/DashboardCard.tsx
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/EnrollmentStatusIndicator.tsx
Labels: Needs Review

#2233 Remove param based onboarding navigation
  authentication/views.py
  authentication/views_test.py
  frontends/main/src/app-pages/OnboardingPage/OnboardingPage.test.tsx
  frontends/main/src/app-pages/OnboardingPage/OnboardingPage.tsx
Labels: Waiting on author

#2224 ingestion of test/sandbox courses
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/generated/v1/api.ts
  learning_resources/etl/edx_shared.py
  learning_resources/etl/loaders_test.py
  learning_resources/etl/mitxonline.py
  learning_resources/etl/mitxonline_test.py
  learning_resources/management/commands/backpopulate_micromasters_data.py
  learning_resources/management/commands/backpopulate_mit_edx_data.py
  learning_resources/management/commands/backpopulate_mit_edx_files.py
  learning_resources/management/commands/backpopulate_mitpe_data.py
  learning_resources/management/commands/backpopulate_mitxonline_data.py
  learning_resources/management/commands/backpopulate_mitxonline_files.py
  learning_resources/management/commands/backpopulate_ocw_data.py
  learning_resources/management/commands/backpopulate_oll_data.py
  learning_resources/management/commands/backpopulate_oll_files.py
  learning_resources/management/commands/backpopulate_sloan_data.py
  learning_resources/management/commands/backpopulate_xpro_data.py
  learning_resources/management/commands/backpopulate_xpro_files.py
  learning_resources/management/commands/mixins.py
  learning_resources/migrations/0090_learningresource_test_mode.py
  learning_resources/models.py
  learning_resources/serializers_test.py
  learning_resources/tasks.py
  learning_resources/tasks_test.py
  learning_resources_search/indexing_api.py
  openapi/specs/v0.yaml
  openapi/specs/v1.yaml
  vector_search/tasks.py
Labels: Waiting on author

#2236 Less noisy openapi-diff action.
  .github/workflows/openapi-diff.yml
Labels: Needs Review

#2237 Tracking user account creation event in posthog
  main/constants.py
  main/middleware/apisix_user.py
  main/middleware/apisix_user_test.py
Labels: Needs Review

#2239 Set card link on org dashboard pages to courseware url
  frontends/main/src/app-pages/DashboardPage/CoursewareDisplay/DashboardCard.tsx
  frontends/main/src/app-pages/DashboardPage/OrganizationContent.tsx
Labels: Needs Review

#2246 Fix flaky test
  profiles/serializers_test.py
Labels: Needs Review

#2242 Ensure celery tasks execute once
  docker-compose.apps.yml
  main/settings_celery.py
  poetry.lock
  pyproject.toml
Labels: Waiting on author

#2247 feat: Add health check
  .github/workflows/ci.yml
  Dockerfile
  main/settings.py
  main/settings_celery.py
  main/urls.py
  poetry.lock
  pyproject.toml
Labels: Waiting on author

#2260 Make Dockerfile.web a multistage build
  frontends/main/Dockerfile.web
Labels: DevOps, enhancement

#2262 Prevent test courses from being overwritten
  learning_resources/etl/loaders.py
  learning_resources/etl/loaders_test.py
  learning_resources/management/commands/mixins.py
Labels: Needs Review
